import type { Locale } from "../i18n/types";
import { SKILL_CATEGORY_LABELS } from "../i18n/terms";

const ATTACK_INDEX_RE = /_attack(\d+)(?:$|_)/i;
const COMBO_SKILL_KEY_RE = /(?:^|_)combo(?:_\d+)?_skill(?:$|_)/i;

const ELEMENT_ZH_TO_EN: Record<string, string> = {
  物理: "Physical",
  灼热: "Heat",
  电磁: "Pulse",
  寒冷: "Cryo",
  自然: "Nature",
  法术: "Arts",
  火: "Heat",
  雷: "Pulse",
  冰: "Cryo",
};

const ELEMENT_EN_TO_ZH: Record<string, string> = {
  Physical: "物理",
  Heat: "灼热",
  Pulse: "电磁",
  Cryo: "寒冷",
  Nature: "自然",
  Arts: "法术",
};

export const SKILL_KEY_OVERRIDES: Record<string, { zh: string; en: string }> = {
  "buff_chr_0028_wulfa_combo_2_damage": { zh: "燎影时刻", en: "Moment of Blazing Shadow" },
  "buff_chr_0028_wulfa_normal_bleed": { zh: "爪印斫痕", en: "Claw Slash" },
  "buff_chr_0028_wulfa_normal_bleed_crit_extra_damage": { zh: "沸血", en: "Boiling Blood" },
  "buff_chr_0028_wulfa_normal_bleed_effect": { zh: "爪印斫痕", en: "Claw Slash" },
  "buff_common_cryst_triggered_physical_break": { zh: "寒冷击破触发", en: "Cryo Break Trigger" },
  "buff_common_heal_moss_1": { zh: "治疗苔藓", en: "Healing Moss" },
  "buff_common_heal_moss_2": { zh: "治疗苔藓", en: "Healing Moss" },
  "buff_common_originum_frozen": { zh: "源石冻结", en: "Originium Freeze" },
  "buff_physical_airborne": { zh: "物理浮空伤害", en: "Physical Airborne DMG" },
  "buff_physical_crushed": { zh: "猛击", en: "Crush" },
  "buff_physical_knockdown": { zh: "倒地", en: "Knock Down" },
  "buff_physical_no_guard": { zh: "破防", en: "Breach" },
  "chr_0002_endminm_attack1": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0002_endminm_attack2": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0002_endminm_attack3": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0002_endminm_attack4": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0002_endminm_attack5": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0002_endminm_combo_skill": { zh: "锁闭序列", en: "Sealing Sequence" },
  "chr_0002_endminm_comboskill": { zh: "锁闭序列", en: "Sealing Sequence" },
  "chr_0002_endminm_normal_attack": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0002_endminm_normal_skill": { zh: "构成序列", en: "Constructive Sequence" },
  "chr_0002_endminm_normalattack": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0002_endminm_normalskill": { zh: "构成序列", en: "Constructive Sequence" },
  "chr_0002_endminm_plunging_attack_end": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0002_endminm_power_attack": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0002_endminm_ultimate_skill": { zh: "轰击序列", en: "Bombardment Sequence" },
  "chr_0002_endminm_ultimateskill": { zh: "轰击序列", en: "Bombardment Sequence" },
  "chr_0003_endminf_attack1": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0003_endminf_attack2": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0003_endminf_attack3": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0003_endminf_attack4": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0003_endminf_attack5": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0003_endminf_combo_skill": { zh: "锁闭序列", en: "Sealing Sequence" },
  "chr_0003_endminf_comboskill": { zh: "锁闭序列", en: "Sealing Sequence" },
  "chr_0003_endminf_normal_attack": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0003_endminf_normal_skill": { zh: "构成序列", en: "Constructive Sequence" },
  "chr_0003_endminf_normalattack": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0003_endminf_normalskill": { zh: "构成序列", en: "Constructive Sequence" },
  "chr_0003_endminf_plunging_attack_end": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0003_endminf_power_attack2": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_0003_endminf_ultimate_skill": { zh: "轰击序列", en: "Bombardment Sequence" },
  "chr_0003_endminf_ultimateskill": { zh: "轰击序列", en: "Bombardment Sequence" },
  "chr_0004_pelica_attack1": { zh: "协议α·突破", en: "Protocol \u03b1: Breach" },
  "chr_0004_pelica_attack2": { zh: "协议α·突破", en: "Protocol \u03b1: Breach" },
  "chr_0004_pelica_attack3": { zh: "协议α·突破", en: "Protocol \u03b1: Breach" },
  "chr_0004_pelica_attack4": { zh: "协议α·突破", en: "Protocol \u03b1: Breach" },
  "chr_0004_pelica_combo_skill": { zh: "即时协议·闪链", en: "Instant Protocol: Chain" },
  "chr_0004_pelica_comboskill": { zh: "即时协议·闪链", en: "Instant Protocol: Chain" },
  "chr_0004_pelica_normal_attack": { zh: "协议α·突破", en: "Protocol \u03b1: Breach" },
  "chr_0004_pelica_normal_skill": { zh: "协议ω·雷击", en: "Protocol \u03c9: Strike" },
  "chr_0004_pelica_normalattack": { zh: "协议α·突破", en: "Protocol \u03b1: Breach" },
  "chr_0004_pelica_normalskill": { zh: "协议ω·雷击", en: "Protocol \u03c9: Strike" },
  "chr_0004_pelica_plunging_attack_end": { zh: "协议α·突破", en: "Protocol \u03b1: Breach" },
  "chr_0004_pelica_power_attack": { zh: "协议α·突破", en: "Protocol \u03b1: Breach" },
  "chr_0004_pelica_ultimate_skill": { zh: "协议ε·70.41κ", en: "Protocol \u03b5: 70.41K" },
  "chr_0004_pelica_ultimateskill": { zh: "协议ε·70.41κ", en: "Protocol \u03b5: 70.41K" },
  "chr_0005_chen_attack1": { zh: "破飞霞", en: "Soaring Break" },
  "chr_0005_chen_attack2": { zh: "破飞霞", en: "Soaring Break" },
  "chr_0005_chen_attack3": { zh: "破飞霞", en: "Soaring Break" },
  "chr_0005_chen_attack4": { zh: "破飞霞", en: "Soaring Break" },
  "chr_0005_chen_attack5": { zh: "破飞霞", en: "Soaring Break" },
  "chr_0005_chen_combo_skill": { zh: "见天河", en: "Soar to the Stars" },
  "chr_0005_chen_comboskill": { zh: "见天河", en: "Soar to the Stars" },
  "chr_0005_chen_normal_attack": { zh: "破飞霞", en: "Soaring Break" },
  "chr_0005_chen_normal_skill": { zh: "归穹宇", en: "Ascending Strike" },
  "chr_0005_chen_normalattack": { zh: "破飞霞", en: "Soaring Break" },
  "chr_0005_chen_normalskill": { zh: "归穹宇", en: "Ascending Strike" },
  "chr_0005_chen_plunging_attack_end": { zh: "破飞霞", en: "Soaring Break" },
  "chr_0005_chen_power_attack": { zh: "破飞霞", en: "Soaring Break" },
  "chr_0005_chen_ultimate_skill": { zh: "冽风霜", en: "Blade Gale" },
  "chr_0005_chen_ultimateskill": { zh: "冽风霜", en: "Blade Gale" },
  "chr_0006_wolfgd_attack1": { zh: "多重连射", en: "Rapid Fire Akimbo" },
  "chr_0006_wolfgd_attack2": { zh: "多重连射", en: "Rapid Fire Akimbo" },
  "chr_0006_wolfgd_attack3": { zh: "多重连射", en: "Rapid Fire Akimbo" },
  "chr_0006_wolfgd_attack4": { zh: "多重连射", en: "Rapid Fire Akimbo" },
  "chr_0006_wolfgd_combo_skill": { zh: "爆裂手雷·β型", en: "Frag Grenade\u00b7\u03b2" },
  "chr_0006_wolfgd_comboskill": { zh: "爆裂手雷·β型", en: "Frag Grenade\u00b7\u03b2" },
  "chr_0006_wolfgd_normal_attack": { zh: "多重连射", en: "Rapid Fire Akimbo" },
  "chr_0006_wolfgd_normal_skill": { zh: "灼热弹痕", en: "Thermite Tracers" },
  "chr_0006_wolfgd_normalattack": { zh: "多重连射", en: "Rapid Fire Akimbo" },
  "chr_0006_wolfgd_normalskill": { zh: "灼热弹痕", en: "Thermite Tracers" },
  "chr_0006_wolfgd_plunging_attack_end": { zh: "多重连射", en: "Rapid Fire Akimbo" },
  "chr_0006_wolfgd_power_attack": { zh: "多重连射", en: "Rapid Fire Akimbo" },
  "chr_0006_wolfgd_ultimate_skill": { zh: "狼之怒", en: "Wolven Fury" },
  "chr_0006_wolfgd_ultimateskill": { zh: "狼之怒", en: "Wolven Fury" },
  "chr_0007_ikut_attack1": { zh: "循迹逐猎", en: "Seek and Hunt" },
  "chr_0007_ikut_attack2": { zh: "循迹逐猎", en: "Seek and Hunt" },
  "chr_0007_ikut_attack3": { zh: "循迹逐猎", en: "Seek and Hunt" },
  "chr_0007_ikut_attack4": { zh: "循迹逐猎", en: "Seek and Hunt" },
  "chr_0007_ikut_attack5": { zh: "循迹逐猎", en: "Seek and Hunt" },
  "chr_0007_ikut_combo_skill": { zh: "鸣雷", en: "Peal of Thunder" },
  "chr_0007_ikut_comboskill": { zh: "鸣雷", en: "Peal of Thunder" },
  "chr_0007_ikut_normal_attack": { zh: "循迹逐猎", en: "Seek and Hunt" },
  "chr_0007_ikut_normal_skill": { zh: "疾风迅雷", en: "Tempestuous Arc" },
  "chr_0007_ikut_normalattack": { zh: "循迹逐猎", en: "Seek and Hunt" },
  "chr_0007_ikut_normalskill": { zh: "疾风迅雷", en: "Tempestuous Arc" },
  "chr_0007_ikut_plunging_attack_end": { zh: "循迹逐猎", en: "Seek and Hunt" },
  "chr_0007_ikut_power_attack": { zh: "循迹逐猎", en: "Seek and Hunt" },
  "chr_0007_ikut_ultimate_skill": { zh: "轰雷掣电", en: "Exploding Blitz" },
  "chr_0007_ikut_ultimateskill": { zh: "轰雷掣电", en: "Exploding Blitz" },
  "chr_0009_azrila_attack1": { zh: "陷阵剑术", en: "Sword Art of Assault" },
  "chr_0009_azrila_attack2": { zh: "陷阵剑术", en: "Sword Art of Assault" },
  "chr_0009_azrila_attack3": { zh: "陷阵剑术", en: "Sword Art of Assault" },
  "chr_0009_azrila_attack4": { zh: "陷阵剑术", en: "Sword Art of Assault" },
  "chr_0009_azrila_combo_skill": { zh: "前线援护", en: "Frontline Support" },
  "chr_0009_azrila_comboskill": { zh: "前线援护", en: "Frontline Support" },
  "chr_0009_azrila_normal_attack": { zh: "陷阵剑术", en: "Sword Art of Assault" },
  "chr_0009_azrila_normal_skill": { zh: "进军", en: "Forward March" },
  "chr_0009_azrila_normalattack": { zh: "陷阵剑术", en: "Sword Art of Assault" },
  "chr_0009_azrila_normalskill": { zh: "进军", en: "Forward March" },
  "chr_0009_azrila_plunging_attack_end": { zh: "陷阵剑术", en: "Sword Art of Assault" },
  "chr_0009_azrila_power_attack": { zh: "陷阵剑术", en: "Sword Art of Assault" },
  "chr_0009_azrila_ultimate_skill": { zh: "重燃誓约", en: "Re-Ignited Oath" },
  "chr_0009_azrila_ultimateskill": { zh: "重燃誓约", en: "Re-Ignited Oath" },
  "chr_0011_seraph_attack1": { zh: "冷却", en: "Cooldown" },
  "chr_0011_seraph_attack2": { zh: "冷却", en: "Cooldown" },
  "chr_0011_seraph_attack3": { zh: "冷却", en: "Cooldown" },
  "chr_0011_seraph_attack4": { zh: "冷却", en: "Cooldown" },
  "chr_0011_seraph_attack5": { zh: "冷却", en: "Cooldown" },
  "chr_0011_seraph_combo_skill": { zh: "压力测试", en: "Stress Testing" },
  "chr_0011_seraph_comboskill": { zh: "压力测试", en: "Stress Testing" },
  "chr_0011_seraph_normal_attack": { zh: "冷却", en: "Cooldown" },
  "chr_0011_seraph_normal_skill": { zh: "分布式拒绝服务", en: "Distributed DoS" },
  "chr_0011_seraph_normalattack": { zh: "冷却", en: "Cooldown" },
  "chr_0011_seraph_normalskill": { zh: "分布式拒绝服务", en: "Distributed DoS" },
  "chr_0011_seraph_plunging_attack_end": { zh: "冷却", en: "Cooldown" },
  "chr_0011_seraph_power_attack": { zh: "冷却", en: "Cooldown" },
  "chr_0011_seraph_ultimate_skill": { zh: "栈溢出", en: "Stack Overflow" },
  "chr_0011_seraph_ultimateskill": { zh: "栈溢出", en: "Stack Overflow" },
  "chr_0012_avywen_attack1": { zh: "雷枪·疾袭", en: "Thunderlance: Blitz" },
  "chr_0012_avywen_attack2": { zh: "雷枪·疾袭", en: "Thunderlance: Blitz" },
  "chr_0012_avywen_attack3": { zh: "雷枪·疾袭", en: "Thunderlance: Blitz" },
  "chr_0012_avywen_attack4": { zh: "雷枪·疾袭", en: "Thunderlance: Blitz" },
  "chr_0012_avywen_attack5": { zh: "雷枪·疾袭", en: "Thunderlance: Blitz" },
  "chr_0012_avywen_combo_skill": { zh: "雷枪·掣击", en: "Thunderlance: Strike" },
  "chr_0012_avywen_comboskill": { zh: "雷枪·掣击", en: "Thunderlance: Strike" },
  "chr_0012_avywen_normal_attack": { zh: "雷枪·疾袭", en: "Thunderlance: Blitz" },
  "chr_0012_avywen_normal_skill": { zh: "雷枪·截回", en: "Thunderlance: Interdiction" },
  "chr_0012_avywen_normalattack": { zh: "雷枪·疾袭", en: "Thunderlance: Blitz" },
  "chr_0012_avywen_normalskill": { zh: "雷枪·截回", en: "Thunderlance: Interdiction" },
  "chr_0012_avywen_plunging_attack_end": { zh: "雷枪·疾袭", en: "Thunderlance: Blitz" },
  "chr_0012_avywen_power_attack": { zh: "雷枪·疾袭", en: "Thunderlance: Blitz" },
  "chr_0012_avywen_ultimate_skill": { zh: "雷枪·决颤", en: "Thunderlance: Final Shock" },
  "chr_0012_avywen_ultimateskill": { zh: "雷枪·决颤", en: "Thunderlance: Final Shock" },
  "chr_0013_aglina_attack1": { zh: "秘杖·束能技艺", en: "Arcane Staff: Beam Cohesion Arts" },
  "chr_0013_aglina_attack2": { zh: "秘杖·束能技艺", en: "Arcane Staff: Beam Cohesion Arts" },
  "chr_0013_aglina_attack3": { zh: "秘杖·束能技艺", en: "Arcane Staff: Beam Cohesion Arts" },
  "chr_0013_aglina_attack4": { zh: "秘杖·束能技艺", en: "Arcane Staff: Beam Cohesion Arts" },
  "chr_0013_aglina_combo_skill": { zh: "秘杖·矩阵位移", en: "Arcane Staff: Matrix Displacement" },
  "chr_0013_aglina_comboskill": { zh: "秘杖·矩阵位移", en: "Arcane Staff: Matrix Displacement" },
  "chr_0013_aglina_normal_attack": { zh: "秘杖·束能技艺", en: "Arcane Staff: Beam Cohesion Arts" },
  "chr_0013_aglina_normal_skill": { zh: "秘杖·引力模式", en: "Arcane Staff: Gravity Mode" },
  "chr_0013_aglina_normalattack": { zh: "秘杖·束能技艺", en: "Arcane Staff: Beam Cohesion Arts" },
  "chr_0013_aglina_normalskill": { zh: "秘杖·引力模式", en: "Arcane Staff: Gravity Mode" },
  "chr_0013_aglina_plunging_attack_end": { zh: "秘杖·束能技艺", en: "Arcane Staff: Beam Cohesion Arts" },
  "chr_0013_aglina_power_attack": { zh: "秘杖·束能技艺", en: "Arcane Staff: Beam Cohesion Arts" },
  "chr_0013_aglina_ultimate_skill": { zh: "秘杖·重力场", en: "Arcane Staff: Gravity Field" },
  "chr_0013_aglina_ultimateskill": { zh: "秘杖·重力场", en: "Arcane Staff: Gravity Field" },
  "chr_0014_aurora_attack1": { zh: "失温猛击", en: "Hypothermic Assault" },
  "chr_0014_aurora_attack2": { zh: "失温猛击", en: "Hypothermic Assault" },
  "chr_0014_aurora_attack3": { zh: "失温猛击", en: "Hypothermic Assault" },
  "chr_0014_aurora_combo_skill": { zh: "极地救援", en: "Polar Rescue" },
  "chr_0014_aurora_comboskill": { zh: "极地救援", en: "Polar Rescue" },
  "chr_0014_aurora_normal_attack": { zh: "失温猛击", en: "Hypothermic Assault" },
  "chr_0014_aurora_normal_skill": { zh: "饱和性防御", en: "Saturated Defense" },
  "chr_0014_aurora_normalattack": { zh: "失温猛击", en: "Hypothermic Assault" },
  "chr_0014_aurora_normalskill": { zh: "饱和性防御", en: "Saturated Defense" },
  "chr_0014_aurora_plunging_attack_end": { zh: "失温猛击", en: "Hypothermic Assault" },
  "chr_0014_aurora_power_attack": { zh: "失温猛击", en: "Hypothermic Assault" },
  "chr_0014_aurora_ultimate_skill": { zh: "凛冽寒霜", en: "Frigid Snowfield" },
  "chr_0014_aurora_ultimateskill": { zh: "凛冽寒霜", en: "Frigid Snowfield" },
  "chr_0015_lifeng_attack1": { zh: "摧破", en: "Ruination" },
  "chr_0015_lifeng_attack2": { zh: "摧破", en: "Ruination" },
  "chr_0015_lifeng_attack3": { zh: "摧破", en: "Ruination" },
  "chr_0015_lifeng_attack5": { zh: "摧破", en: "Ruination" },
  "chr_0015_lifeng_combo_skill": { zh: "忿怒相", en: "Aspect of Wrath" },
  "chr_0015_lifeng_comboskill": { zh: "忿怒相", en: "Aspect of Wrath" },
  "chr_0015_lifeng_normal_attack": { zh: "摧破", en: "Ruination" },
  "chr_0015_lifeng_normal_skill": { zh: "荡浊身", en: "Turbid Avatar" },
  "chr_0015_lifeng_normalattack": { zh: "摧破", en: "Ruination" },
  "chr_0015_lifeng_normalskill": { zh: "荡浊身", en: "Turbid Avatar" },
  "chr_0015_lifeng_plunging_attack_end": { zh: "摧破", en: "Ruination" },
  "chr_0015_lifeng_power_attack": { zh: "摧破", en: "Ruination" },
  "chr_0015_lifeng_ultimate_skill": { zh: "不动心", en: "Heart of the Unmoving" },
  "chr_0015_lifeng_ultimateskill": { zh: "不动心", en: "Heart of the Unmoving" },
  "chr_0016_laevat_attack1": { zh: "燃烬", en: "Flaming Cinders" },
  "chr_0016_laevat_attack2": { zh: "燃烬", en: "Flaming Cinders" },
  "chr_0016_laevat_attack3": { zh: "燃烬", en: "Flaming Cinders" },
  "chr_0016_laevat_attack4": { zh: "燃烬", en: "Flaming Cinders" },
  "chr_0016_laevat_attack5": { zh: "燃烬", en: "Flaming Cinders" },
  "chr_0016_laevat_combo_skill": { zh: "沸腾", en: "Seethe" },
  "chr_0016_laevat_comboskill": { zh: "沸腾", en: "Seethe" },
  "chr_0016_laevat_normal_attack": { zh: "燃烬", en: "Flaming Cinders" },
  "chr_0016_laevat_normal_skill": { zh: "焚灭", en: "Smouldering Fire" },
  "chr_0016_laevat_normal_skill_during_ult": { zh: "焚灭", en: "Smouldering Fire" },
  "chr_0016_laevat_normalattack": { zh: "燃烬", en: "Flaming Cinders" },
  "chr_0016_laevat_normalskill": { zh: "焚灭", en: "Smouldering Fire" },
  "chr_0016_laevat_plunging_attack_end": { zh: "燃烬", en: "Flaming Cinders" },
  "chr_0016_laevat_power_attack": { zh: "燃烬", en: "Flaming Cinders" },
  "chr_0016_laevat_ult_attack1": { zh: "黄昏", en: "Twilight" },
  "chr_0016_laevat_ult_attack2": { zh: "黄昏", en: "Twilight" },
  "chr_0016_laevat_ult_attack3": { zh: "黄昏", en: "Twilight" },
  "chr_0016_laevat_ult_attack4": { zh: "黄昏", en: "Twilight" },
  "chr_0016_laevat_ultimate_skill": { zh: "黄昏", en: "Twilight" },
  "chr_0016_laevat_ultimateskill": { zh: "黄昏", en: "Twilight" },
  "chr_0017_yvonne_attack1": { zh: "雀跃扳机", en: "Exuberant Trigger" },
  "chr_0017_yvonne_attack2": { zh: "雀跃扳机", en: "Exuberant Trigger" },
  "chr_0017_yvonne_attack3": { zh: "雀跃扳机", en: "Exuberant Trigger" },
  "chr_0017_yvonne_attack4": { zh: "雀跃扳机", en: "Exuberant Trigger" },
  "chr_0017_yvonne_attack5": { zh: "雀跃扳机", en: "Exuberant Trigger" },
  "chr_0017_yvonne_combo_skill": { zh: "速冻仔·υ37", en: "Flashfreezer \u03c537" },
  "chr_0017_yvonne_comboskill": { zh: "速冻仔·υ37", en: "Flashfreezer \u03c537" },
  "chr_0017_yvonne_normal_attack": { zh: "雀跃扳机", en: "Exuberant Trigger" },
  "chr_0017_yvonne_normal_skill": { zh: "冰冰弹·β型", en: "Brr-Brr-Bomb \u03b2" },
  "chr_0017_yvonne_normalattack": { zh: "雀跃扳机", en: "Exuberant Trigger" },
  "chr_0017_yvonne_normalskill": { zh: "冰冰弹·β型", en: "Brr-Brr-Bomb \u03b2" },
  "chr_0017_yvonne_plunging_attack_end": { zh: "雀跃扳机", en: "Exuberant Trigger" },
  "chr_0017_yvonne_power_attack": { zh: "雀跃扳机", en: "Exuberant Trigger" },
  "chr_0017_yvonne_skill_162": { zh: "伊冯连携 / 机器人持续伤害", en: "Yvonne Combo / Drone DoT" },
  "chr_0017_yvonne_skill_163": { zh: "伊冯连携 / 机器人终结爆炸", en: "Yvonne Combo / Drone Final Explosion" },
  "chr_0017_yvonne_ult_attack1_1": { zh: "冷冻射手", en: "Cryoblasting Pistolier" },
  "chr_0017_yvonne_ult_attack2_1": { zh: "冷冻射手", en: "Cryoblasting Pistolier" },
  "chr_0017_yvonne_ult_attack2_2": { zh: "冷冻射手", en: "Cryoblasting Pistolier" },
  "chr_0017_yvonne_ult_attack3_1": { zh: "冷冻射手", en: "Cryoblasting Pistolier" },
  "chr_0017_yvonne_ult_attack3_2": { zh: "冷冻射手", en: "Cryoblasting Pistolier" },
  "chr_0017_yvonne_ult_attack_end": { zh: "冷冻射手", en: "Cryoblasting Pistolier" },
  "chr_0017_yvonne_ultimate_skill": { zh: "冷冻射手", en: "Cryoblasting Pistolier" },
  "chr_0017_yvonne_ultimateskill": { zh: "冷冻射手", en: "Cryoblasting Pistolier" },
  "chr_0018_dapan_attack1": { zh: "滚刀切！", en: "ROLLING CUT!" },
  "chr_0018_dapan_attack2": { zh: "滚刀切！", en: "ROLLING CUT!" },
  "chr_0018_dapan_attack3": { zh: "滚刀切！", en: "ROLLING CUT!" },
  "chr_0018_dapan_attack4": { zh: "滚刀切！", en: "ROLLING CUT!" },
  "chr_0018_dapan_combo_skill": { zh: "加料！", en: "MORE SPICE!" },
  "chr_0018_dapan_comboskill": { zh: "加料！", en: "MORE SPICE!" },
  "chr_0018_dapan_normal_attack": { zh: "滚刀切！", en: "ROLLING CUT!" },
  "chr_0018_dapan_normal_skill": { zh: "颠勺！", en: "FLIP DA WOK!" },
  "chr_0018_dapan_normalattack": { zh: "滚刀切！", en: "ROLLING CUT!" },
  "chr_0018_dapan_normalskill": { zh: "颠勺！", en: "FLIP DA WOK!" },
  "chr_0018_dapan_plunging_attack_end": { zh: "滚刀切！", en: "ROLLING CUT!" },
  "chr_0018_dapan_power_attack": { zh: "滚刀切！", en: "ROLLING CUT!" },
  "chr_0018_dapan_ultimate_skill": { zh: "切丝入锅！", en: "CHOP 'N DUNK!" },
  "chr_0018_dapan_ultimateskill": { zh: "切丝入锅！", en: "CHOP 'N DUNK!" },
  "chr_0019_karin_attack1": { zh: "进取剑锋", en: "Sword of Aspiration" },
  "chr_0019_karin_attack2": { zh: "进取剑锋", en: "Sword of Aspiration" },
  "chr_0019_karin_attack3": { zh: "进取剑锋", en: "Sword of Aspiration" },
  "chr_0019_karin_attack4": { zh: "进取剑锋", en: "Sword of Aspiration" },
  "chr_0019_karin_combo_skill": { zh: "快闪冲击", en: "Flash and Dash" },
  "chr_0019_karin_comboskill": { zh: "快闪冲击", en: "Flash and Dash" },
  "chr_0019_karin_normal_attack": { zh: "进取剑锋", en: "Sword of Aspiration" },
  "chr_0019_karin_normal_skill": { zh: "热情迸发", en: "Burst of Passion" },
  "chr_0019_karin_normalattack": { zh: "进取剑锋", en: "Sword of Aspiration" },
  "chr_0019_karin_normalskill": { zh: "热情迸发", en: "Burst of Passion" },
  "chr_0019_karin_plunging_attack_end": { zh: "进取剑锋", en: "Sword of Aspiration" },
  "chr_0019_karin_power_attack": { zh: "进取剑锋", en: "Sword of Aspiration" },
  "chr_0019_karin_ultimate_skill": { zh: "小队，集结！", en: "SQUAD! ON ME!" },
  "chr_0019_karin_ultimateskill": { zh: "小队，集结！", en: "SQUAD! ON ME!" },
  "chr_0020_meurs_attack1": { zh: "基础战术", en: "Basic Tactics" },
  "chr_0020_meurs_attack2": { zh: "基础战术", en: "Basic Tactics" },
  "chr_0020_meurs_attack3": { zh: "基础战术", en: "Basic Tactics" },
  "chr_0020_meurs_attack4": { zh: "基础战术", en: "Basic Tactics" },
  "chr_0020_meurs_combo_skill": { zh: "即时压制", en: "Timely Suppression" },
  "chr_0020_meurs_comboskill": { zh: "即时压制", en: "Timely Suppression" },
  "chr_0020_meurs_normal_attack": { zh: "基础战术", en: "Basic Tactics" },
  "chr_0020_meurs_normal_skill": { zh: "刚性阻击", en: "Rigid Interdiction" },
  "chr_0020_meurs_normalattack": { zh: "基础战术", en: "Basic Tactics" },
  "chr_0020_meurs_normalskill": { zh: "刚性阻击", en: "Rigid Interdiction" },
  "chr_0020_meurs_plunging_attack_end": { zh: "基础战术", en: "Basic Tactics" },
  "chr_0020_meurs_power_attack": { zh: "基础战术", en: "Basic Tactics" },
  "chr_0020_meurs_ultimate_skill": { zh: "教科书式猛攻", en: "Textbook Assault" },
  "chr_0020_meurs_ultimateskill": { zh: "教科书式猛攻", en: "Textbook Assault" },
  "chr_0021_whiten_attack1": { zh: "噪点", en: "Audio Noise" },
  "chr_0021_whiten_attack2": { zh: "噪点", en: "Audio Noise" },
  "chr_0021_whiten_attack3": { zh: "噪点", en: "Audio Noise" },
  "chr_0021_whiten_attack4": { zh: "噪点", en: "Audio Noise" },
  "chr_0021_whiten_combo_skill": { zh: "失真", en: "Distortion" },
  "chr_0021_whiten_comboskill": { zh: "失真", en: "Distortion" },
  "chr_0021_whiten_normal_attack": { zh: "噪点", en: "Audio Noise" },
  "chr_0021_whiten_normal_skill": { zh: "凝声", en: "Onomatopoeia" },
  "chr_0021_whiten_normalattack": { zh: "噪点", en: "Audio Noise" },
  "chr_0021_whiten_normalskill": { zh: "凝声", en: "Onomatopoeia" },
  "chr_0021_whiten_plunging_attack_end": { zh: "噪点", en: "Audio Noise" },
  "chr_0021_whiten_power_attack": { zh: "噪点", en: "Audio Noise" },
  "chr_0021_whiten_ultimate_skill": { zh: "震音", en: "Tremolo" },
  "chr_0021_whiten_ultimateskill": { zh: "震音", en: "Tremolo" },
  "chr_0022_bounda_attack1": { zh: "独门射击法", en: "Signature Gun Kata" },
  "chr_0022_bounda_attack2": { zh: "独门射击法", en: "Signature Gun Kata" },
  "chr_0022_bounda_attack3": { zh: "独门射击法", en: "Signature Gun Kata" },
  "chr_0022_bounda_attack4": { zh: "独门射击法", en: "Signature Gun Kata" },
  "chr_0022_bounda_attack4_1": { zh: "独门射击法", en: "Signature Gun Kata" },
  "chr_0022_bounda_combo_skill": { zh: "免费赠礼", en: "Free Giveaway" },
  "chr_0022_bounda_comboskill": { zh: "免费赠礼", en: "Free Giveaway" },
  "chr_0022_bounda_normal_attack": { zh: "独门射击法", en: "Signature Gun Kata" },
  "chr_0022_bounda_normal_skill": { zh: "小惊喜", en: "Tiny Surprise" },
  "chr_0022_bounda_normalattack": { zh: "独门射击法", en: "Signature Gun Kata" },
  "chr_0022_bounda_normalskill": { zh: "小惊喜", en: "Tiny Surprise" },
  "chr_0022_bounda_plunging_attack_end": { zh: "独门射击法", en: "Signature Gun Kata" },
  "chr_0022_bounda_power_attack": { zh: "独门射击法", en: "Signature Gun Kata" },
  "chr_0022_bounda_ultimate_skill": { zh: "巅峰闹剧", en: "Apex Prankster" },
  "chr_0022_bounda_ultimateskill": { zh: "巅峰闹剧", en: "Apex Prankster" },
  "chr_0023_antal_attack1": { zh: "交换电流", en: "Exchange Current" },
  "chr_0023_antal_attack2": { zh: "交换电流", en: "Exchange Current" },
  "chr_0023_antal_attack3": { zh: "交换电流", en: "Exchange Current" },
  "chr_0023_antal_attack4": { zh: "交换电流", en: "Exchange Current" },
  "chr_0023_antal_combo_skill": { zh: "磁暴试验场", en: "EMP Test Site" },
  "chr_0023_antal_comboskill": { zh: "磁暴试验场", en: "EMP Test Site" },
  "chr_0023_antal_normal_attack": { zh: "交换电流", en: "Exchange Current" },
  "chr_0023_antal_normal_skill": { zh: "指定研究对象", en: "Specified Research Subject" },
  "chr_0023_antal_normalattack": { zh: "交换电流", en: "Exchange Current" },
  "chr_0023_antal_normalskill": { zh: "指定研究对象", en: "Specified Research Subject" },
  "chr_0023_antal_plunging_attack_end": { zh: "交换电流", en: "Exchange Current" },
  "chr_0023_antal_power_attack": { zh: "交换电流", en: "Exchange Current" },
  "chr_0023_antal_ultimate_skill": { zh: "超频时刻", en: "Overclocked Moment" },
  "chr_0023_antal_ultimateskill": { zh: "超频时刻", en: "Overclocked Moment" },
  "chr_0024_deepfin_attack1": { zh: "基本挥竿法", en: "Basic Rod Casting" },
  "chr_0024_deepfin_attack2": { zh: "基本挥竿法", en: "Basic Rod Casting" },
  "chr_0024_deepfin_attack3": { zh: "基本挥竿法", en: "Basic Rod Casting" },
  "chr_0024_deepfin_attack4": { zh: "基本挥竿法", en: "Basic Rod Casting" },
  "chr_0024_deepfin_attack5": { zh: "基本挥竿法", en: "Basic Rod Casting" },
  "chr_0024_deepfin_combo_skill": { zh: "凿孔底钓术", en: "Auger Angling" },
  "chr_0024_deepfin_comboskill": { zh: "凿孔底钓术", en: "Auger Angling" },
  "chr_0024_deepfin_normal_attack": { zh: "基本挥竿法", en: "Basic Rod Casting" },
  "chr_0024_deepfin_normal_skill": { zh: "非常规路亚", en: "Unconventional Lure" },
  "chr_0024_deepfin_normalattack": { zh: "基本挥竿法", en: "Basic Rod Casting" },
  "chr_0024_deepfin_normalskill": { zh: "非常规路亚", en: "Unconventional Lure" },
  "chr_0024_deepfin_plunging_attack_end": { zh: "基本挥竿法", en: "Basic Rod Casting" },
  "chr_0024_deepfin_power_attack": { zh: "基本挥竿法", en: "Basic Rod Casting" },
  "chr_0024_deepfin_ultimate_skill": { zh: "大鳞，上钩！", en: "One Monster Catch!" },
  "chr_0024_deepfin_ultimateskill": { zh: "大鳞，上钩！", en: "One Monster Catch!" },
  "chr_0025_ardelia_attack1": { zh: "岩石的轻语", en: "Rocky Whispers" },
  "chr_0025_ardelia_attack2": { zh: "岩石的轻语", en: "Rocky Whispers" },
  "chr_0025_ardelia_attack3": { zh: "岩石的轻语", en: "Rocky Whispers" },
  "chr_0025_ardelia_attack4": { zh: "岩石的轻语", en: "Rocky Whispers" },
  "chr_0025_ardelia_combo_skill": { zh: "火山蘑菇云", en: "Eruption Column" },
  "chr_0025_ardelia_comboskill": { zh: "火山蘑菇云", en: "Eruption Column" },
  "chr_0025_ardelia_normal_attack": { zh: "岩石的轻语", en: "Rocky Whispers" },
  "chr_0025_ardelia_normal_skill": { zh: "奔腾的多利", en: "Dolly Rush" },
  "chr_0025_ardelia_normalattack": { zh: "岩石的轻语", en: "Rocky Whispers" },
  "chr_0025_ardelia_normalskill": { zh: "奔腾的多利", en: "Dolly Rush" },
  "chr_0025_ardelia_plunging_attack_end": { zh: "岩石的轻语", en: "Rocky Whispers" },
  "chr_0025_ardelia_power_attack": { zh: "岩石的轻语", en: "Rocky Whispers" },
  "chr_0025_ardelia_ultimate_skill": { zh: "毛茸茸派对", en: "Wooly Party" },
  "chr_0025_ardelia_ultimateskill": { zh: "毛茸茸派对", en: "Wooly Party" },
  "chr_0026_lastrite_attack1": { zh: "严霜之舞", en: "Dance of Rime" },
  "chr_0026_lastrite_attack2": { zh: "严霜之舞", en: "Dance of Rime" },
  "chr_0026_lastrite_attack3": { zh: "严霜之舞", en: "Dance of Rime" },
  "chr_0026_lastrite_attack4": { zh: "严霜之舞", en: "Dance of Rime" },
  "chr_0026_lastrite_combo_skill": { zh: "噬冬", en: "Winter's Devourer" },
  "chr_0026_lastrite_comboskill": { zh: "噬冬", en: "Winter's Devourer" },
  "chr_0026_lastrite_normal_attack": { zh: "严霜之舞", en: "Dance of Rime" },
  "chr_0026_lastrite_normal_skill": { zh: "塞什卡的秘传", en: "Esoteric Legacy of Se\u0161'qa" },
  "chr_0026_lastrite_normalattack": { zh: "严霜之舞", en: "Dance of Rime" },
  "chr_0026_lastrite_normalskill": { zh: "塞什卡的秘传", en: "Esoteric Legacy of Se\u0161'qa" },
  "chr_0026_lastrite_plunging_attack_end": { zh: "严霜之舞", en: "Dance of Rime" },
  "chr_0026_lastrite_power_attack": { zh: "严霜之舞", en: "Dance of Rime" },
  "chr_0026_lastrite_ultimate_skill": { zh: "临终别礼", en: "Vigil Services" },
  "chr_0026_lastrite_ultimateskill": { zh: "临终别礼", en: "Vigil Services" },
  "chr_0027_tangtang_attack1": { zh: "崩你脑壳！", en: "I'LL BLOW YOUR MIND!" },
  "chr_0027_tangtang_attack2": { zh: "崩你脑壳！", en: "I'LL BLOW YOUR MIND!" },
  "chr_0027_tangtang_attack3": { zh: "崩你脑壳！", en: "I'LL BLOW YOUR MIND!" },
  "chr_0027_tangtang_attack4": { zh: "崩你脑壳！", en: "I'LL BLOW YOUR MIND!" },
  "chr_0027_tangtang_attack5": { zh: "崩你脑壳！", en: "I'LL BLOW YOUR MIND!" },
  "chr_0027_tangtang_combo_skill": { zh: "河水，助我！", en: "RIVER, TO ME!" },
  "chr_0027_tangtang_comboskill": { zh: "河水，助我！", en: "RIVER, TO ME!" },
  "chr_0027_tangtang_normal_attack": { zh: "崩你脑壳！", en: "I'LL BLOW YOUR MIND!" },
  "chr_0027_tangtang_normal_skill": { zh: "踏潮卷浪！", en: "IMA WAVERIDAAH!" },
  "chr_0027_tangtang_normalattack": { zh: "崩你脑壳！", en: "I'LL BLOW YOUR MIND!" },
  "chr_0027_tangtang_normalskill": { zh: "踏潮卷浪！", en: "IMA WAVERIDAAH!" },
  "chr_0027_tangtang_passive_0": { zh: "踏潮卷浪！", en: "IMA WAVERIDAAH!" },
  "chr_0027_tangtang_plunging_attack_end": { zh: "崩你脑壳！", en: "I'LL BLOW YOUR MIND!" },
  "chr_0027_tangtang_power_attack": { zh: "崩你脑壳！", en: "I'LL BLOW YOUR MIND!" },
  "chr_0027_tangtang_ultimate_skill": { zh: "大当家盯着呢！", en: "DA CHIEF SEES YOU!" },
  "chr_0027_tangtang_ultimateskill": { zh: "大当家盯着呢！", en: "DA CHIEF SEES YOU!" },
  "chr_0028_wulfa_attack1": { zh: "沸腾狼血", en: "Seething Wolfblood" },
  "chr_0028_wulfa_attack2": { zh: "沸腾狼血", en: "Seething Wolfblood" },
  "chr_0028_wulfa_attack3": { zh: "沸腾狼血", en: "Seething Wolfblood" },
  "chr_0028_wulfa_attack4": { zh: "沸腾狼血", en: "Seething Wolfblood" },
  "chr_0028_wulfa_attack5": { zh: "沸腾狼血", en: "Seething Wolfblood" },
  "chr_0028_wulfa_combo_2_skill": { zh: "燎影时刻", en: "Moment of Blazing Shadow" },
  "chr_0028_wulfa_combo_3_skill": { zh: "燎影时刻", en: "Moment of Blazing Shadow" },
  "chr_0028_wulfa_combo_skill": { zh: "燎影时刻", en: "Moment of Blazing Shadow" },
  "chr_0028_wulfa_comboskill": { zh: "燎影时刻", en: "Moment of Blazing Shadow" },
  "chr_0028_wulfa_normal_attack": { zh: "沸腾狼血", en: "Seething Wolfblood" },
  "chr_0028_wulfa_normal_skill": { zh: "血红之影", en: "Crimson Shadow" },
  "chr_0028_wulfa_normalattack": { zh: "沸腾狼血", en: "Seething Wolfblood" },
  "chr_0028_wulfa_normalskill": { zh: "血红之影", en: "Crimson Shadow" },
  "chr_0028_wulfa_plunging_attack_end": { zh: "沸腾狼血", en: "Seething Wolfblood" },
  "chr_0028_wulfa_power_attack": { zh: "沸腾狼血", en: "Seething Wolfblood" },
  "chr_0028_wulfa_ultimate_skill": { zh: "“利爪”奇袭", en: "\"Razorclaw\" Ambuscade" },
  "chr_0028_wulfa_ultimateskill": { zh: "“利爪”奇袭", en: "\"Razorclaw\" Ambuscade" },
  "chr_0029_pograni_attack1": { zh: "全面攻势", en: "All-Out Offensive" },
  "chr_0029_pograni_attack2": { zh: "全面攻势", en: "All-Out Offensive" },
  "chr_0029_pograni_attack3": { zh: "全面攻势", en: "All-Out Offensive" },
  "chr_0029_pograni_attack4": { zh: "全面攻势", en: "All-Out Offensive" },
  "chr_0029_pograni_attack5": { zh: "全面攻势", en: "All-Out Offensive" },
  "chr_0029_pograni_combo_skill": { zh: "盈月邀击", en: "Full Moon Slash" },
  "chr_0029_pograni_comboskill": { zh: "盈月邀击", en: "Full Moon Slash" },
  "chr_0029_pograni_normal_attack": { zh: "全面攻势", en: "All-Out Offensive" },
  "chr_0029_pograni_normal_skill": { zh: "粉碎阵线", en: "The Pulverizing Front" },
  "chr_0029_pograni_normalattack": { zh: "全面攻势", en: "All-Out Offensive" },
  "chr_0029_pograni_normalskill": { zh: "粉碎阵线", en: "The Pulverizing Front" },
  "chr_0029_pograni_plunging_attack_end": { zh: "全面攻势", en: "All-Out Offensive" },
  "chr_0029_pograni_power_attack": { zh: "全面攻势", en: "All-Out Offensive" },
  "chr_0029_pograni_ultimate_skill": { zh: "盾卫旗队，上前", en: "Shieldguard Banner, Forward" },
  "chr_0029_pograni_ultimateskill": { zh: "盾卫旗队，上前", en: "Shieldguard Banner, Forward" },
  "chr_0030_zhuangfy_attack1": { zh: "疾电法", en: "Jolting Arts" },
  "chr_0030_zhuangfy_attack1_ult": { zh: "万钧风雷", en: "Smiting Tempest" },
  "chr_0030_zhuangfy_attack2": { zh: "疾电法", en: "Jolting Arts" },
  "chr_0030_zhuangfy_attack2_ult": { zh: "万钧风雷", en: "Smiting Tempest" },
  "chr_0030_zhuangfy_attack3": { zh: "疾电法", en: "Jolting Arts" },
  "chr_0030_zhuangfy_attack3_ult": { zh: "万钧风雷", en: "Smiting Tempest" },
  "chr_0030_zhuangfy_attack4": { zh: "疾电法", en: "Jolting Arts" },
  "chr_0030_zhuangfy_attack5": { zh: "疾电法", en: "Jolting Arts" },
  "chr_0030_zhuangfy_combo_skill": { zh: "一息万变", en: "Breath of Transformation" },
  "chr_0030_zhuangfy_combo_skill_ult": { zh: "一息万变", en: "Breath of Transformation" },
  "chr_0030_zhuangfy_comboskill": { zh: "一息万变", en: "Breath of Transformation" },
  "chr_0030_zhuangfy_normal_attack": { zh: "疾电法", en: "Jolting Arts" },
  "chr_0030_zhuangfy_normal_skill": { zh: "惊霆诀", en: "Mantra of Sundering" },
  "chr_0030_zhuangfy_normal_skill_ult": { zh: "惊霆诀", en: "Mantra of Sundering" },
  "chr_0030_zhuangfy_normalattack": { zh: "疾电法", en: "Jolting Arts" },
  "chr_0030_zhuangfy_normalskill": { zh: "惊霆诀", en: "Mantra of Sundering" },
  "chr_0030_zhuangfy_plunging_attack_end": { zh: "疾电法", en: "Jolting Arts" },
  "chr_0030_zhuangfy_power_attack": { zh: "疾电法", en: "Jolting Arts" },
  "chr_0030_zhuangfy_ultimate_skill": { zh: "万钧风雷", en: "Smiting Tempest" },
  "chr_0030_zhuangfy_ultimateskill": { zh: "万钧风雷", en: "Smiting Tempest" },
  "chr_0031_mifu_attack1": { zh: "剑行拳意", en: "Fistmancer of Blades" },
  "chr_0031_mifu_attack2": { zh: "剑行拳意", en: "Fistmancer of Blades" },
  "chr_0031_mifu_attack3": { zh: "剑行拳意", en: "Fistmancer of Blades" },
  "chr_0031_mifu_attack4": { zh: "剑行拳意", en: "Fistmancer of Blades" },
  "chr_0031_mifu_combo_skill": { zh: "拳出无悔", en: "Fists of No Regrets" },
  "chr_0031_mifu_comboskill": { zh: "拳出无悔", en: "Fists of No Regrets" },
  "chr_0031_mifu_normal_attack": { zh: "剑行拳意", en: "Fistmancer of Blades" },
  "chr_0031_mifu_normal_skill": { zh: "清波三艺", en: "Qingbo Triplex" },
  "chr_0031_mifu_normalattack": { zh: "剑行拳意", en: "Fistmancer of Blades" },
  "chr_0031_mifu_normalskill": { zh: "清波三艺", en: "Qingbo Triplex" },
  "chr_0031_mifu_normalskill_1": { zh: "清波三艺", en: "Qingbo Triplex" },
  "chr_0031_mifu_normalskill_2": { zh: "清波三艺", en: "Qingbo Triplex" },
  "chr_0031_mifu_normalskill_3": { zh: "清波三艺", en: "Qingbo Triplex" },
  "chr_0031_mifu_plunging_attack_end": { zh: "剑行拳意", en: "Fistmancer of Blades" },
  "chr_0031_mifu_powerattack": { zh: "剑行拳意", en: "Fistmancer of Blades" },
  "chr_0031_mifu_ultimate_skill": { zh: "绝心", en: "Pile of No Mercy" },
  "chr_0031_mifu_ultimateskill": { zh: "绝心", en: "Pile of No Mercy" },
  "chr_9000_endmin_combo_skill": { zh: "锁闭序列", en: "Sealing Sequence" },
  "chr_9000_endmin_comboskill": { zh: "锁闭序列", en: "Sealing Sequence" },
  "chr_9000_endmin_normal_attack": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_9000_endmin_normal_skill": { zh: "构成序列", en: "Constructive Sequence" },
  "chr_9000_endmin_normalattack": { zh: "毁伤序列", en: "Destructive Sequence" },
  "chr_9000_endmin_normalskill": { zh: "构成序列", en: "Constructive Sequence" },
  "chr_9000_endmin_ultimate_skill": { zh: "轰击序列", en: "Bombardment Sequence" },
  "chr_9000_endmin_ultimateskill": { zh: "轰击序列", en: "Bombardment Sequence" },
};

export const SKILL_NAME_OVERRIDES: Record<string, { zh: string; en: string }> = {
  "\"razorclaw\" ambuscade": { zh: "“利爪”奇袭", en: "\"Razorclaw\" Ambuscade" },
  "airborne dmg": { zh: "airborne dmg", en: "Airborne DMG" },
  "all-out offensive": { zh: "全面攻势", en: "All-Out Offensive" },
  "apex prankster": { zh: "巅峰闹剧", en: "Apex Prankster" },
  "arcane staff: beam cohesion arts": { zh: "秘杖·束能技艺", en: "Arcane Staff: Beam Cohesion Arts" },
  "arcane staff: gravity field": { zh: "秘杖·重力场", en: "Arcane Staff: Gravity Field" },
  "arcane staff: gravity mode": { zh: "秘杖·引力模式", en: "Arcane Staff: Gravity Mode" },
  "arcane staff: matrix displacement": { zh: "秘杖·矩阵位移", en: "Arcane Staff: Matrix Displacement" },
  "ascending strike": { zh: "归穹宇", en: "Ascending Strike" },
  "aspect of wrath": { zh: "忿怒相", en: "Aspect of Wrath" },
  "audio noise": { zh: "噪点", en: "Audio Noise" },
  "auger angling": { zh: "凿孔底钓术", en: "Auger Angling" },
  "basic attack": { zh: "basic attack", en: "Basic Attack" },
  "basic rod casting": { zh: "基本挥竿法", en: "Basic Rod Casting" },
  "basic tactics": { zh: "基础战术", en: "Basic Tactics" },
  "battle skill": { zh: "battle skill", en: "Battle Skill" },
  "blade gale": { zh: "冽风霜", en: "Blade Gale" },
  "bombardment sequence": { zh: "轰击序列", en: "Bombardment Sequence" },
  "breach": { zh: "breach", en: "Breach" },
  "breath of transformation": { zh: "一息万变", en: "Breath of Transformation" },
  "brr-brr-bomb β": { zh: "冰冰弹·β型", en: "Brr-Brr-Bomb \u03b2" },
  "burst of passion": { zh: "热情迸发", en: "Burst of Passion" },
  "chop 'n dunk!": { zh: "切丝入锅！", en: "CHOP 'N DUNK!" },
  "cleave": { zh: "cleave", en: "Cleave" },
  "combo": { zh: "combo", en: "Combo" },
  "combo skill": { zh: "combo skill", en: "Combo Skill" },
  "constructive sequence": { zh: "构成序列", en: "Constructive Sequence" },
  "cooldown": { zh: "冷却", en: "Cooldown" },
  "crimson shadow": { zh: "血红之影", en: "Crimson Shadow" },
  "crush": { zh: "crush", en: "Crush" },
  "cryoblasting pistolier": { zh: "冷冻射手", en: "Cryoblasting Pistolier" },
  "da chief sees you!": { zh: "大当家盯着呢！", en: "DA CHIEF SEES YOU!" },
  "dance of rime": { zh: "严霜之舞", en: "Dance of Rime" },
  "destructive sequence": { zh: "毁伤序列", en: "Destructive Sequence" },
  "distortion": { zh: "失真", en: "Distortion" },
  "distributed dos": { zh: "分布式拒绝服务", en: "Distributed DoS" },
  "dolly rush": { zh: "奔腾的多利", en: "Dolly Rush" },
  "emp test site": { zh: "磁暴试验场", en: "EMP Test Site" },
  "eruption column": { zh: "火山蘑菇云", en: "Eruption Column" },
  "esoteric legacy of seš'qa": { zh: "塞什卡的秘传", en: "Esoteric Legacy of Se\u0161'qa" },
  "exchange current": { zh: "交换电流", en: "Exchange Current" },
  "execution": { zh: "execution", en: "Execution" },
  "exploding blitz": { zh: "轰雷掣电", en: "Exploding Blitz" },
  "exuberant trigger": { zh: "雀跃扳机", en: "Exuberant Trigger" },
  "fistmancer of blades": { zh: "剑行拳意", en: "Fistmancer of Blades" },
  "fists of no regrets": { zh: "拳出无悔", en: "Fists of No Regrets" },
  "flaming cinders": { zh: "燃烬", en: "Flaming Cinders" },
  "flash and dash": { zh: "快闪冲击", en: "Flash and Dash" },
  "flashfreezer υ37": { zh: "速冻仔·υ37", en: "Flashfreezer \u03c537" },
  "flip da wok!": { zh: "颠勺！", en: "FLIP DA WOK!" },
  "forward march": { zh: "forward march", en: "Forward March" },
  "frag grenade·β": { zh: "爆裂手雷·β型", en: "Frag Grenade\u00b7\u03b2" },
  "free giveaway": { zh: "免费赠礼", en: "Free Giveaway" },
  "frigid snowfield": { zh: "凛冽寒霜", en: "Frigid Snowfield" },
  "frontline support": { zh: "frontline support", en: "Frontline Support" },
  "full moon slash": { zh: "盈月邀击", en: "Full Moon Slash" },
  "heart of the unmoving": { zh: "不动心", en: "Heart of the Unmoving" },
  "heavy attack": { zh: "heavy attack", en: "Heavy Attack" },
  "hypothermic assault": { zh: "失温猛击", en: "Hypothermic Assault" },
  "i'll blow your mind!": { zh: "崩你脑壳！", en: "I'LL BLOW YOUR MIND!" },
  "ima waveridaah!": { zh: "踏潮卷浪！", en: "IMA WAVERIDAAH!" },
  "instant protocol: chain": { zh: "即时协议·闪链", en: "Instant Protocol: Chain" },
  "jolting arts": { zh: "疾电法", en: "Jolting Arts" },
  "knock down": { zh: "knock down", en: "Knock Down" },
  "mantra of sundering": { zh: "惊霆诀", en: "Mantra of Sundering" },
  "moment of blazing shadow": { zh: "燎影时刻", en: "Moment of Blazing Shadow" },
  "more spice!": { zh: "加料！", en: "MORE SPICE!" },
  "one monster catch!": { zh: "大鳞，上钩！", en: "One Monster Catch!" },
  "onomatopoeia": { zh: "凝声", en: "Onomatopoeia" },
  "overclocked moment": { zh: "超频时刻", en: "Overclocked Moment" },
  "peal of thunder": { zh: "鸣雷", en: "Peal of Thunder" },
  "physical airborne dmg": { zh: "physical airborne dmg", en: "Physical Airborne DMG" },
  "pile of no mercy": { zh: "绝心", en: "Pile of No Mercy" },
  "polar rescue": { zh: "极地救援", en: "Polar Rescue" },
  "protocol α: breach": { zh: "协议α·突破", en: "Protocol \u03b1: Breach" },
  "protocol ε: 70.41k": { zh: "协议ε·70.41κ", en: "Protocol \u03b5: 70.41K" },
  "protocol ω: strike": { zh: "协议ω·雷击", en: "Protocol \u03c9: Strike" },
  "qingbo triplex": { zh: "清波三艺", en: "Qingbo Triplex" },
  "rapid fire akimbo": { zh: "多重连射", en: "Rapid Fire Akimbo" },
  "re-ignited oath": { zh: "re-ignited oath", en: "Re-Ignited Oath" },
  "rigid interdiction": { zh: "刚性阻击", en: "Rigid Interdiction" },
  "river, to me!": { zh: "河水，助我！", en: "RIVER, TO ME!" },
  "rocky whispers": { zh: "岩石的轻语", en: "Rocky Whispers" },
  "rolling cut!": { zh: "滚刀切！", en: "ROLLING CUT!" },
  "ruination": { zh: "摧破", en: "Ruination" },
  "saturated defense": { zh: "饱和性防御", en: "Saturated Defense" },
  "sealing sequence": { zh: "锁闭序列", en: "Sealing Sequence" },
  "seek and hunt": { zh: "循迹逐猎", en: "Seek and Hunt" },
  "seethe": { zh: "沸腾", en: "Seethe" },
  "seething wolfblood": { zh: "沸腾狼血", en: "Seething Wolfblood" },
  "shieldguard banner, forward": { zh: "盾卫旗队，上前", en: "Shieldguard Banner, Forward" },
  "signature gun kata": { zh: "独门射击法", en: "Signature Gun Kata" },
  "smiting tempest": { zh: "万钧风雷", en: "Smiting Tempest" },
  "smouldering fire": { zh: "焚灭", en: "Smouldering Fire" },
  "soar to the stars": { zh: "见天河", en: "Soar to the Stars" },
  "soaring break": { zh: "破飞霞", en: "Soaring Break" },
  "specified research subject": { zh: "指定研究对象", en: "Specified Research Subject" },
  "squad! on me!": { zh: "小队，集结！", en: "SQUAD! ON ME!" },
  "stack overflow": { zh: "栈溢出", en: "Stack Overflow" },
  "stress testing": { zh: "压力测试", en: "Stress Testing" },
  "sword art of assault": { zh: "sword art of assault", en: "Sword Art of Assault" },
  "sword of aspiration": { zh: "进取剑锋", en: "Sword of Aspiration" },
  "tempestuous arc": { zh: "疾风迅雷", en: "Tempestuous Arc" },
  "textbook assault": { zh: "教科书式猛攻", en: "Textbook Assault" },
  "the pulverizing front": { zh: "粉碎阵线", en: "The Pulverizing Front" },
  "thermite tracers": { zh: "灼热弹痕", en: "Thermite Tracers" },
  "thunderlance: blitz": { zh: "雷枪·疾袭", en: "Thunderlance: Blitz" },
  "thunderlance: final shock": { zh: "雷枪·决颤", en: "Thunderlance: Final Shock" },
  "thunderlance: interdiction": { zh: "雷枪·截回", en: "Thunderlance: Interdiction" },
  "thunderlance: strike": { zh: "雷枪·掣击", en: "Thunderlance: Strike" },
  "timely suppression": { zh: "即时压制", en: "Timely Suppression" },
  "tiny surprise": { zh: "小惊喜", en: "Tiny Surprise" },
  "tremolo": { zh: "震音", en: "Tremolo" },
  "turbid avatar": { zh: "荡浊身", en: "Turbid Avatar" },
  "twilight": { zh: "黄昏", en: "Twilight" },
  "ultimate": { zh: "ultimate", en: "Ultimate" },
  "unconventional lure": { zh: "非常规路亚", en: "Unconventional Lure" },
  "vigil services": { zh: "临终别礼", en: "Vigil Services" },
  "winter's devourer": { zh: "噬冬", en: "Winter's Devourer" },
  "wolven fury": { zh: "狼之怒", en: "Wolven Fury" },
  "wooly party": { zh: "毛茸茸派对", en: "Wooly Party" },
  "“利爪”奇袭": { zh: "“利爪”奇袭", en: "\"Razorclaw\" Ambuscade" },
  "一息万变": { zh: "一息万变", en: "Breath of Transformation" },
  "万钧风雷": { zh: "万钧风雷", en: "Smiting Tempest" },
  "不动心": { zh: "不动心", en: "Heart of the Unmoving" },
  "严霜之舞": { zh: "严霜之舞", en: "Dance of Rime" },
  "临终别礼": { zh: "临终别礼", en: "Vigil Services" },
  "交换电流": { zh: "交换电流", en: "Exchange Current" },
  "倒地": { zh: "倒地", en: "Knock Down" },
  "免费赠礼": { zh: "免费赠礼", en: "Free Giveaway" },
  "全面攻势": { zh: "全面攻势", en: "All-Out Offensive" },
  "冰冰弹·β型": { zh: "冰冰弹·β型", en: "Brr-Brr-Bomb \u03b2" },
  "冷冻射手": { zh: "冷冻射手", en: "Cryoblasting Pistolier" },
  "冷却": { zh: "冷却", en: "Cooldown" },
  "冽风霜": { zh: "冽风霜", en: "Blade Gale" },
  "凛冽寒霜": { zh: "凛冽寒霜", en: "Frigid Snowfield" },
  "凝声": { zh: "凝声", en: "Onomatopoeia" },
  "凿孔底钓术": { zh: "凿孔底钓术", en: "Auger Angling" },
  "分布式拒绝服务": { zh: "分布式拒绝服务", en: "Distributed DoS" },
  "切丝入锅！": { zh: "切丝入锅！", en: "CHOP 'N DUNK!" },
  "刚性阻击": { zh: "刚性阻击", en: "Rigid Interdiction" },
  "前线援护": { zh: "前线援护", en: "Frontline Support" },
  "前线支援": { zh: "前线支援", en: "Frontline Support" },
  "剑行拳意": { zh: "剑行拳意", en: "Fistmancer of Blades" },
  "加料！": { zh: "加料！", en: "MORE SPICE!" },
  "协议α·突破": { zh: "协议α·突破", en: "Protocol \u03b1: Breach" },
  "协议ε·70.41κ": { zh: "协议ε·70.41κ", en: "Protocol \u03b5: 70.41K" },
  "协议ω·雷击": { zh: "协议ω·雷击", en: "Protocol \u03c9: Strike" },
  "即时协议·闪链": { zh: "即时协议·闪链", en: "Instant Protocol: Chain" },
  "即时压制": { zh: "即时压制", en: "Timely Suppression" },
  "压力测试": { zh: "压力测试", en: "Stress Testing" },
  "噪点": { zh: "噪点", en: "Audio Noise" },
  "噬冬": { zh: "噬冬", en: "Winter's Devourer" },
  "基本挥竿法": { zh: "基本挥竿法", en: "Basic Rod Casting" },
  "基础战术": { zh: "基础战术", en: "Basic Tactics" },
  "塞什卡的秘传": { zh: "塞什卡的秘传", en: "Esoteric Legacy of Se\u0161'qa" },
  "处决": { zh: "处决", en: "Execution" },
  "多重连射": { zh: "多重连射", en: "Rapid Fire Akimbo" },
  "大当家盯着呢！": { zh: "大当家盯着呢！", en: "DA CHIEF SEES YOU!" },
  "大招": { zh: "大招", en: "Ultimate" },
  "大鳞，上钩！": { zh: "大鳞，上钩！", en: "One Monster Catch!" },
  "失温猛击": { zh: "失温猛击", en: "Hypothermic Assault" },
  "失真": { zh: "失真", en: "Distortion" },
  "奔腾的多利": { zh: "奔腾的多利", en: "Dolly Rush" },
  "小惊喜": { zh: "小惊喜", en: "Tiny Surprise" },
  "小队，集结！": { zh: "小队，集结！", en: "SQUAD! ON ME!" },
  "岩石的轻语": { zh: "岩石的轻语", en: "Rocky Whispers" },
  "崩你脑壳！": { zh: "崩你脑壳！", en: "I'LL BLOW YOUR MIND!" },
  "巅峰闹剧": { zh: "巅峰闹剧", en: "Apex Prankster" },
  "归穹宇": { zh: "归穹宇", en: "Ascending Strike" },
  "循迹逐猎": { zh: "循迹逐猎", en: "Seek and Hunt" },
  "快闪冲击": { zh: "快闪冲击", en: "Flash and Dash" },
  "忿怒相": { zh: "忿怒相", en: "Aspect of Wrath" },
  "惊霆诀": { zh: "惊霆诀", en: "Mantra of Sundering" },
  "战技": { zh: "战技", en: "Battle Skill" },
  "战术技能": { zh: "战术技能", en: "Battle Skill" },
  "拳出无悔": { zh: "拳出无悔", en: "Fists of No Regrets" },
  "指定研究对象": { zh: "指定研究对象", en: "Specified Research Subject" },
  "摧破": { zh: "摧破", en: "Ruination" },
  "教科书式猛攻": { zh: "教科书式猛攻", en: "Textbook Assault" },
  "斫": { zh: "斫", en: "Cleave" },
  "普攻": { zh: "普攻", en: "Basic Attack" },
  "普通攻击": { zh: "普通攻击", en: "Basic Attack" },
  "极地救援": { zh: "极地救援", en: "Polar Rescue" },
  "构成序列": { zh: "构成序列", en: "Constructive Sequence" },
  "栈溢出": { zh: "栈溢出", en: "Stack Overflow" },
  "毁伤序列": { zh: "毁伤序列", en: "Destructive Sequence" },
  "毛茸茸派对": { zh: "毛茸茸派对", en: "Wooly Party" },
  "河水，助我！": { zh: "河水，助我！", en: "RIVER, TO ME!" },
  "沸腾": { zh: "沸腾", en: "Seethe" },
  "沸腾狼血": { zh: "沸腾狼血", en: "Seething Wolfblood" },
  "浮空伤害": { zh: "浮空伤害", en: "Airborne DMG" },
  "清波三艺": { zh: "清波三艺", en: "Qingbo Triplex" },
  "滚刀切！": { zh: "滚刀切！", en: "ROLLING CUT!" },
  "火山蘑菇云": { zh: "火山蘑菇云", en: "Eruption Column" },
  "灼热弹痕": { zh: "灼热弹痕", en: "Thermite Tracers" },
  "热情迸发": { zh: "热情迸发", en: "Burst of Passion" },
  "焚灭": { zh: "焚灭", en: "Smouldering Fire" },
  "燃烬": { zh: "燃烬", en: "Flaming Cinders" },
  "燃约": { zh: "燃约", en: "Re-Ignited Oath" },
  "燎影时刻": { zh: "燎影时刻", en: "Moment of Blazing Shadow" },
  "爆裂手雷·β型": { zh: "爆裂手雷·β型", en: "Frag Grenade\u00b7\u03b2" },
  "物理浮空伤害": { zh: "物理浮空伤害", en: "Physical Airborne DMG" },
  "独门射击法": { zh: "独门射击法", en: "Signature Gun Kata" },
  "狼之怒": { zh: "狼之怒", en: "Wolven Fury" },
  "猛击": { zh: "猛击", en: "Crush" },
  "疾电法": { zh: "疾电法", en: "Jolting Arts" },
  "疾风迅雷": { zh: "疾风迅雷", en: "Tempestuous Arc" },
  "盈月邀击": { zh: "盈月邀击", en: "Full Moon Slash" },
  "盾卫旗队，上前": { zh: "盾卫旗队，上前", en: "Shieldguard Banner, Forward" },
  "破防": { zh: "破防", en: "Breach" },
  "破飞霞": { zh: "破飞霞", en: "Soaring Break" },
  "磁暴试验场": { zh: "磁暴试验场", en: "EMP Test Site" },
  "秘杖·引力模式": { zh: "秘杖·引力模式", en: "Arcane Staff: Gravity Mode" },
  "秘杖·束能技艺": { zh: "秘杖·束能技艺", en: "Arcane Staff: Beam Cohesion Arts" },
  "秘杖·矩阵位移": { zh: "秘杖·矩阵位移", en: "Arcane Staff: Matrix Displacement" },
  "秘杖·重力场": { zh: "秘杖·重力场", en: "Arcane Staff: Gravity Field" },
  "粉碎阵线": { zh: "粉碎阵线", en: "The Pulverizing Front" },
  "终结技": { zh: "终结技", en: "Ultimate" },
  "绝心": { zh: "绝心", en: "Pile of No Mercy" },
  "荡浊身": { zh: "荡浊身", en: "Turbid Avatar" },
  "血红之影": { zh: "血红之影", en: "Crimson Shadow" },
  "见天河": { zh: "见天河", en: "Soar to the Stars" },
  "超频时刻": { zh: "超频时刻", en: "Overclocked Moment" },
  "踏潮卷浪！": { zh: "踏潮卷浪！", en: "IMA WAVERIDAAH!" },
  "轰击序列": { zh: "轰击序列", en: "Bombardment Sequence" },
  "轰雷掣电": { zh: "轰雷掣电", en: "Exploding Blitz" },
  "进军": { zh: "进军", en: "Forward March" },
  "进取剑锋": { zh: "进取剑锋", en: "Sword of Aspiration" },
  "连携": { zh: "连携", en: "Combo" },
  "连携技": { zh: "连携技", en: "Combo Skill" },
  "速冻仔·υ37": { zh: "速冻仔·υ37", en: "Flashfreezer \u03c537" },
  "重击": { zh: "重击", en: "Heavy Attack" },
  "重燃誓约": { zh: "重燃誓约", en: "Re-Ignited Oath" },
  "锁闭序列": { zh: "锁闭序列", en: "Sealing Sequence" },
  "陷阵剑术": { zh: "陷阵剑术", en: "Sword Art of Assault" },
  "雀跃扳机": { zh: "雀跃扳机", en: "Exuberant Trigger" },
  "雷枪·决颤": { zh: "雷枪·决颤", en: "Thunderlance: Final Shock" },
  "雷枪·截回": { zh: "雷枪·截回", en: "Thunderlance: Interdiction" },
  "雷枪·掣击": { zh: "雷枪·掣击", en: "Thunderlance: Strike" },
  "雷枪·疾袭": { zh: "雷枪·疾袭", en: "Thunderlance: Blitz" },
  "震音": { zh: "震音", en: "Tremolo" },
  "非常规路亚": { zh: "非常规路亚", en: "Unconventional Lure" },
  "颠勺！": { zh: "颠勺！", en: "FLIP DA WOK!" },
  "饱和性防御": { zh: "饱和性防御", en: "Saturated Defense" },
  "鸣雷": { zh: "鸣雷", en: "Peal of Thunder" },
  "黄昏": { zh: "黄昏", en: "Twilight" },
};

export type BattleSkillCategory = "normal" | "skill" | "combo" | "heavy" | "ultimate" | "other";

export function getPreferredBattleSkillDisplayName(
  skillName: string,
  skillKey?: string | null,
  locale: Locale = "en",
): string {
  if (skillKey) {
    const skillKeyOverride = SKILL_KEY_OVERRIDES[skillKey.toLowerCase()];
    if (skillKeyOverride) {
      return locale === "zh" ? skillKeyOverride.zh : skillKeyOverride.en;
    }
  }
  const trimmed = skillName.trim();
  const skillNameOverride = SKILL_NAME_OVERRIDES[trimmed.toLowerCase()];
  if (skillNameOverride) {
    return locale === "zh" ? skillNameOverride.zh : skillNameOverride.en;
  }
  if (skillKey && COMBO_SKILL_KEY_RE.test(skillKey)) {
    return locale === "zh" ? "连携技" : "Combo Skill";
  }

  // Pattern-based translations
  if (locale === "en") {
    // e.g. "物理浮空伤害" -> "Physical Airborne DMG"
    const airborneMatch = trimmed.match(/^(.+?)浮空伤害$/);
    if (airborneMatch) {
      const elem = ELEMENT_ZH_TO_EN[airborneMatch[1]] || airborneMatch[1];
      return `${elem} Airborne DMG`;
    }

    // e.g. "灼热爆发" -> "Heat Burst"
    const burstMatch = trimmed.match(/^(.+?)爆发$/);
    if (burstMatch) {
      const elem = ELEMENT_ZH_TO_EN[burstMatch[1]] || burstMatch[1];
      return `${elem} Burst`;
    }

    // e.g. "灼热·电磁触发" -> "Heat · Pulse Trigger"
    const triggerMatch = trimmed.match(/^(.+?)[·・](.+?)触发$/);
    if (triggerMatch) {
      const elem1 = ELEMENT_ZH_TO_EN[triggerMatch[1]] || triggerMatch[1];
      const elem2 = ELEMENT_ZH_TO_EN[triggerMatch[2]] || triggerMatch[2];
      return `${elem1} · ${elem2} Trigger`;
    }

    // e.g. "敌方法术灼热触发" -> "Enemy Arts Heat Trigger"
    const enemyArtsMatch = trimmed.match(/^敌方法术(.+?)触发$/);
    if (enemyArtsMatch) {
      const elem = ELEMENT_ZH_TO_EN[enemyArtsMatch[1]] || enemyArtsMatch[1];
      return `Enemy Arts ${elem} Trigger`;
    }

    if (trimmed === "战技") return "Battle Skill";
    if (trimmed === "连携" || trimmed === "连携技") return "Combo";
    if (trimmed === "终结技" || trimmed === "大招") return "Ultimate";
    if (trimmed === "普攻") return "Basic Attack";
    if (trimmed === "重击" || trimmed === "处决") return "Heavy Attack";
  } else {
    // locale === "zh"
    const airborneEnMatch = trimmed.match(/^(.+?)\s+Airborne\s+DMG$/i);
    if (airborneEnMatch) {
      const elem = ELEMENT_EN_TO_ZH[airborneEnMatch[1]] || airborneEnMatch[1];
      return `${elem}浮空伤害`;
    }

    const burstEnMatch = trimmed.match(/^(.+?)\s+Burst$/i);
    if (burstEnMatch) {
      const elem = ELEMENT_EN_TO_ZH[burstEnMatch[1]] || burstEnMatch[1];
      return `${elem}爆发`;
    }

    if (trimmed === "Battle Skill" || trimmed === "BS") return "战技";
    if (trimmed === "Combo" || trimmed === "Combo Skill") return "连携";
    if (trimmed === "Ultimate" || trimmed === "ULT") return "大招";
    if (trimmed === "Basic Attack" || trimmed === "Normal Attack" || trimmed === "BA") return "普攻";
    if (trimmed === "Heavy Attack" || trimmed === "Finisher" || trimmed === "Execution") return "重击";
  }

  return trimmed;
}

export function getBattleSkillCategory(skillName: string, skillKey?: string | null): BattleSkillCategory {
  const displayName = getPreferredBattleSkillDisplayName(skillName, skillKey, "zh").trim();
  if (/^A[1-4]$/i.test(displayName) || /^(Basic Attack|Normal Attack|普攻|BA)/i.test(displayName)) {
    return "normal";
  }
  if (displayName === "战技" || displayName === "Battle Skill" || displayName === "BS") {
    return "skill";
  }
  if (displayName === "连携技" || displayName === "连携" || displayName === "Combo Skill" || displayName === "Combo") {
    return "combo";
  }
  if (
    displayName === "重击" ||
    displayName === "处决" ||
    displayName === "Heavy Attack" ||
    displayName === "Finisher" ||
    displayName === "Execution" ||
    displayName === "Hvy"
  ) {
    return "heavy";
  }
  if (displayName === "终结技" || displayName === "大招" || displayName === "Ultimate" || displayName === "ULT") {
    return "ultimate";
  }
  if (!skillKey) {
    return "other";
  }

  const lowered = skillKey.toLowerCase();
  if (lowered.includes("_ult_attack") || lowered.includes("_ultimate_skill")) {
    return "ultimate";
  }
  if (COMBO_SKILL_KEY_RE.test(lowered)) {
    return "combo";
  }
  if (lowered.includes("_normal_skill")) {
    return "skill";
  }
  if (lowered.includes("execute") || lowered.includes("execution")) {
    return "heavy";
  }
  if (lowered.includes("power_attack") || lowered.includes("plunging_attack") || lowered.includes("heavy_attack")) {
    return "heavy";
  }

  const attackMatch = ATTACK_INDEX_RE.exec(lowered);
  if (attackMatch) {
    return "normal";
  }

  return "other";
}

export function getBattleSkillCategoryLabel(
  skillName: string,
  skillKey?: string | null,
  locale: Locale = "en",
): string {
  const category = getBattleSkillCategory(skillName, skillKey);
  return SKILL_CATEGORY_LABELS[locale][category] || SKILL_CATEGORY_LABELS[locale].other;
}

