version: 2
updates:
  - package-ecosystem: npm
    directory: /endfield-logs
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: pip
    directory: /endfield-logs/apps/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: pip
    directory: /endfield-logs/apps/uploader
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: pip
    directory: /endfield-pcap
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

