# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ACTIVITY_CONDITIONAL_STAGE_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ACTIVITY_CONDITIONAL_STAGE_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCD_ACTIVITY_CONDITIONS_pb2 as SCD__ACTIVITY__CONDITIONS__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%ACTIVITY_CONDITIONAL_STAGE_INFO.proto\x1a\x1dSCD_ACTIVITY_CONDITIONS.proto\"k\n\x1f\x41\x43TIVITY_CONDITIONAL_STAGE_INFO\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12,\n\nconditions\x18\x03 \x01(\x0b\x32\x18.SCD_ACTIVITY_CONDITIONSb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ACTIVITY_CONDITIONAL_STAGE_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIVITY_CONDITIONAL_STAGE_INFO']._serialized_start=72
  _globals['_ACTIVITY_CONDITIONAL_STAGE_INFO']._serialized_end=179
# @@protoc_insertion_point(module_scope)

