# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ATK_SCALE_CALCULATION_RUNTIME_ARGS.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ATK_SCALE_CALCULATION_RUNTIME_ARGS.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(ATK_SCALE_CALCULATION_RUNTIME_ARGS.proto\"X\n\"ATK_SCALE_CALCULATION_RUNTIME_ARGS\x12\x18\n\x10\x63lient_atk_scale\x18\x01 \x01(\x01\x12\x18\n\x10\x63lient_atk_value\x18\x02 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ATK_SCALE_CALCULATION_RUNTIME_ARGS_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATK_SCALE_CALCULATION_RUNTIME_ARGS']._serialized_start=44
  _globals['_ATK_SCALE_CALCULATION_RUNTIME_ARGS']._serialized_end=132
# @@protoc_insertion_point(module_scope)

