# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ATTR_MODIFY_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ATTR_MODIFY_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x41TTR_MODIFY_DATA.proto\"\xee\x01\n\x10\x41TTR_MODIFY_DATA\x12\x14\n\x0cmodify_value\x18\x01 \x01(\x01\x12\x14\n\x0cmodify_ratio\x18\x02 \x01(\x01\x12\x1a\n\x12\x66inal_modify_value\x18\x03 \x01(\x01\x12\x1a\n\x12\x66inal_modify_ratio\x18\x04 \x01(\x01\x12\x19\n\x11\x62\x61se_modify_value\x18\x05 \x01(\x01\x12\x19\n\x11\x62\x61se_modify_ratio\x18\x06 \x01(\x01\x12\x1f\n\x17\x62\x61se_final_modify_value\x18\x07 \x01(\x01\x12\x1f\n\x17\x62\x61se_final_modify_ratio\x18\x08 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ATTR_MODIFY_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATTR_MODIFY_DATA']._serialized_start=27
  _globals['_ATTR_MODIFY_DATA']._serialized_end=265
# @@protoc_insertion_point(module_scope)

