# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_REPORT_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_REPORT_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ATTR_MODIFY_INFO_pb2 as ATTR__MODIFY__INFO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x42\x41TTLE_REPORT_INFO.proto\x1a\x16\x41TTR_MODIFY_INFO.proto\"\x80\x01\n\x12\x42\x41TTLE_REPORT_INFO\x12\x34\n\x19\x61ttacker_attr_modify_info\x18\x01 \x03(\x0b\x32\x11.ATTR_MODIFY_INFO\x12\x34\n\x19\x64\x65\x66\x65nder_attr_modify_info\x18\x02 \x03(\x0b\x32\x11.ATTR_MODIFY_INFOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_REPORT_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_REPORT_INFO']._serialized_start=53
  _globals['_BATTLE_REPORT_INFO']._serialized_end=181
# @@protoc_insertion_point(module_scope)

