# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_SWITCH_MODE_OP_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_SWITCH_MODE_OP_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n BATTLE_SWITCH_MODE_OP_DATA.proto\"p\n\x1a\x42\x41TTLE_SWITCH_MODE_OP_DATA\x12\x14\n\x0cmode_inst_id\x18\x01 \x01(\r\x12\x0f\n\x07mode_id\x18\x02 \x01(\t\x12\x18\n\x10mode_change_type\x18\x03 \x01(\x05\x12\x11\n\tis_enable\x18\x04 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_SWITCH_MODE_OP_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_SWITCH_MODE_OP_DATA']._serialized_start=36
  _globals['_BATTLE_SWITCH_MODE_OP_DATA']._serialized_end=148
# @@protoc_insertion_point(module_scope)

