# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_SKILL_START_CAST_OP_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_SKILL_START_CAST_OP_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_ATB_DATA_pb2 as BATTLE__ATB__DATA__pb2
import BATTLE_TARGET_HANDLE_pb2 as BATTLE__TARGET__HANDLE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%BATTLE_SKILL_START_CAST_OP_DATA.proto\x1a\x15\x42\x41TTLE_ATB_DATA.proto\x1a\x1a\x42\x41TTLE_TARGET_HANDLE.proto\"}\n\x1f\x42\x41TTLE_SKILL_START_CAST_OP_DATA\x12\x0f\n\x07inst_id\x18\x01 \x01(\x04\x12%\n\x06target\x18\x02 \x01(\x0b\x32\x15.BATTLE_TARGET_HANDLE\x12\"\n\x08\x61tb_data\x18\x03 \x01(\x0b\x32\x10.BATTLE_ATB_DATAb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_SKILL_START_CAST_OP_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_SKILL_START_CAST_OP_DATA']._serialized_start=92
  _globals['_BATTLE_SKILL_START_CAST_OP_DATA']._serialized_end=217
# @@protoc_insertion_point(module_scope)

