# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_MODIFY_ENABLE_PART_ACTION_RUNTIME.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_MODIFY_ENABLE_PART_ACTION_RUNTIME.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.BATTLE_MODIFY_ENABLE_PART_ACTION_RUNTIME.proto\"\xd7\x01\n(BATTLE_MODIFY_ENABLE_PART_ACTION_RUNTIME\x12\x19\n\x11main_body_inst_id\x18\x01 \x01(\x04\x12Y\n\x12part_inst_id_to_hp\x18\x02 \x03(\x0b\x32=.BATTLE_MODIFY_ENABLE_PART_ACTION_RUNTIME.PartInstIdToHpEntry\x1a\x35\n\x13PartInstIdToHpEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_MODIFY_ENABLE_PART_ACTION_RUNTIME_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_MODIFY_ENABLE_PART_ACTION_RUNTIME_PARTINSTIDTOHPENTRY']._loaded_options = None
  _globals['_BATTLE_MODIFY_ENABLE_PART_ACTION_RUNTIME_PARTINSTIDTOHPENTRY']._serialized_options = b'8\001'
  _globals['_BATTLE_MODIFY_ENABLE_PART_ACTION_RUNTIME']._serialized_start=51
  _globals['_BATTLE_MODIFY_ENABLE_PART_ACTION_RUNTIME']._serialized_end=266
  _globals['_BATTLE_MODIFY_ENABLE_PART_ACTION_RUNTIME_PARTINSTIDTOHPENTRY']._serialized_start=213
  _globals['_BATTLE_MODIFY_ENABLE_PART_ACTION_RUNTIME_PARTINSTIDTOHPENTRY']._serialized_end=266
# @@protoc_insertion_point(module_scope)

