# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_CREATE_BUFF_ACTION_DETAIL.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_CREATE_BUFF_ACTION_DETAIL.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_BLACKBOARD_ASSIGN_ITEM_pb2 as BATTLE__BLACKBOARD__ASSIGN__ITEM__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&BATTLE_CREATE_BUFF_ACTION_DETAIL.proto\x1a#BATTLE_BLACKBOARD_ASSIGN_ITEM.proto\"\xd6\x01\n BATTLE_CREATE_BUFF_ACTION_DETAIL\x12\x11\n\tsource_id\x18\x01 \x01(\x04\x12\x11\n\ttarget_id\x18\x02 \x01(\x04\x12\x14\n\x0c\x62uff_inst_id\x18\x03 \x01(\x04\x12\x18\n\x10\x62uff_input_index\x18\x04 \x01(\x05\x12\x36\n\x0e\x61ssigned_items\x18\x05 \x03(\x0b\x32\x1e.BATTLE_BLACKBOARD_ASSIGN_ITEM\x12\x13\n\x0b\x62uff_num_id\x18\x06 \x01(\x05\x12\x0f\n\x07\x62uff_id\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_CREATE_BUFF_ACTION_DETAIL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_CREATE_BUFF_ACTION_DETAIL']._serialized_start=80
  _globals['_BATTLE_CREATE_BUFF_ACTION_DETAIL']._serialized_end=294
# @@protoc_insertion_point(module_scope)

