# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_DAMAGE_SCALE_pb2 as BATTLE__CLIENT__PROCESSOR__DEBUG__ARGS__ITEM__DAMAGE__SCALE__pb2
import BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_HEAL_INSTANT_MODIFY_ATTRIBUTE_pb2 as BATTLE__CLIENT__PROCESSOR__DEBUG__ARGS__ITEM__HEAL__INSTANT__MODIFY__ATTRIBUTE__pb2
import BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_HEAL_MODIFY_RESULT_pb2 as BATTLE__CLIENT__PROCESSOR__DEBUG__ARGS__ITEM__HEAL__MODIFY__RESULT__pb2
import BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_INSTANT_MODIFY_ATTRIBUTE_pb2 as BATTLE__CLIENT__PROCESSOR__DEBUG__ARGS__ITEM__INSTANT__MODIFY__ATTRIBUTE__pb2
import BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_MODIFY_CALCULATE_RESULT_pb2 as BATTLE__CLIENT__PROCESSOR__DEBUG__ARGS__ITEM__MODIFY__CALCULATE__RESULT__pb2
import EMPTY_BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_pb2 as EMPTY__BATTLE__CLIENT__PROCESSOR__DEBUG__ARGS__ITEM__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM.proto\x1a:BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_DAMAGE_SCALE.proto\x1aKBATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_HEAL_INSTANT_MODIFY_ATTRIBUTE.proto\x1a@BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_HEAL_MODIFY_RESULT.proto\x1a\x46\x42\x41TTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_INSTANT_MODIFY_ATTRIBUTE.proto\x1a\x45\x42\x41TTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_MODIFY_CALCULATE_RESULT.proto\x1a\x33\x45MPTY_BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM.proto\"\xbf\x05\n\'BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM\x12N\n\x14\x65mpty_processor_args\x18\x64 \x01(\x0b\x32..EMPTY_BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEMH\x00\x12r\n&modify_calculate_result_processor_args\x18\x65 \x01(\x0b\x32@.BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_MODIFY_CALCULATE_RESULTH\x00\x12t\n\'instant_modify_attribute_processor_args\x18\x66 \x01(\x0b\x32\x41.BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_INSTANT_MODIFY_ATTRIBUTEH\x00\x12\\\n\x1b\x64\x61mage_scale_processor_args\x18g \x01(\x0b\x32\x35.BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_DAMAGE_SCALEH\x00\x12i\n!heal_modify_result_processor_args\x18\xc9\x01 \x01(\x0b\x32;.BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_HEAL_MODIFY_RESULTH\x00\x12\x7f\n,heal_instant_modify_attribute_processor_args\x18\xca\x01 \x01(\x0b\x32\x46.BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_HEAL_INSTANT_MODIFY_ATTRIBUTEH\x00\x42\x10\n\x0eprocessor_argsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM']._serialized_start=449
  _globals['_BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM']._serialized_end=1152
# @@protoc_insertion_point(module_scope)

