# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_TRIGGER_KEYWORD_OP_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_TRIGGER_KEYWORD_OP_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_TRIGGER_KEYWORD_MODIFY_DATA_pb2 as BATTLE__TRIGGER__KEYWORD__MODIFY__DATA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$BATTLE_TRIGGER_KEYWORD_OP_DATA.proto\x1a(BATTLE_TRIGGER_KEYWORD_MODIFY_DATA.proto\"\x84\x01\n\x1e\x42\x41TTLE_TRIGGER_KEYWORD_OP_DATA\x12\x14\n\x0c\x62uff_inst_id\x18\x01 \x01(\x04\x12\x17\n\x0f\x61\x64\x64_buff_num_id\x18\x02 \x01(\x05\x12\x33\n\x06modify\x18\x03 \x03(\x0b\x32#.BATTLE_TRIGGER_KEYWORD_MODIFY_DATAb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_TRIGGER_KEYWORD_OP_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_TRIGGER_KEYWORD_OP_DATA']._serialized_start=83
  _globals['_BATTLE_TRIGGER_KEYWORD_OP_DATA']._serialized_end=215
# @@protoc_insertion_point(module_scope)

