# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_DAMAGE_DETAIL.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_DAMAGE_DETAIL.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_pb2 as BATTLE__CLIENT__PROCESSOR__DEBUG__ARGS__ITEM__pb2
import BATTLE_DAMAGE_MODIFIER_ARGS_pb2 as BATTLE__DAMAGE__MODIFIER__ARGS__pb2
import BATTLE_REPORT_INFO_pb2 as BATTLE__REPORT__INFO__pb2
import CLIENT_ATTR_MODIFIER_DEBUG_DATA_pb2 as CLIENT__ATTR__MODIFIER__DEBUG__DATA__pb2
import DAMAGE_ABSORB_INFO_pb2 as DAMAGE__ABSORB__INFO__pb2
import DEV_BATTLE_CALCULATE_DAMAGE_RUNTIME_ARGS_pb2 as DEV__BATTLE__CALCULATE__DAMAGE__RUNTIME__ARGS__pb2
import DEV_BATTLE_CALCULATION_RUNTIME_ARGS_pb2 as DEV__BATTLE__CALCULATION__RUNTIME__ARGS__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x42\x41TTLE_DAMAGE_DETAIL.proto\x1a-BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM.proto\x1a!BATTLE_DAMAGE_MODIFIER_ARGS.proto\x1a\x18\x42\x41TTLE_REPORT_INFO.proto\x1a%CLIENT_ATTR_MODIFIER_DEBUG_DATA.proto\x1a\x18\x44\x41MAGE_ABSORB_INFO.proto\x1a.DEV_BATTLE_CALCULATE_DAMAGE_RUNTIME_ARGS.proto\x1a)DEV_BATTLE_CALCULATION_RUNTIME_ARGS.proto\"\x83\x06\n\x14\x42\x41TTLE_DAMAGE_DETAIL\x12\x11\n\ttarget_id\x18\x01 \x01(\x04\x12\x19\n\x11\x64\x61mage_unit_index\x18\x02 \x01(\x05\x12\x0f\n\x07is_crit\x18\x03 \x01(\x08\x12\r\n\x05value\x18\x04 \x01(\x01\x12\x33\n\rmodifier_args\x18\x05 \x01(\x0b\x32\x1c.BATTLE_DAMAGE_MODIFIER_ARGS\x12\x0e\n\x06\x63ur_hp\x18\x06 \x01(\x01\x12\x14\n\x0cpart_inst_id\x18\x07 \x01(\x04\x12/\n\x12\x64\x61mage_absorb_info\x18\x08 \x03(\x0b\x32\x13.DAMAGE_ABSORB_INFO\x12/\n\x12\x62\x61ttle_report_info\x18\t \x01(\x0b\x32\x13.BATTLE_REPORT_INFO\x12\x44\n\x16\x63\x61lculation_check_args\x18\n \x01(\x0b\x32$.DEV_BATTLE_CALCULATION_RUNTIME_ARGS\x12K\n\x14processor_debug_args\x18\x0b \x03(\x0b\x32-.BATTLE_DAMAGE_DETAIL.ProcessorDebugArgsEntry\x12N\n\x1b\x63\x61lculate_damage_check_args\x18\x0c \x01(\x0b\x32).DEV_BATTLE_CALCULATE_DAMAGE_RUNTIME_ARGS\x12K\n!attacker_attr_modifier_debug_data\x18\r \x01(\x0b\x32 .CLIENT_ATTR_MODIFIER_DEBUG_DATA\x12K\n!defender_attr_modifier_debug_data\x18\x0e \x01(\x0b\x32 .CLIENT_ATTR_MODIFIER_DEBUG_DATA\x1a\x63\n\x17ProcessorDebugArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_DAMAGE_DETAIL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_DAMAGE_DETAIL_PROCESSORDEBUGARGSENTRY']._loaded_options = None
  _globals['_BATTLE_DAMAGE_DETAIL_PROCESSORDEBUGARGSENTRY']._serialized_options = b'8\001'
  _globals['_BATTLE_DAMAGE_DETAIL']._serialized_start=295
  _globals['_BATTLE_DAMAGE_DETAIL']._serialized_end=1066
  _globals['_BATTLE_DAMAGE_DETAIL_PROCESSORDEBUGARGSENTRY']._serialized_start=967
  _globals['_BATTLE_DAMAGE_DETAIL_PROCESSORDEBUGARGSENTRY']._serialized_end=1066
# @@protoc_insertion_point(module_scope)

