# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_TARGET_HANDLE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_TARGET_HANDLE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_TARGET_WRAPPER_pb2 as BATTLE__TARGET__WRAPPER__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x42\x41TTLE_TARGET_HANDLE.proto\x1a\x1b\x42\x41TTLE_TARGET_WRAPPER.proto\"?\n\x14\x42\x41TTLE_TARGET_HANDLE\x12\'\n\x07targets\x18\x01 \x03(\x0b\x32\x16.BATTLE_TARGET_WRAPPERb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_TARGET_HANDLE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_TARGET_HANDLE']._serialized_start=59
  _globals['_BATTLE_TARGET_HANDLE']._serialized_end=122
# @@protoc_insertion_point(module_scope)

