# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_RESET_REASON.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_RESET_REASON.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x42\x41TTLE_RESET_REASON.proto*\xe5\x01\n\x13\x42\x41TTLE_RESET_REASON\x12\x08\n\x04None\x10\x00\x12\x10\n\x0cGenderChange\x10\x01\x12\x08\n\x04\x44\x65\x63o\x10\x02\x12\x11\n\rObjEnterScene\x10\x03\x12\x06\n\x02Gm\x10\x04\x12\x0c\n\x08\x42\x61ttleOp\x10\x05\x12\x17\n\x13\x42\x65\x66oreDestroyEntity\x10\x06\x12\x14\n\x10SceneResetBattle\x10\x07\x12\x12\n\x0e\x41\x64\x64\x41oiObserver\x10\x08\x12\x0e\n\nReviveChar\x10\t\x12\x13\n\x0fResetPartSummon\x10\n\x12\x17\n\x13ResetBackgroundChar\x10\x0b\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_RESET_REASON_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_RESET_REASON']._serialized_start=30
  _globals['_BATTLE_RESET_REASON']._serialized_end=259
# @@protoc_insertion_point(module_scope)
