# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_TARGET_WRAPPER.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_TARGET_WRAPPER.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import VECTOR_pb2 as VECTOR__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x42\x41TTLE_TARGET_WRAPPER.proto\x1a\x0cVECTOR.proto\"G\n\x15\x42\x41TTLE_TARGET_WRAPPER\x12\x11\n\ttarget_id\x18\x01 \x01(\x04\x12\x1b\n\ntarget_pos\x18\x02 \x01(\x0b\x32\x07.VECTORb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_TARGET_WRAPPER_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_TARGET_WRAPPER']._serialized_start=45
  _globals['_BATTLE_TARGET_WRAPPER']._serialized_end=116
# @@protoc_insertion_point(module_scope)

