# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_BLACKBOARD_ASSIGN_ITEM.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_BLACKBOARD_ASSIGN_ITEM.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#BATTLE_BLACKBOARD_ASSIGN_ITEM.proto\"\x93\x01\n\x1d\x42\x41TTLE_BLACKBOARD_ASSIGN_ITEM\x12\x12\n\ntarget_key\x18\x01 \x01(\t\x12\x17\n\x0finput_value_key\x18\x02 \x01(\t\x12\x18\n\x10use_direct_value\x18\x03 \x01(\x08\x12\x15\n\rnumeric_value\x18\x04 \x01(\x02\x12\x14\n\x0cstring_value\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_BLACKBOARD_ASSIGN_ITEM_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_BLACKBOARD_ASSIGN_ITEM']._serialized_start=40
  _globals['_BATTLE_BLACKBOARD_ASSIGN_ITEM']._serialized_end=187
# @@protoc_insertion_point(module_scope)

