# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_SKILL_ATTACH_OP_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_SKILL_ATTACH_OP_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_SKILL_SOURCE_pb2 as BATTLE__SKILL__SOURCE__pb2
import TEMPLATE_ID_pb2 as TEMPLATE__ID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!BATTLE_SKILL_ATTACH_OP_DATA.proto\x1a\x19\x42\x41TTLE_SKILL_SOURCE.proto\x1a\x11TEMPLATE_ID.proto\"\xa7\x01\n\x1b\x42\x41TTLE_SKILL_ATTACH_OP_DATA\x12\x13\n\x0bsrc_inst_id\x18\x01 \x01(\x04\x12\x1e\n\x08skill_id\x18\x02 \x01(\x0b\x32\x0c.TEMPLATE_ID\x12\x10\n\x08skill_lv\x18\x03 \x01(\x05\x12*\n\x0cskill_source\x18\x04 \x01(\x0e\x32\x14.BATTLE_SKILL_SOURCE\x12\x15\n\rskill_inst_id\x18\x05 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_SKILL_ATTACH_OP_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_SKILL_ATTACH_OP_DATA']._serialized_start=84
  _globals['_BATTLE_SKILL_ATTACH_OP_DATA']._serialized_end=251
# @@protoc_insertion_point(module_scope)

