# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_ABILITY_ENTITY_DETAIL.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_ABILITY_ENTITY_DETAIL.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import VECTOR_pb2 as VECTOR__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"BATTLE_ABILITY_ENTITY_DETAIL.proto\x1a\x0cVECTOR.proto\"\x89\x01\n\x1c\x42\x41TTLE_ABILITY_ENTITY_DETAIL\x12 \n\x18\x63lient_ability_entity_id\x18\x01 \x01(\x04\x12\x11\n\tsource_id\x18\x02 \x01(\x04\x12\x19\n\x08init_pos\x18\x03 \x01(\x0b\x32\x07.VECTOR\x12\x19\n\x08rotation\x18\x04 \x01(\x0b\x32\x07.VECTORb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_ABILITY_ENTITY_DETAIL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_ABILITY_ENTITY_DETAIL']._serialized_start=53
  _globals['_BATTLE_ABILITY_ENTITY_DETAIL']._serialized_end=190
# @@protoc_insertion_point(module_scope)

