# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_ACTION_OPERATE_TYPE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_ACTION_OPERATE_TYPE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n BATTLE_ACTION_OPERATE_TYPE.proto*\xbb\x04\n\x1a\x42\x41TTLE_ACTION_OPERATE_TYPE\x12\x10\n\x0c\x42\x61ttleOpNone\x10\x00\x12\x13\n\x0f\x42\x61ttleOpAddBuff\x10\x01\x12\x16\n\x12\x42\x61ttleOpFinishBuff\x10\x02\x12\x17\n\x13\x42\x61ttleOpSkillAttach\x10\x03\x12\x17\n\x13\x42\x61ttleOpSkillDetach\x10\x04\x12\x1a\n\x16\x42\x61ttleOpSkillStartCast\x10\x05\x12\x18\n\x14\x42\x61ttleOpSkillEndCast\x10\x06\x12\x16\n\x12\x42\x61ttleOpSwitchMode\x10\x07\x12\x19\n\x15\x42\x61ttleOpTriggerAction\x10\x08\x12\x15\n\x11\x42\x61ttleOpEntityDie\x10\n\x12\x1d\n\x19\x42\x61ttleOpEntityValueModify\x10\x0b\x12\x1b\n\x17\x42\x61ttleOpResetBattleData\x10\x0c\x12\x1d\n\x19\x42\x61ttleOpUpdateDataVersion\x10\r\x12\x1e\n\x1a\x42\x61ttleOpEnablePassiveSkill\x10\x0e\x12\x1a\n\x16\x42\x61ttleOpTriggerKeyword\x10\x0f\x12\x1d\n\x19\x42\x61ttleOpShieldValueModify\x10\x10\x12\x19\n\x15\x42\x61ttleOpUpdateAtbInfo\x10\x11\x12\x1d\n\x19\x42\x61ttleOpModifyBattleState\x10\x12\x12\x1c\n\x18\x42\x61ttleOpModifyPoiseValue\x10\x13\x12\x1e\n\x1a\x42\x61ttleOpSetBuffEnableState\x10\x14\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_ACTION_OPERATE_TYPE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_ACTION_OPERATE_TYPE']._serialized_start=37
  _globals['_BATTLE_ACTION_OPERATE_TYPE']._serialized_end=608
# @@protoc_insertion_point(module_scope)

