# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_MODIFIER_HANDLE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_MODIFIER_HANDLE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_pb2 as BATTLE__CLIENT__PROCESSOR__DEBUG__ARGS__ITEM__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x42\x41TTLE_MODIFIER_HANDLE.proto\x1a-BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM.proto\"\xf1\x01\n\x16\x42\x41TTLE_MODIFIER_HANDLE\x12\x14\n\x0c\x62uff_inst_id\x18\x01 \x01(\x04\x12\r\n\x05index\x18\x02 \x01(\x05\x12M\n\x14processor_debug_args\x18\x03 \x03(\x0b\x32/.BATTLE_MODIFIER_HANDLE.ProcessorDebugArgsEntry\x1a\x63\n\x17ProcessorDebugArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_MODIFIER_HANDLE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_MODIFIER_HANDLE_PROCESSORDEBUGARGSENTRY']._loaded_options = None
  _globals['_BATTLE_MODIFIER_HANDLE_PROCESSORDEBUGARGSENTRY']._serialized_options = b'8\001'
  _globals['_BATTLE_MODIFIER_HANDLE']._serialized_start=80
  _globals['_BATTLE_MODIFIER_HANDLE']._serialized_end=321
  _globals['_BATTLE_MODIFIER_HANDLE_PROCESSORDEBUGARGSENTRY']._serialized_start=222
  _globals['_BATTLE_MODIFIER_HANDLE_PROCESSORDEBUGARGSENTRY']._serialized_end=321
# @@protoc_insertion_point(module_scope)

