# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_OP_MODIFY_POISE_VALUE_OP_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_OP_MODIFY_POISE_VALUE_OP_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_ACTION_OWNER_TYPE_pb2 as BATTLE__ACTION__OWNER__TYPE__pb2
import BATTLE_REPORT_INFO_pb2 as BATTLE__REPORT__INFO__pb2
import MODIFY_POISE_VALUE_TYPE_pb2 as MODIFY__POISE__VALUE__TYPE__pb2
import TEMPLATE_ID_pb2 as TEMPLATE__ID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*BATTLE_OP_MODIFY_POISE_VALUE_OP_DATA.proto\x1a\x1e\x42\x41TTLE_ACTION_OWNER_TYPE.proto\x1a\x18\x42\x41TTLE_REPORT_INFO.proto\x1a\x1dMODIFY_POISE_VALUE_TYPE.proto\x1a\x11TEMPLATE_ID.proto\"\xe0\x02\n$BATTLE_OP_MODIFY_POISE_VALUE_OP_DATA\x12-\n\x0bmodify_type\x18\x01 \x01(\x0e\x32\x18.MODIFY_POISE_VALUE_TYPE\x12!\n\x0btemplate_id\x18\x02 \x01(\x0b\x32\x0c.TEMPLATE_ID\x12\x31\n\x1boriginal_source_template_id\x18\x03 \x01(\x0b\x32\x0c.TEMPLATE_ID\x12-\n\nowner_type\x18\x04 \x01(\x0e\x32\x19.BATTLE_ACTION_OWNER_TYPE\x12\r\n\x05value\x18\x05 \x01(\x01\x12\x17\n\x0f\x63ur_poise_value\x18\x06 \x01(\x01\x12\x18\n\x10\x61ttacker_inst_id\x18\x07 \x01(\x04\x12\x11\n\taction_id\x18\x08 \x01(\x05\x12/\n\x12\x62\x61ttle_report_info\x18\t \x01(\x0b\x32\x13.BATTLE_REPORT_INFOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_OP_MODIFY_POISE_VALUE_OP_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_OP_MODIFY_POISE_VALUE_OP_DATA']._serialized_start=155
  _globals['_BATTLE_OP_MODIFY_POISE_VALUE_OP_DATA']._serialized_end=507
# @@protoc_insertion_point(module_scope)

