# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_HEAL_ACTION_RUNTIME.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_HEAL_ACTION_RUNTIME.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_HEAL_ACTION_DETAIL_pb2 as BATTLE__HEAL__ACTION__DETAIL__pb2
import TEMPLATE_ID_pb2 as TEMPLATE__ID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n BATTLE_HEAL_ACTION_RUNTIME.proto\x1a\x1f\x42\x41TTLE_HEAL_ACTION_DETAIL.proto\x1a\x11TEMPLATE_ID.proto\"|\n\x1a\x42\x41TTLE_HEAL_ACTION_RUNTIME\x12+\n\x07\x64\x65tails\x18\x01 \x03(\x0b\x32\x1a.BATTLE_HEAL_ACTION_DETAIL\x12\x31\n\x1boriginal_source_template_id\x18\x02 \x01(\x0b\x32\x0c.TEMPLATE_IDb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_HEAL_ACTION_RUNTIME_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_HEAL_ACTION_RUNTIME']._serialized_start=88
  _globals['_BATTLE_HEAL_ACTION_RUNTIME']._serialized_end=212
# @@protoc_insertion_point(module_scope)

