# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME_DETAIL_pb2 as BATTLE__READ__SKILL__SETTING__TO__BB__ACTION__RUNTIME__DETAIL__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME.proto\x1a;BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME_DETAIL.proto\"\x81\x01\n.BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME\x12O\n\x0fruntime_details\x18\x01 \x03(\x0b\x32\x36.BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME_DETAILb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME']._serialized_start=118
  _globals['_BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME']._serialized_end=247
# @@protoc_insertion_point(module_scope)

