# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_SPAWN_CUSTOM_SUMMON_DETAIL.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_SPAWN_CUSTOM_SUMMON_DETAIL.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_BLACKBOARD_pb2 as BATTLE__BLACKBOARD__pb2
import TEMPLATE_ID_pb2 as TEMPLATE__ID__pb2
import VECTOR_pb2 as VECTOR__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'BATTLE_SPAWN_CUSTOM_SUMMON_DETAIL.proto\x1a\x17\x42\x41TTLE_BLACKBOARD.proto\x1a\x11TEMPLATE_ID.proto\x1a\x0cVECTOR.proto\"\xf0\x01\n!BATTLE_SPAWN_CUSTOM_SUMMON_DETAIL\x12\x11\n\tsummon_id\x18\x01 \x01(\t\x12%\n\x0fsummon_skill_id\x18\x02 \x01(\x0b\x32\x0c.TEMPLATE_ID\x12 \n\x18\x63lient_ability_entity_id\x18\x03 \x01(\x04\x12\x19\n\x08init_pos\x18\x04 \x01(\x0b\x32\x07.VECTOR\x12\x19\n\x08rotation\x18\x05 \x01(\x0b\x32\x07.VECTOR\x12&\n\nblackboard\x18\x06 \x01(\x0b\x32\x12.BATTLE_BLACKBOARD\x12\x11\n\tsource_id\x18\x07 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_SPAWN_CUSTOM_SUMMON_DETAIL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_SPAWN_CUSTOM_SUMMON_DETAIL']._serialized_start=102
  _globals['_BATTLE_SPAWN_CUSTOM_SUMMON_DETAIL']._serialized_end=342
# @@protoc_insertion_point(module_scope)

