# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_ENTITY_VALUE_MODIFY_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_ENTITY_VALUE_MODIFY_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_INFO_pb2 as BATTLE__INFO__pb2
import TEMPLATE_ID_pb2 as TEMPLATE__ID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%BATTLE_ENTITY_VALUE_MODIFY_DATA.proto\x1a\x11\x42\x41TTLE_INFO.proto\x1a\x11TEMPLATE_ID.proto\"\xe7\x01\n\x1f\x42\x41TTLE_ENTITY_VALUE_MODIFY_DATA\x12\x16\n\x0e\x65ntity_inst_id\x18\x01 \x01(\x04\x12\x14\n\x0cscene_num_id\x18\x02 \x01(\x05\x12\x1b\n\x05value\x18\x03 \x01(\x0b\x32\x0c.BATTLE_INFO\x12\x0e\n\x06source\x18\x04 \x01(\x05\x12!\n\x0btemplate_id\x18\x05 \x01(\x0b\x32\x0c.TEMPLATE_ID\x12\x31\n\x1boriginal_source_template_id\x18\x06 \x01(\x0b\x32\x0c.TEMPLATE_ID\x12\x13\n\x0b\x64\x65lta_value\x18\x07 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_ENTITY_VALUE_MODIFY_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_ENTITY_VALUE_MODIFY_DATA']._serialized_start=80
  _globals['_BATTLE_ENTITY_VALUE_MODIFY_DATA']._serialized_end=311
# @@protoc_insertion_point(module_scope)

