# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME_DETAIL.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME_DETAIL.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME_DETAIL.proto\"\xa4\x01\n5BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME_DETAIL\x12\x18\n\x10\x63lient_layer_cnt\x18\x01 \x01(\x05\x12\x14\n\x0c\x63lient_value\x18\x02 \x01(\x01\x12\x1a\n\x12\x65nhance_attr_value\x18\x03 \x01(\x01\x12\x1f\n\x17\x61ttacker_battle_inst_id\x18\x04 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME_DETAIL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME_DETAIL']._serialized_start=64
  _globals['_BATTLE_READ_SKILL_SETTING_TO_BB_ACTION_RUNTIME_DETAIL']._serialized_end=228
# @@protoc_insertion_point(module_scope)

