# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_SIMPLE_CALC_BB_ACTION_RUNTIME.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_SIMPLE_CALC_BB_ACTION_RUNTIME.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*BATTLE_SIMPLE_CALC_BB_ACTION_RUNTIME.proto\"\x8d\x01\n$BATTLE_SIMPLE_CALC_BB_ACTION_RUNTIME\x12\x16\n\x0e\x63lient_value_a\x18\x01 \x01(\x01\x12\x16\n\x0e\x63lient_value_b\x18\x02 \x01(\x01\x12\x19\n\x11\x63lient_target_key\x18\x03 \x01(\t\x12\x1a\n\x12\x63lient_final_value\x18\x04 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_SIMPLE_CALC_BB_ACTION_RUNTIME_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_SIMPLE_CALC_BB_ACTION_RUNTIME']._serialized_start=47
  _globals['_BATTLE_SIMPLE_CALC_BB_ACTION_RUNTIME']._serialized_end=188
# @@protoc_insertion_point(module_scope)

