# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_UPDATE_ATB_INFO_OP_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_UPDATE_ATB_INFO_OP_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_ATB_DATA_pb2 as BATTLE__ATB__DATA__pb2
import TEMPLATE_ID_pb2 as TEMPLATE__ID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$BATTLE_UPDATE_ATB_INFO_OP_DATA.proto\x1a\x15\x42\x41TTLE_ATB_DATA.proto\x1a\x11TEMPLATE_ID.proto\"\xaf\x01\n\x1e\x42\x41TTLE_UPDATE_ATB_INFO_OP_DATA\x12\"\n\x08\x61tb_data\x18\x01 \x01(\x0b\x32\x10.BATTLE_ATB_DATA\x12!\n\x0btemplate_id\x18\x02 \x01(\x0b\x32\x0c.TEMPLATE_ID\x12\x31\n\x1boriginal_source_template_id\x18\x03 \x01(\x0b\x32\x0c.TEMPLATE_ID\x12\x13\n\x0b\x64\x65lta_value\x18\x04 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_UPDATE_ATB_INFO_OP_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_UPDATE_ATB_INFO_OP_DATA']._serialized_start=83
  _globals['_BATTLE_UPDATE_ATB_INFO_OP_DATA']._serialized_end=258
# @@protoc_insertion_point(module_scope)

