# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_FINISH_BUFF_ACTION_RUNTIME.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_FINISH_BUFF_ACTION_RUNTIME.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_FINISH_BUFF_ACTION_DETAIL_pb2 as BATTLE__FINISH__BUFF__ACTION__DETAIL__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'BATTLE_FINISH_BUFF_ACTION_RUNTIME.proto\x1a&BATTLE_FINISH_BUFF_ACTION_DETAIL.proto\"v\n!BATTLE_FINISH_BUFF_ACTION_RUNTIME\x12\x37\n\x0c\x66inish_buffs\x18\x01 \x03(\x0b\x32!.BATTLE_FINISH_BUFF_ACTION_DETAIL\x12\x18\n\x10\x66inish_layer_cnt\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_FINISH_BUFF_ACTION_RUNTIME_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_FINISH_BUFF_ACTION_RUNTIME']._serialized_start=83
  _globals['_BATTLE_FINISH_BUFF_ACTION_RUNTIME']._serialized_end=201
# @@protoc_insertion_point(module_scope)

