# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_INSTANT_MODIFY_ATTRIBUTE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_INSTANT_MODIFY_ATTRIBUTE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CLIENT_ATTR_MODIFIER_DEBUG_DATA_pb2 as CLIENT__ATTR__MODIFIER__DEBUG__DATA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFBATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_INSTANT_MODIFY_ATTRIBUTE.proto\x1a%CLIENT_ATTR_MODIFIER_DEBUG_DATA.proto\"\x9c\x01\n@BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_INSTANT_MODIFY_ATTRIBUTE\x12\x14\n\x0c\x63lient_value\x18\x01 \x01(\x01\x12\x42\n\x18\x61ttr_modifier_debug_data\x18\x02 \x01(\x0b\x32 .CLIENT_ATTR_MODIFIER_DEBUG_DATAb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_INSTANT_MODIFY_ATTRIBUTE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_INSTANT_MODIFY_ATTRIBUTE']._serialized_start=114
  _globals['_BATTLE_CLIENT_PROCESSOR_DEBUG_ARGS_ITEM_INSTANT_MODIFY_ATTRIBUTE']._serialized_end=270
# @@protoc_insertion_point(module_scope)

