# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_OP_SET_BUFF_ENABLE_STATE_OP_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_OP_SET_BUFF_ENABLE_STATE_OP_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-BATTLE_OP_SET_BUFF_ENABLE_STATE_OP_DATA.proto\"\xd6\x01\n\'BATTLE_OP_SET_BUFF_ENABLE_STATE_OP_DATA\x12k\n\x1c\x62uff_inst_id_to_enable_state\x18\x01 \x03(\x0b\x32\x45.BATTLE_OP_SET_BUFF_ENABLE_STATE_OP_DATA.BuffInstIdToEnableStateEntry\x1a>\n\x1c\x42uffInstIdToEnableStateEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_OP_SET_BUFF_ENABLE_STATE_OP_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_OP_SET_BUFF_ENABLE_STATE_OP_DATA_BUFFINSTIDTOENABLESTATEENTRY']._loaded_options = None
  _globals['_BATTLE_OP_SET_BUFF_ENABLE_STATE_OP_DATA_BUFFINSTIDTOENABLESTATEENTRY']._serialized_options = b'8\001'
  _globals['_BATTLE_OP_SET_BUFF_ENABLE_STATE_OP_DATA']._serialized_start=50
  _globals['_BATTLE_OP_SET_BUFF_ENABLE_STATE_OP_DATA']._serialized_end=264
  _globals['_BATTLE_OP_SET_BUFF_ENABLE_STATE_OP_DATA_BUFFINSTIDTOENABLESTATEENTRY']._serialized_start=202
  _globals['_BATTLE_OP_SET_BUFF_ENABLE_STATE_OP_DATA_BUFFINSTIDTOENABLESTATEENTRY']._serialized_end=264
# @@protoc_insertion_point(module_scope)

