# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_MGR_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_MGR_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_PART_INST_INFO_pb2 as BATTLE__PART__INST__INFO__pb2
import SERVER_BUFF_pb2 as SERVER__BUFF__pb2
import SERVER_BUFF_STACKING_GROUP_pb2 as SERVER__BUFF__STACKING__GROUP__pb2
import SERVER_SKILL_pb2 as SERVER__SKILL__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x42\x41TTLE_MGR_INFO.proto\x1a\x1b\x42\x41TTLE_PART_INST_INFO.proto\x1a\x11SERVER_BUFF.proto\x1a SERVER_BUFF_STACKING_GROUP.proto\x1a\x12SERVER_SKILL.proto\"\xef\x01\n\x0f\x42\x41TTLE_MGR_INFO\x12\x1f\n\tbuff_list\x18\x01 \x03(\x0b\x32\x0c.SERVER_BUFF\x12!\n\nskill_list\x18\x02 \x03(\x0b\x32\r.SERVER_SKILL\x12\x16\n\x0emsg_generation\x18\x03 \x01(\r\x12\x16\n\x0e\x62\x61ttle_inst_id\x18\x04 \x01(\x04\x12\x38\n\x13stacking_group_list\x18\x05 \x03(\x0b\x32\x1b.SERVER_BUFF_STACKING_GROUP\x12.\n\x0epart_inst_info\x18\x06 \x01(\x0b\x32\x16.BATTLE_PART_INST_INFOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_MGR_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_MGR_INFO']._serialized_start=128
  _globals['_BATTLE_MGR_INFO']._serialized_end=367
# @@protoc_insertion_point(module_scope)

