# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_SET_BLACKBOARD_FROM_PRESET_RUNTIME.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_SET_BLACKBOARD_FROM_PRESET_RUNTIME.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/BATTLE_SET_BLACKBOARD_FROM_PRESET_RUNTIME.proto\"C\n)BATTLE_SET_BLACKBOARD_FROM_PRESET_RUNTIME\x12\x16\n\x0emodified_value\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_SET_BLACKBOARD_FROM_PRESET_RUNTIME_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_SET_BLACKBOARD_FROM_PRESET_RUNTIME']._serialized_start=51
  _globals['_BATTLE_SET_BLACKBOARD_FROM_PRESET_RUNTIME']._serialized_end=118
# @@protoc_insertion_point(module_scope)

