# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_CLIENT_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_CLIENT_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_CLIENT_OP_DATA_pb2 as BATTLE__CLIENT__OP__DATA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x42\x41TTLE_CLIENT_DATA.proto\x1a\x1b\x42\x41TTLE_CLIENT_OP_DATA.proto\"=\n\x12\x42\x41TTLE_CLIENT_DATA\x12\'\n\x07op_list\x18\x01 \x03(\x0b\x32\x16.BATTLE_CLIENT_OP_DATAb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_CLIENT_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_CLIENT_DATA']._serialized_start=57
  _globals['_BATTLE_CLIENT_DATA']._serialized_end=118
# @@protoc_insertion_point(module_scope)

