# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_BLACKBOARD.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_BLACKBOARD.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_BLACKBOARD_DATA_pb2 as BATTLE__BLACKBOARD__DATA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x42\x41TTLE_BLACKBOARD.proto\x1a\x1c\x42\x41TTLE_BLACKBOARD_DATA.proto\"\x97\x01\n\x11\x42\x41TTLE_BLACKBOARD\x12\x36\n\nblackboard\x18\x01 \x03(\x0b\x32\".BATTLE_BLACKBOARD.BlackboardEntry\x1aJ\n\x0f\x42lackboardEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.BATTLE_BLACKBOARD_DATA:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_BLACKBOARD_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_BLACKBOARD_BLACKBOARDENTRY']._loaded_options = None
  _globals['_BATTLE_BLACKBOARD_BLACKBOARDENTRY']._serialized_options = b'8\001'
  _globals['_BATTLE_BLACKBOARD']._serialized_start=58
  _globals['_BATTLE_BLACKBOARD']._serialized_end=209
  _globals['_BATTLE_BLACKBOARD_BLACKBOARDENTRY']._serialized_start=135
  _globals['_BATTLE_BLACKBOARD_BLACKBOARDENTRY']._serialized_end=209
# @@protoc_insertion_point(module_scope)

