# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_HEAL_MODIFIER_ARGS.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_HEAL_MODIFIER_ARGS.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_MODIFIER_HANDLE_pb2 as BATTLE__MODIFIER__HANDLE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x42\x41TTLE_HEAL_MODIFIER_ARGS.proto\x1a\x1c\x42\x41TTLE_MODIFIER_HANDLE.proto\"\xb3\x01\n\x19\x42\x41TTLE_HEAL_MODIFIER_ARGS\x12\x11\n\thealer_id\x18\x01 \x01(\x04\x12\x17\n\x0fheal_receive_id\x18\x02 \x01(\x04\x12\x31\n\x10healer_modifiers\x18\x03 \x03(\x0b\x32\x17.BATTLE_MODIFIER_HANDLE\x12\x37\n\x16heal_receive_modifiers\x18\x04 \x03(\x0b\x32\x17.BATTLE_MODIFIER_HANDLEb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_HEAL_MODIFIER_ARGS_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_HEAL_MODIFIER_ARGS']._serialized_start=66
  _globals['_BATTLE_HEAL_MODIFIER_ARGS']._serialized_end=245
# @@protoc_insertion_point(module_scope)

