# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BATTLE_SKILL_SOURCE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BATTLE_SKILL_SOURCE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x42\x41TTLE_SKILL_SOURCE.proto*\xcc\x01\n\x13\x42\x41TTLE_SKILL_SOURCE\x12\x0b\n\x07\x44\x65\x66\x61ult\x10\x00\x12\x08\n\x04Mode\x10\x01\x12\n\n\x06Weapon\x10\x02\x12\r\n\tEquipSuit\x10\x03\x12\t\n\x05Other\x10\x04\x12\x0f\n\x0bInteractive\x10\x05\x12\n\n\x06Summon\x10\x06\x12\x12\n\x0ePlungingAttack\x10\x07\x12\x0f\n\x0bPowerAttack\x10\x08\x12\x13\n\x0fTalentPotential\x10\t\x12\x0e\n\nCharCommon\x10\n\x12\x11\n\rClientTempAdd\x10\x0b\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BATTLE_SKILL_SOURCE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLE_SKILL_SOURCE']._serialized_start=30
  _globals['_BATTLE_SKILL_SOURCE']._serialized_end=234
# @@protoc_insertion_point(module_scope)

