# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BREAKING_ATTACK_CALCULATION_RUNTIME_ARGS.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BREAKING_ATTACK_CALCULATION_RUNTIME_ARGS.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.BREAKING_ATTACK_CALCULATION_RUNTIME_ARGS.proto\"\xb6\x01\n(BREAKING_ATTACK_CALCULATION_RUNTIME_ARGS\x12\x18\n\x10\x63lient_atk_scale\x18\x01 \x01(\x01\x12\x19\n\x11\x63lient_multiplier\x18\x02 \x01(\x01\x12\x1b\n\x13\x63lient_attacker_atk\x18\x03 \x01(\x01\x12\x38\n0client_defender_breaking_attack_dmg_taken_scalar\x18\x04 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BREAKING_ATTACK_CALCULATION_RUNTIME_ARGS_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BREAKING_ATTACK_CALCULATION_RUNTIME_ARGS']._serialized_start=51
  _globals['_BREAKING_ATTACK_CALCULATION_RUNTIME_ARGS']._serialized_end=233
# @@protoc_insertion_point(module_scope)

