# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CLIENT_ATTR_MODIFIER_LIST.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CLIENT_ATTR_MODIFIER_LIST.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CLIENT_ATTR_MODIFIER_pb2 as CLIENT__ATTR__MODIFIER__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x43LIENT_ATTR_MODIFIER_LIST.proto\x1a\x1a\x43LIENT_ATTR_MODIFIER.proto\"c\n\x19\x43LIENT_ATTR_MODIFIER_LIST\x12\x31\n\x12\x61ttr_modifier_list\x18\x01 \x03(\x0b\x32\x15.CLIENT_ATTR_MODIFIER\x12\x13\n\x0b\x62\x61sic_value\x18\x02 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CLIENT_ATTR_MODIFIER_LIST_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENT_ATTR_MODIFIER_LIST']._serialized_start=63
  _globals['_CLIENT_ATTR_MODIFIER_LIST']._serialized_end=162
# @@protoc_insertion_point(module_scope)

