# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CLIENT_ATTR_MODIFIER_DEBUG_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CLIENT_ATTR_MODIFIER_DEBUG_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CLIENT_ATTR_MODIFIER_LIST_pb2 as CLIENT__ATTR__MODIFIER__LIST__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%CLIENT_ATTR_MODIFIER_DEBUG_DATA.proto\x1a\x1f\x43LIENT_ATTR_MODIFIER_LIST.proto\"\xc7\x01\n\x1f\x43LIENT_ATTR_MODIFIER_DEBUG_DATA\x12P\n\x11\x61ttr_modifier_map\x18\x01 \x03(\x0b\x32\x35.CLIENT_ATTR_MODIFIER_DEBUG_DATA.AttrModifierMapEntry\x1aR\n\x14\x41ttrModifierMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.CLIENT_ATTR_MODIFIER_LIST:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CLIENT_ATTR_MODIFIER_DEBUG_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENT_ATTR_MODIFIER_DEBUG_DATA_ATTRMODIFIERMAPENTRY']._loaded_options = None
  _globals['_CLIENT_ATTR_MODIFIER_DEBUG_DATA_ATTRMODIFIERMAPENTRY']._serialized_options = b'8\001'
  _globals['_CLIENT_ATTR_MODIFIER_DEBUG_DATA']._serialized_start=75
  _globals['_CLIENT_ATTR_MODIFIER_DEBUG_DATA']._serialized_end=274
  _globals['_CLIENT_ATTR_MODIFIER_DEBUG_DATA_ATTRMODIFIERMAPENTRY']._serialized_start=192
  _globals['_CLIENT_ATTR_MODIFIER_DEBUG_DATA_ATTRMODIFIERMAPENTRY']._serialized_end=274
# @@protoc_insertion_point(module_scope)

