# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CLIENT_ATTR_MODIFIER.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CLIENT_ATTR_MODIFIER.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ATTR_MODIFY_DATA_pb2 as ATTR__MODIFY__DATA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x43LIENT_ATTR_MODIFIER.proto\x1a\x16\x41TTR_MODIFY_DATA.proto\"U\n\x14\x43LIENT_ATTR_MODIFIER\x12\x15\n\rattr_src_mask\x18\x01 \x01(\x04\x12&\n\x0bmodify_data\x18\x02 \x01(\x0b\x32\x11.ATTR_MODIFY_DATAb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CLIENT_ATTR_MODIFIER_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENT_ATTR_MODIFIER']._serialized_start=54
  _globals['_CLIENT_ATTR_MODIFIER']._serialized_end=139
# @@protoc_insertion_point(module_scope)

