# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CS_CONDITIONAL_MULTI_STAGE_ACTIVITY_GAIN_REWARD.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CS_CONDITIONAL_MULTI_STAGE_ACTIVITY_GAIN_REWARD.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5CS_CONDITIONAL_MULTI_STAGE_ACTIVITY_GAIN_REWARD.proto\"]\n/CS_CONDITIONAL_MULTI_STAGE_ACTIVITY_GAIN_REWARD\x12\x13\n\x0b\x61\x63tivity_id\x18\x01 \x01(\t\x12\x15\n\rstage_id_list\x18\x02 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CS_CONDITIONAL_MULTI_STAGE_ACTIVITY_GAIN_REWARD_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CS_CONDITIONAL_MULTI_STAGE_ACTIVITY_GAIN_REWARD']._serialized_start=57
  _globals['_CS_CONDITIONAL_MULTI_STAGE_ACTIVITY_GAIN_REWARD']._serialized_end=150
# @@protoc_insertion_point(module_scope)
