# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CS_ENTER_DUNGEON.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CS_ENTER_DUNGEON.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ENTER_RACING_DUNGEON_PARAM_pb2 as ENTER__RACING__DUNGEON__PARAM__pb2
import ENTER_WEEK_RAID_PARAM_pb2 as ENTER__WEEK__RAID__PARAM__pb2
import TEAM_CHAR_ID_pb2 as TEAM__CHAR__ID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x43S_ENTER_DUNGEON.proto\x1a ENTER_RACING_DUNGEON_PARAM.proto\x1a\x1b\x45NTER_WEEK_RAID_PARAM.proto\x1a\x12TEAM_CHAR_ID.proto\"\xbf\x01\n\x10\x43S_ENTER_DUNGEON\x12 \n\tchar_team\x18\x01 \x03(\x0b\x32\r.TEAM_CHAR_ID\x12\x12\n\ndungeon_id\x18\x02 \x01(\t\x12\x33\n\x0cracing_param\x18\x15 \x01(\x0b\x32\x1b.ENTER_RACING_DUNGEON_PARAMH\x00\x12\x31\n\x0fweek_raid_param\x18\x16 \x01(\x0b\x32\x16.ENTER_WEEK_RAID_PARAMH\x00\x42\r\n\x0b\x65nter_paramb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CS_ENTER_DUNGEON_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CS_ENTER_DUNGEON']._serialized_start=110
  _globals['_CS_ENTER_DUNGEON']._serialized_end=301
# @@protoc_insertion_point(module_scope)

