# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CS_FRIEND_BUSINESS_CARD_QUERY.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CS_FRIEND_BUSINESS_CARD_QUERY.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FRIEND_BUSINESS_CARD_TYPE_pb2 as FRIEND__BUSINESS__CARD__TYPE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#CS_FRIEND_BUSINESS_CARD_QUERY.proto\x1a\x1f\x46RIEND_BUSINESS_CARD_TYPE.proto\"Z\n\x1d\x43S_FRIEND_BUSINESS_CARD_QUERY\x12\x0f\n\x07role_id\x18\x01 \x01(\x04\x12(\n\x04type\x18\x02 \x01(\x0e\x32\x1a.FRIEND_BUSINESS_CARD_TYPEb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CS_FRIEND_BUSINESS_CARD_QUERY_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CS_FRIEND_BUSINESS_CARD_QUERY']._serialized_start=72
  _globals['_CS_FRIEND_BUSINESS_CARD_QUERY']._serialized_end=162
# @@protoc_insertion_point(module_scope)
