# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CS_GAME_MECHANICS_REQ_START.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CS_GAME_MECHANICS_REQ_START.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!CS_GAME_MECHANICS_REQ_START.proto\"t\n\x1b\x43S_GAME_MECHANICS_REQ_START\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x1a\n\x12interactive_obj_id\x18\x02 \x01(\x04\x12\x14\n\x0cnpc_proxy_id\x18\x03 \x01(\t\x12\x12\n\nnpc_obj_id\x18\x04 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CS_GAME_MECHANICS_REQ_START_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CS_GAME_MECHANICS_REQ_START']._serialized_start=37
  _globals['_CS_GAME_MECHANICS_REQ_START']._serialized_end=153
# @@protoc_insertion_point(module_scope)
