# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DEV_BATTLE_CALCULATE_DAMAGE_RUNTIME_ARGS.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'DEV_BATTLE_CALCULATE_DAMAGE_RUNTIME_ARGS.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.DEV_BATTLE_CALCULATE_DAMAGE_RUNTIME_ARGS.proto\"\xf6\x03\n(DEV_BATTLE_CALCULATE_DAMAGE_RUNTIME_ARGS\x12 \n\x18\x63lient_calc_result_value\x18\x01 \x01(\x01\x12!\n\x19\x63lient_final_damage_scale\x18\x02 \x01(\x01\x12\x1b\n\x13\x63lient_attack_value\x18\x03 \x01(\x01\x12\x1d\n\x15\x63lient_crit_add_scale\x18\x04 \x01(\x01\x12$\n\x1c\x63lient_def_attr_defender_def\x18\x05 \x01(\x01\x12\x1d\n\x15\x63lient_def_resistance\x18\x06 \x01(\x01\x12\"\n\x1a\x63lient_dmg_type_resistance\x18\x07 \x01(\x01\x12$\n\x1c\x63lient_defender_poise_factor\x18\x08 \x01(\x01\x12#\n\x1b\x63lient_ignite_damage_scalar\x18\t \x01(\x01\x12\x1a\n\x12\x63lient_final_value\x18\n \x01(\x01\x12!\n\x19\x63lient_weak_damage_scalar\x18\x0b \x01(\x01\x12$\n\x1c\x63lient_shelter_damage_scalar\x18\x0c \x01(\x01\x12\x30\n(client_physical_infliction_damage_scalar\x18\r \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DEV_BATTLE_CALCULATE_DAMAGE_RUNTIME_ARGS_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEV_BATTLE_CALCULATE_DAMAGE_RUNTIME_ARGS']._serialized_start=51
  _globals['_DEV_BATTLE_CALCULATE_DAMAGE_RUNTIME_ARGS']._serialized_end=553
# @@protoc_insertion_point(module_scope)

