# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DEV_BATTLE_CALCULATION_RUNTIME_ARGS.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'DEV_BATTLE_CALCULATION_RUNTIME_ARGS.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ATK_SCALE_CALCULATION_RUNTIME_ARGS_pb2 as ATK__SCALE__CALCULATION__RUNTIME__ARGS__pb2
import BREAKING_ATTACK_CALCULATION_RUNTIME_ARGS_pb2 as BREAKING__ATTACK__CALCULATION__RUNTIME__ARGS__pb2
import DEFINITE_VALUE_CALCULATION_RUNTIME_ARGS_pb2 as DEFINITE__VALUE__CALCULATION__RUNTIME__ARGS__pb2
import MULTIPLY_ATTRIBUTE_CALCULATION_RUNTIME_ARGS_pb2 as MULTIPLY__ATTRIBUTE__CALCULATION__RUNTIME__ARGS__pb2
import PRIMARY_ATTR_CALCULATION_RUNTIME_ARGS_pb2 as PRIMARY__ATTR__CALCULATION__RUNTIME__ARGS__pb2
import SIMPLE_CALC_RUNTIME_ARGS_pb2 as SIMPLE__CALC__RUNTIME__ARGS__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)DEV_BATTLE_CALCULATION_RUNTIME_ARGS.proto\x1a(ATK_SCALE_CALCULATION_RUNTIME_ARGS.proto\x1a.BREAKING_ATTACK_CALCULATION_RUNTIME_ARGS.proto\x1a-DEFINITE_VALUE_CALCULATION_RUNTIME_ARGS.proto\x1a\x31MULTIPLY_ATTRIBUTE_CALCULATION_RUNTIME_ARGS.proto\x1a+PRIMARY_ATTR_CALCULATION_RUNTIME_ARGS.proto\x1a\x1eSIMPLE_CALC_RUNTIME_ARGS.proto\"\xc5\x04\n#DEV_BATTLE_CALCULATION_RUNTIME_ARGS\x12=\n\x18simple_calc_runtime_args\x18\x64 \x01(\x0b\x32\x19.SIMPLE_CALC_RUNTIME_ARGSH\x00\x12Q\n\"atk_scale_calculation_runtime_args\x18\x65 \x01(\x0b\x32#.ATK_SCALE_CALCULATION_RUNTIME_ARGSH\x00\x12[\n\'definite_value_calculation_runtime_args\x18\x66 \x01(\x0b\x32(.DEFINITE_VALUE_CALCULATION_RUNTIME_ARGSH\x00\x12\x63\n+multiply_attribute_calculation_runtime_args\x18g \x01(\x0b\x32,.MULTIPLY_ATTRIBUTE_CALCULATION_RUNTIME_ARGSH\x00\x12]\n(breaking_attack_calculation_runtime_args\x18h \x01(\x0b\x32).BREAKING_ATTACK_CALCULATION_RUNTIME_ARGSH\x00\x12W\n%primary_attr_calculation_runtime_args\x18i \x01(\x0b\x32&.PRIMARY_ATTR_CALCULATION_RUNTIME_ARGSH\x00\x42\x12\n\x10\x63\x61lculation_argsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DEV_BATTLE_CALCULATION_RUNTIME_ARGS_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEV_BATTLE_CALCULATION_RUNTIME_ARGS']._serialized_start=311
  _globals['_DEV_BATTLE_CALCULATION_RUNTIME_ARGS']._serialized_end=892
# @@protoc_insertion_point(module_scope)

