# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DYNAMIC_PARAMETER.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'DYNAMIC_PARAMETER.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x44YNAMIC_PARAMETER.proto\"\xa0\x01\n\x11\x44YNAMIC_PARAMETER\x12\x12\n\nvalue_type\x18\x01 \x01(\x05\x12\x11\n\treal_type\x18\x02 \x01(\x05\x12\x17\n\x0fvalue_bool_list\x18\x03 \x03(\x08\x12\x16\n\x0evalue_int_list\x18\x04 \x03(\x03\x12\x18\n\x10value_float_list\x18\x05 \x03(\x02\x12\x19\n\x11value_string_list\x18\x06 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DYNAMIC_PARAMETER_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DYNAMIC_PARAMETER']._serialized_start=28
  _globals['_DYNAMIC_PARAMETER']._serialized_end=188
# @@protoc_insertion_point(module_scope)

