# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ENTER_RACING_DUNGEON_PARAM.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ENTER_RACING_DUNGEON_PARAM.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ENTER_RACING_DUNGEON_PARAM.proto\"?\n\x1a\x45NTER_RACING_DUNGEON_PARAM\x12\r\n\x05level\x18\x01 \x01(\x05\x12\x12\n\ntactics_id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ENTER_RACING_DUNGEON_PARAM_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTER_RACING_DUNGEON_PARAM']._serialized_start=36
  _globals['_ENTER_RACING_DUNGEON_PARAM']._serialized_end=99
# @@protoc_insertion_point(module_scope)

