# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: EQUIP_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'EQUIP_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ATTR_ENHANCE_FAILED_DATA_pb2 as ATTR__ENHANCE__FAILED__DATA__pb2
import EQUIP_ENHANCE_DATA_pb2 as EQUIP__ENHANCE__DATA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x45QUIP_DATA.proto\x1a\x1e\x41TTR_ENHANCE_FAILED_DATA.proto\x1a\x18\x45QUIP_ENHANCE_DATA.proto\"\xfa\x02\n\nEQUIP_DATA\x12\x0f\n\x07\x65quipid\x18\x01 \x01(\x04\x12\x12\n\ntemplateid\x18\x02 \x01(\x05\x12\x15\n\requip_char_id\x18\x03 \x01(\x04\x12\x36\n\x0elegacy_enhance\x18\x04 \x03(\x0b\x32\x1e.EQUIP_DATA.LegacyEnhanceEntry\x12\x36\n\x19legacy_equip_enhance_data\x18\x05 \x01(\x0b\x32\x13.EQUIP_ENHANCE_DATA\x12)\n\x07\x65nhance\x18\x08 \x03(\x0b\x32\x18.EQUIP_DATA.EnhanceEntry\x12/\n\x12\x65quip_enhance_data\x18\t \x01(\x0b\x32\x13.EQUIP_ENHANCE_DATA\x1a\x34\n\x12LegacyEnhanceEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a.\n\x0c\x45nhanceEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EQUIP_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EQUIP_DATA_LEGACYENHANCEENTRY']._loaded_options = None
  _globals['_EQUIP_DATA_LEGACYENHANCEENTRY']._serialized_options = b'8\001'
  _globals['_EQUIP_DATA_ENHANCEENTRY']._loaded_options = None
  _globals['_EQUIP_DATA_ENHANCEENTRY']._serialized_options = b'8\001'
  _globals['_EQUIP_DATA']._serialized_start=79
  _globals['_EQUIP_DATA']._serialized_end=457
  _globals['_EQUIP_DATA_LEGACYENHANCEENTRY']._serialized_start=357
  _globals['_EQUIP_DATA_LEGACYENHANCEENTRY']._serialized_end=409
  _globals['_EQUIP_DATA_ENHANCEENTRY']._serialized_start=411
  _globals['_EQUIP_DATA_ENHANCEENTRY']._serialized_end=457
# @@protoc_insertion_point(module_scope)

