# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FRIEND_BUSINESS_CARD_TYPE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'FRIEND_BUSINESS_CARD_TYPE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x46RIEND_BUSINESS_CARD_TYPE.proto*5\n\x19\x46RIEND_BUSINESS_CARD_TYPE\x12\x0c\n\x08Stranger\x10\x00\x12\n\n\x06\x46riend\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FRIEND_BUSINESS_CARD_TYPE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRIEND_BUSINESS_CARD_TYPE']._serialized_start=35
  _globals['_FRIEND_BUSINESS_CARD_TYPE']._serialized_end=88
# @@protoc_insertion_point(module_scope)
