# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FRIEND_PERSONAL_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'FRIEND_PERSONAL_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x46RIEND_PERSONAL_DATA.proto\"\xc7\x01\n\x14\x46RIEND_PERSONAL_DATA\x12\x16\n\x0euser_avatar_id\x18\x01 \x01(\x05\x12\x1c\n\x14user_avatar_frame_id\x18\x02 \x01(\x05\x12\x1e\n\x16\x62usiness_card_topic_id\x18\x03 \x01(\x05\x12\x11\n\tsignature\x18\x04 \x01(\t\x12\x11\n\tchar_list\x18\x05 \x03(\x04\x12!\n\x19\x62usiness_card_expand_flag\x18\x06 \x01(\x08\x12\x10\n\x08psn_only\x18\x07 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FRIEND_PERSONAL_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRIEND_PERSONAL_DATA']._serialized_start=31
  _globals['_FRIEND_PERSONAL_DATA']._serialized_end=230
# @@protoc_insertion_point(module_scope)
