# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FRIEND_BUSINESS_CARD_DATA_STRANGER.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'FRIEND_BUSINESS_CARD_DATA_STRANGER.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SROLE_INFO_pb2 as SROLE__INFO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(FRIEND_BUSINESS_CARD_DATA_STRANGER.proto\x1a\x10SROLE_INFO.proto\"D\n\"FRIEND_BUSINESS_CARD_DATA_STRANGER\x12\x1e\n\tbase_data\x18\x01 \x01(\x0b\x32\x0b.SROLE_INFOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FRIEND_BUSINESS_CARD_DATA_STRANGER_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRIEND_BUSINESS_CARD_DATA_STRANGER']._serialized_start=62
  _globals['_FRIEND_BUSINESS_CARD_DATA_STRANGER']._serialized_end=130
# @@protoc_insertion_point(module_scope)
