# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GEM_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'GEM_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GEM_TERM_pb2 as GEM__TERM__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eGEM_DATA.proto\x1a\x0eGEM_TERM.proto\"\x83\x01\n\x08GEM_DATA\x12\x0e\n\x06gem_id\x18\x01 \x01(\x04\x12\x13\n\x0btemplate_id\x18\x02 \x01(\x05\x12\x12\n\ntotal_cost\x18\x03 \x01(\x05\x12\x18\n\x05terms\x18\x04 \x03(\x0b\x32\t.GEM_TERM\x12\x11\n\tweapon_id\x18\x05 \x01(\x04\x12\x11\n\tdomain_id\x18\x06 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GEM_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEM_DATA']._serialized_start=35
  _globals['_GEM_DATA']._serialized_end=166
# @@protoc_insertion_point(module_scope)

