# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GLOBAL_BUFF_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'GLOBAL_BUFF_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_BLACKBOARD_pb2 as BATTLE__BLACKBOARD__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16GLOBAL_BUFF_INFO.proto\x1a\x17\x42\x41TTLE_BLACKBOARD.proto\"Z\n\x10GLOBAL_BUFF_INFO\x12\x1a\n\x12global_buff_num_id\x18\x01 \x01(\x05\x12*\n\x0e\x61ssigned_items\x18\x02 \x01(\x0b\x32\x12.BATTLE_BLACKBOARDb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GLOBAL_BUFF_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GLOBAL_BUFF_INFO']._serialized_start=51
  _globals['_GLOBAL_BUFF_INFO']._serialized_end=141
# @@protoc_insertion_point(module_scope)
