# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HG_THIRD_ACCOUNT_TYPE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HG_THIRD_ACCOUNT_TYPE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bHG_THIRD_ACCOUNT_TYPE.proto*C\n\x15HG_THIRD_ACCOUNT_TYPE\x12\x16\n\x12\x41\x63\x63ountTypeDefault\x10\x00\x12\x12\n\x0e\x41\x63\x63ountTypePsn\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HG_THIRD_ACCOUNT_TYPE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HG_THIRD_ACCOUNT_TYPE']._serialized_start=31
  _globals['_HG_THIRD_ACCOUNT_TYPE']._serialized_end=98
# @@protoc_insertion_point(module_scope)
