# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ITEM_INST.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ITEM_INST.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EQUIP_DATA_pb2 as EQUIP__DATA__pb2
import GEM_DATA_pb2 as GEM__DATA__pb2
import ITEM_FLAG_pb2 as ITEM__FLAG__pb2
import ITEM_INST_EMPTY_pb2 as ITEM__INST__EMPTY__pb2
import WEAPON_DATA_pb2 as WEAPON__DATA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fITEM_INST.proto\x1a\x10\x45QUIP_DATA.proto\x1a\x0eGEM_DATA.proto\x1a\x0fITEM_FLAG.proto\x1a\x15ITEM_INST_EMPTY.proto\x1a\x11WEAPON_DATA.proto\"\xb7\x02\n\tITEM_INST\x12\x0f\n\x07inst_id\x18\x01 \x01(\x04\x12\x0f\n\x07is_lock\x18\x65 \x01(\x08\x12\x0e\n\x06is_new\x18\x66 \x01(\x08\x12$\n\x10legacy_item_flag\x18\x04 \x01(\x0e\x32\n.ITEM_FLAG\x12\x18\n\x10legacy_expire_ts\x18\x05 \x01(\x03\x12\x1d\n\titem_flag\x18g \x01(\x0e\x32\n.ITEM_FLAG\x12\x11\n\texpire_ts\x18h \x01(\x03\x12\x1c\n\x05\x65quip\x18\x02 \x01(\x0b\x32\x0b.EQUIP_DATAH\x00\x12\x18\n\x03gem\x18\x03 \x01(\x0b\x32\t.GEM_DATAH\x00\x12\x1e\n\x06weapon\x18\x06 \x01(\x0b\x32\x0c.WEAPON_DATAH\x00\x12!\n\x05\x65mpty\x18\x1f \x01(\x0b\x32\x10.ITEM_INST_EMPTYH\x00\x42\x0b\n\tinst_implb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ITEM_INST_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM_INST']._serialized_start=113
  _globals['_ITEM_INST']._serialized_end=424
# @@protoc_insertion_point(module_scope)
