# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_ACTIVITY_CONDITIONAL_MULTI_STAGE_BASE_CHANGE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_ACTIVITY_CONDITIONAL_MULTI_STAGE_BASE_CHANGE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCD_ACTIVITY_CONDITIONAL_MULTI_STAGE_BASE_pb2 as SCD__ACTIVITY__CONDITIONAL__MULTI__STAGE__BASE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5SC_ACTIVITY_CONDITIONAL_MULTI_STAGE_BASE_CHANGE.proto\x1a/SCD_ACTIVITY_CONDITIONAL_MULTI_STAGE_BASE.proto\"n\n/SC_ACTIVITY_CONDITIONAL_MULTI_STAGE_BASE_CHANGE\x12;\n\x07\x63hanges\x18\x01 \x03(\x0b\x32*.SCD_ACTIVITY_CONDITIONAL_MULTI_STAGE_BASEb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_ACTIVITY_CONDITIONAL_MULTI_STAGE_BASE_CHANGE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_ACTIVITY_CONDITIONAL_MULTI_STAGE_BASE_CHANGE']._serialized_start=106
  _globals['_SC_ACTIVITY_CONDITIONAL_MULTI_STAGE_BASE_CHANGE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
