# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_ACHIEVE_SYNC_PERSONAL_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_ACHIEVE_SYNC_PERSONAL_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCD_ACHIEVE_PERSONAL_INFO_pb2 as SCD__ACHIEVE__PERSONAL__INFO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#SC_ACHIEVE_SYNC_PERSONAL_INFO.proto\x1a\x1fSCD_ACHIEVE_PERSONAL_INFO.proto\"[\n\x1dSC_ACHIEVE_SYNC_PERSONAL_INFO\x12:\n\x16\x61\x63hieve_personal_infos\x18\x01 \x03(\x0b\x32\x1a.SCD_ACHIEVE_PERSONAL_INFOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_ACHIEVE_SYNC_PERSONAL_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_ACHIEVE_SYNC_PERSONAL_INFO']._serialized_start=72
  _globals['_SC_ACHIEVE_SYNC_PERSONAL_INFO']._serialized_end=163
# @@protoc_insertion_point(module_scope)
