# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_ACHIEVE_DISPLAY_INFO_CHANGE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_ACHIEVE_DISPLAY_INFO_CHANGE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$SC_ACHIEVE_DISPLAY_INFO_CHANGE.proto\" \n\x1eSC_ACHIEVE_DISPLAY_INFO_CHANGEb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_ACHIEVE_DISPLAY_INFO_CHANGE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_ACHIEVE_DISPLAY_INFO_CHANGE']._serialized_start=40
  _globals['_SC_ACHIEVE_DISPLAY_INFO_CHANGE']._serialized_end=72
# @@protoc_insertion_point(module_scope)
