# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_ACHIEVE_SYNC.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_ACHIEVE_SYNC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCD_ACHIEVE_DISPLAY_INFO_pb2 as SCD__ACHIEVE__DISPLAY__INFO__pb2
import SCD_ACHIEVE_PERSONAL_INFO_pb2 as SCD__ACHIEVE__PERSONAL__INFO__pb2
import SCD_ACHIEVE_PUBLIC_INFO_pb2 as SCD__ACHIEVE__PUBLIC__INFO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15SC_ACHIEVE_SYNC.proto\x1a\x1eSCD_ACHIEVE_DISPLAY_INFO.proto\x1a\x1fSCD_ACHIEVE_PERSONAL_INFO.proto\x1a\x1dSCD_ACHIEVE_PUBLIC_INFO.proto\"\xbe\x01\n\x0fSC_ACHIEVE_SYNC\x12\x36\n\x14\x61\x63hieve_public_infos\x18\x01 \x03(\x0b\x32\x18.SCD_ACHIEVE_PUBLIC_INFO\x12:\n\x16\x61\x63hieve_personal_infos\x18\x02 \x03(\x0b\x32\x1a.SCD_ACHIEVE_PERSONAL_INFO\x12\x37\n\x14\x61\x63hieve_display_info\x18\x03 \x01(\x0b\x32\x19.SCD_ACHIEVE_DISPLAY_INFOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_ACHIEVE_SYNC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_ACHIEVE_SYNC']._serialized_start=122
  _globals['_SC_ACHIEVE_SYNC']._serialized_end=312
# @@protoc_insertion_point(module_scope)
