# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_BATTLE_ADD_GLOBAL_BUFF.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_BATTLE_ADD_GLOBAL_BUFF.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GLOBAL_BUFF_INFO_pb2 as GLOBAL__BUFF__INFO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fSC_BATTLE_ADD_GLOBAL_BUFF.proto\x1a\x16GLOBAL_BUFF_INFO.proto\"H\n\x19SC_BATTLE_ADD_GLOBAL_BUFF\x12+\n\x10global_buff_info\x18\x01 \x01(\x0b\x32\x11.GLOBAL_BUFF_INFOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_BATTLE_ADD_GLOBAL_BUFF_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_BATTLE_ADD_GLOBAL_BUFF']._serialized_start=59
  _globals['_SC_BATTLE_ADD_GLOBAL_BUFF']._serialized_end=131
# @@protoc_insertion_point(module_scope)
