# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_CHAR_SKILL_INFOS.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_CHAR_SKILL_INFOS.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SKILL_LEVEL_INFO_pb2 as SKILL__LEVEL__INFO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19SC_CHAR_SKILL_INFOS.proto\x1a\x16SKILL_LEVEL_INFO.proto\"R\n\x13SC_CHAR_SKILL_INFOS\x12\x13\n\x0b\x63har_obj_id\x18\x01 \x01(\x04\x12&\n\x0blevel_infos\x18\x02 \x03(\x0b\x32\x11.SKILL_LEVEL_INFOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_CHAR_SKILL_INFOS_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_CHAR_SKILL_INFOS']._serialized_start=53
  _globals['_SC_CHAR_SKILL_INFOS']._serialized_end=135
# @@protoc_insertion_point(module_scope)
