# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_CHAR_BAG_SET_MAX_TEAM_MEMBER_COUNT.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_CHAR_BAG_SET_MAX_TEAM_MEMBER_COUNT.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+SC_CHAR_BAG_SET_MAX_TEAM_MEMBER_COUNT.proto\"_\n%SC_CHAR_BAG_SET_MAX_TEAM_MEMBER_COUNT\x12\"\n\x1amax_char_team_member_count\x18\x01 \x01(\r\x12\x12\n\nscope_name\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_CHAR_BAG_SET_MAX_TEAM_MEMBER_COUNT_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_CHAR_BAG_SET_MAX_TEAM_MEMBER_COUNT']._serialized_start=47
  _globals['_SC_CHAR_BAG_SET_MAX_TEAM_MEMBER_COUNT']._serialized_end=142
# @@protoc_insertion_point(module_scope)
