# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_CHAR_BAG_SET_TEAM.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_CHAR_BAG_SET_TEAM.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CHAR_BAG_TEAM_TYPE_pb2 as CHAR__BAG__TEAM__TYPE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aSC_CHAR_BAG_SET_TEAM.proto\x1a\x18\x43HAR_BAG_TEAM_TYPE.proto\"\x8c\x01\n\x14SC_CHAR_BAG_SET_TEAM\x12&\n\tteam_type\x18\x01 \x01(\x0e\x32\x13.CHAR_BAG_TEAM_TYPE\x12\x12\n\nteam_index\x18\x02 \x01(\x05\x12\x11\n\tchar_team\x18\x03 \x03(\x04\x12\x12\n\nscope_name\x18\x04 \x01(\x05\x12\x11\n\tleader_id\x18\x05 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_CHAR_BAG_SET_TEAM_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_CHAR_BAG_SET_TEAM']._serialized_start=57
  _globals['_SC_CHAR_BAG_SET_TEAM']._serialized_end=197
# @@protoc_insertion_point(module_scope)
