# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_EQUIP_MEDICINE_MODIFY.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_EQUIP_MEDICINE_MODIFY.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eSC_EQUIP_MEDICINE_MODIFY.proto\"F\n\x18SC_EQUIP_MEDICINE_MODIFY\x12\x0f\n\x07\x63har_id\x18\x01 \x01(\x04\x12\x19\n\x11\x65quip_medicine_id\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_EQUIP_MEDICINE_MODIFY_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_EQUIP_MEDICINE_MODIFY']._serialized_start=34
  _globals['_SC_EQUIP_MEDICINE_MODIFY']._serialized_end=104
# @@protoc_insertion_point(module_scope)
