# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_EQUIP_ENHANCE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_EQUIP_ENHANCE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EQUIP_DATA_pb2 as EQUIP__DATA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16SC_EQUIP_ENHANCE.proto\x1a\x10\x45QUIP_DATA.proto\"J\n\x10SC_EQUIP_ENHANCE\x12\x15\n\requip_inst_id\x18\x01 \x01(\x04\x12\x1f\n\nequip_data\x18\x02 \x01(\x0b\x32\x0b.EQUIP_DATAb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_EQUIP_ENHANCE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_EQUIP_ENHANCE']._serialized_start=44
  _globals['_SC_EQUIP_ENHANCE']._serialized_end=118
# @@protoc_insertion_point(module_scope)
