# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_FRIEND_PERSONAL_DATA_SYNC.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_FRIEND_PERSONAL_DATA_SYNC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FRIEND_PERSONAL_DATA_pb2 as FRIEND__PERSONAL__DATA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"SC_FRIEND_PERSONAL_DATA_SYNC.proto\x1a\x1a\x46RIEND_PERSONAL_DATA.proto\"C\n\x1cSC_FRIEND_PERSONAL_DATA_SYNC\x12#\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x15.FRIEND_PERSONAL_DATAb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_FRIEND_PERSONAL_DATA_SYNC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_FRIEND_PERSONAL_DATA_SYNC']._serialized_start=66
  _globals['_SC_FRIEND_PERSONAL_DATA_SYNC']._serialized_end=133
# @@protoc_insertion_point(module_scope)
