# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_GAME_MECHANICS_SYNC_LEAVE_GAME_INST.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_GAME_MECHANICS_SYNC_LEAVE_GAME_INST.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,SC_GAME_MECHANICS_SYNC_LEAVE_GAME_INST.proto\"g\n&SC_GAME_MECHANICS_SYNC_LEAVE_GAME_INST\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x14\n\x0cgame_inst_id\x18\x02 \x01(\t\x12\x16\n\x0egame_unique_id\x18\x03 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_GAME_MECHANICS_SYNC_LEAVE_GAME_INST_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_GAME_MECHANICS_SYNC_LEAVE_GAME_INST']._serialized_start=48
  _globals['_SC_GAME_MECHANICS_SYNC_LEAVE_GAME_INST']._serialized_end=151
# @@protoc_insertion_point(module_scope)
