# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_GAME_MECHANICS_SYNC_CHALLENGE_COMPLETE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_GAME_MECHANICS_SYNC_CHALLENGE_COMPLETE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/SC_GAME_MECHANICS_SYNC_CHALLENGE_COMPLETE.proto\"x\n)SC_GAME_MECHANICS_SYNC_CHALLENGE_COMPLETE\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x0f\n\x07is_pass\x18\x02 \x01(\x08\x12\x16\n\x0e\x66orce_leave_ts\x18\x03 \x01(\x03\x12\x11\n\tpass_time\x18\x04 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_GAME_MECHANICS_SYNC_CHALLENGE_COMPLETE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_GAME_MECHANICS_SYNC_CHALLENGE_COMPLETE']._serialized_start=51
  _globals['_SC_GAME_MECHANICS_SYNC_CHALLENGE_COMPLETE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
