# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_GAME_MECHANICS_MODIFY_INST_TIME_FREEZE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_GAME_MECHANICS_MODIFY_INST_TIME_FREEZE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCD_GAME_MECHANICS_INST_TIME_FREEZE_pb2 as SCD__GAME__MECHANICS__INST__TIME__FREEZE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/SC_GAME_MECHANICS_MODIFY_INST_TIME_FREEZE.proto\x1a)SCD_GAME_MECHANICS_INST_TIME_FREEZE.proto\"}\n)SC_GAME_MECHANICS_MODIFY_INST_TIME_FREEZE\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12?\n\x11time_freeze_infos\x18\x02 \x03(\x0b\x32$.SCD_GAME_MECHANICS_INST_TIME_FREEZEb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_GAME_MECHANICS_MODIFY_INST_TIME_FREEZE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_GAME_MECHANICS_MODIFY_INST_TIME_FREEZE']._serialized_start=94
  _globals['_SC_GAME_MECHANICS_MODIFY_INST_TIME_FREEZE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
