# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_ITEM_BAG_COMMON_SYNC.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_ITEM_BAG_COMMON_SYNC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCD_ITEM_BAG_LT_ITEM_EXPIRE_RECORD_pb2 as SCD__ITEM__BAG__LT__ITEM__EXPIRE__RECORD__pb2
import SCD_ITEM_LOST_AND_FOUND_pb2 as SCD__ITEM__LOST__AND__FOUND__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dSC_ITEM_BAG_COMMON_SYNC.proto\x1a(SCD_ITEM_BAG_LT_ITEM_EXPIRE_RECORD.proto\x1a\x1dSCD_ITEM_LOST_AND_FOUND.proto\"\x90\x01\n\x17SC_ITEM_BAG_COMMON_SYNC\x12\x30\n\x0elost_and_found\x18\x01 \x01(\x0b\x32\x18.SCD_ITEM_LOST_AND_FOUND\x12\x43\n\x16lt_item_expire_records\x18\x02 \x03(\x0b\x32#.SCD_ITEM_BAG_LT_ITEM_EXPIRE_RECORDb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_ITEM_BAG_COMMON_SYNC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_ITEM_BAG_COMMON_SYNC']._serialized_start=107
  _globals['_SC_ITEM_BAG_COMMON_SYNC']._serialized_end=251
# @@protoc_insertion_point(module_scope)
