# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_ITEM_BAG_SCOPE_SYNC.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_ITEM_BAG_SCOPE_SYNC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCD_ITEM_BAG_pb2 as SCD__ITEM__BAG__pb2
import SCD_ITEM_BAG_SCOPE_ASSISTANT_pb2 as SCD__ITEM__BAG__SCOPE__ASSISTANT__pb2
import SCD_ITEM_BAG_SYNC_QUICK_BAR_pb2 as SCD__ITEM__BAG__SYNC__QUICK__BAR__pb2
import SCD_ITEM_DEPOT_pb2 as SCD__ITEM__DEPOT__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cSC_ITEM_BAG_SCOPE_SYNC.proto\x1a\x12SCD_ITEM_BAG.proto\x1a\"SCD_ITEM_BAG_SCOPE_ASSISTANT.proto\x1a!SCD_ITEM_BAG_SYNC_QUICK_BAR.proto\x1a\x14SCD_ITEM_DEPOT.proto\"\xdf\x03\n\x16SC_ITEM_BAG_SCOPE_SYNC\x12\x1a\n\x03\x62\x61g\x18\x01 \x01(\x0b\x32\r.SCD_ITEM_BAG\x12@\n\rfactory_depot\x18\x02 \x03(\x0b\x32).SC_ITEM_BAG_SCOPE_SYNC.FactoryDepotEntry\x12\x31\n\x05\x64\x65pot\x18\x03 \x03(\x0b\x32\".SC_ITEM_BAG_SCOPE_SYNC.DepotEntry\x12/\n\tquick_bar\x18\x04 \x01(\x0b\x32\x1c.SCD_ITEM_BAG_SYNC_QUICK_BAR\x12\x30\n\tassistant\x18\x05 \x01(\x0b\x32\x1d.SCD_ITEM_BAG_SCOPE_ASSISTANT\x12\x12\n\nscope_name\x18\x0b \x01(\x05\x12\x1a\n\x12\x63urrent_chapter_id\x18\x0c \x01(\t\x12\x1c\n\x14spaceship_chapter_id\x18\r \x01(\t\x1a\x44\n\x11\x46\x61\x63toryDepotEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.SCD_ITEM_DEPOT:\x02\x38\x01\x1a=\n\nDepotEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.SCD_ITEM_DEPOT:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_ITEM_BAG_SCOPE_SYNC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_ITEM_BAG_SCOPE_SYNC_FACTORYDEPOTENTRY']._loaded_options = None
  _globals['_SC_ITEM_BAG_SCOPE_SYNC_FACTORYDEPOTENTRY']._serialized_options = b'8\001'
  _globals['_SC_ITEM_BAG_SCOPE_SYNC_DEPOTENTRY']._loaded_options = None
  _globals['_SC_ITEM_BAG_SCOPE_SYNC_DEPOTENTRY']._serialized_options = b'8\001'
  _globals['_SC_ITEM_BAG_SCOPE_SYNC']._serialized_start=146
  _globals['_SC_ITEM_BAG_SCOPE_SYNC']._serialized_end=625
  _globals['_SC_ITEM_BAG_SCOPE_SYNC_FACTORYDEPOTENTRY']._serialized_start=494
  _globals['_SC_ITEM_BAG_SCOPE_SYNC_FACTORYDEPOTENTRY']._serialized_end=562
  _globals['_SC_ITEM_BAG_SCOPE_SYNC_DEPOTENTRY']._serialized_start=564
  _globals['_SC_ITEM_BAG_SCOPE_SYNC_DEPOTENTRY']._serialized_end=625
# @@protoc_insertion_point(module_scope)
