# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_ITEM_BAG_SCOPE_MODIFY.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_ITEM_BAG_SCOPE_MODIFY.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCD_ITEM_BAG_MODIFY_pb2 as SCD__ITEM__BAG__MODIFY__pb2
import SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY_pb2 as SCD__ITEM__BAG__SCOPE__ASSISTANT__MODIFY__pb2
import SCD_ITEM_BAG_SYNC_QUICK_BAR_pb2 as SCD__ITEM__BAG__SYNC__QUICK__BAR__pb2
import SCD_ITEM_DEPOT_MODIFY_pb2 as SCD__ITEM__DEPOT__MODIFY__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eSC_ITEM_BAG_SCOPE_MODIFY.proto\x1a\x19SCD_ITEM_BAG_MODIFY.proto\x1a)SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY.proto\x1a!SCD_ITEM_BAG_SYNC_QUICK_BAR.proto\x1a\x1bSCD_ITEM_DEPOT_MODIFY.proto\"\xfc\x03\n\x18SC_ITEM_BAG_SCOPE_MODIFY\x12!\n\x03\x62\x61g\x18\x01 \x01(\x0b\x32\x14.SCD_ITEM_BAG_MODIFY\x12\x42\n\rfactory_depot\x18\x02 \x03(\x0b\x32+.SC_ITEM_BAG_SCOPE_MODIFY.FactoryDepotEntry\x12\x33\n\x05\x64\x65pot\x18\x03 \x03(\x0b\x32$.SC_ITEM_BAG_SCOPE_MODIFY.DepotEntry\x12/\n\tquick_bar\x18\x04 \x01(\x0b\x32\x1c.SCD_ITEM_BAG_SYNC_QUICK_BAR\x12\x37\n\tassistant\x18\x05 \x01(\x0b\x32$.SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY\x12\x12\n\nscope_name\x18\x0b \x01(\x05\x12\x1a\n\x12\x63urrent_chapter_id\x18\x0c \x01(\t\x12\x17\n\x0fis_scope_delete\x18\x0e \x01(\x08\x1aK\n\x11\x46\x61\x63toryDepotEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.SCD_ITEM_DEPOT_MODIFY:\x02\x38\x01\x1a\x44\n\nDepotEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.SCD_ITEM_DEPOT_MODIFY:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_ITEM_BAG_SCOPE_MODIFY_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_ITEM_BAG_SCOPE_MODIFY_FACTORYDEPOTENTRY']._loaded_options = None
  _globals['_SC_ITEM_BAG_SCOPE_MODIFY_FACTORYDEPOTENTRY']._serialized_options = b'8\001'
  _globals['_SC_ITEM_BAG_SCOPE_MODIFY_DEPOTENTRY']._loaded_options = None
  _globals['_SC_ITEM_BAG_SCOPE_MODIFY_DEPOTENTRY']._serialized_options = b'8\001'
  _globals['_SC_ITEM_BAG_SCOPE_MODIFY']._serialized_start=169
  _globals['_SC_ITEM_BAG_SCOPE_MODIFY']._serialized_end=677
  _globals['_SC_ITEM_BAG_SCOPE_MODIFY_FACTORYDEPOTENTRY']._serialized_start=532
  _globals['_SC_ITEM_BAG_SCOPE_MODIFY_FACTORYDEPOTENTRY']._serialized_end=607
  _globals['_SC_ITEM_BAG_SCOPE_MODIFY_DEPOTENTRY']._serialized_start=609
  _globals['_SC_ITEM_BAG_SCOPE_MODIFY_DEPOTENTRY']._serialized_end=677
# @@protoc_insertion_point(module_scope)
