# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_SYNC_CHAR_BAG_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_SYNC_CHAR_BAG_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CHAR_BAG_TEAM_TYPE_pb2 as CHAR__BAG__TEAM__TYPE__pb2
import CHAR_INFO_pb2 as CHAR__INFO__pb2
import CHAR_TEAM_INFO_pb2 as CHAR__TEAM__INFO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bSC_SYNC_CHAR_BAG_INFO.proto\x1a\x18\x43HAR_BAG_TEAM_TYPE.proto\x1a\x0f\x43HAR_INFO.proto\x1a\x14\x43HAR_TEAM_INFO.proto\"\x95\x02\n\x15SC_SYNC_CHAR_BAG_INFO\x12\x1d\n\tchar_info\x18\x01 \x03(\x0b\x32\n.CHAR_INFO\x12\"\n\tteam_info\x18\x02 \x03(\x0b\x32\x0f.CHAR_TEAM_INFO\x12\x17\n\x0f\x63urr_team_index\x18\x03 \x01(\x05\x12\"\n\x1amax_char_team_member_count\x18\x04 \x01(\r\x12\'\n\x0etemp_team_info\x18\x05 \x01(\x0b\x32\x0f.CHAR_TEAM_INFO\x12&\n\tteam_type\x18\x06 \x01(\x0e\x32\x13.CHAR_BAG_TEAM_TYPE\x12\x12\n\nscope_name\x18\n \x01(\x05\x12\x17\n\x0fis_scope_delete\x18\x0b \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_SYNC_CHAR_BAG_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_SYNC_CHAR_BAG_INFO']._serialized_start=97
  _globals['_SC_SYNC_CHAR_BAG_INFO']._serialized_end=374
# @@protoc_insertion_point(module_scope)

