# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_SYNC_WEEK_RAID_SETTLEMENT.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_SYNC_WEEK_RAID_SETTLEMENT.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ITEM_BUNDLE_pb2 as ITEM__BUNDLE__pb2
import WEEK_RAID_SETTLEMENT_CONVERT_pb2 as WEEK__RAID__SETTLEMENT__CONVERT__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"SC_SYNC_WEEK_RAID_SETTLEMENT.proto\x1a\x11ITEM_BUNDLE.proto\x1a\"WEEK_RAID_SETTLEMENT_CONVERT.proto\"\xdd\x01\n\x1cSC_SYNC_WEEK_RAID_SETTLEMENT\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x10\n\x08\x62p_score\x18\x02 \x01(\x05\x12\x14\n\x0c\x64\x61nger_meter\x18\x03 \x01(\x05\x12\x16\n\x0etotal_playtime\x18\x04 \x01(\x03\x12 \n\nloot_items\x18\x05 \x03(\x0b\x32\x0c.ITEM_BUNDLE\x12\x34\n\rconvert_items\x18\x06 \x03(\x0b\x32\x1d.WEEK_RAID_SETTLEMENT_CONVERT\x12\x14\n\x0c\x63onvert_rate\x18\x07 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_SYNC_WEEK_RAID_SETTLEMENT_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_SYNC_WEEK_RAID_SETTLEMENT']._serialized_start=94
  _globals['_SC_SYNC_WEEK_RAID_SETTLEMENT']._serialized_end=315
# @@protoc_insertion_point(module_scope)
