# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_SELF_SCENE_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_SELF_SCENE_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LEVEL_SCRIPT_INFO_pb2 as LEVEL__SCRIPT__INFO__pb2
import SCD_SCENE_TEAM_INFO_pb2 as SCD__SCENE__TEAM__INFO__pb2
import SCENE_DROP_pb2 as SCENE__DROP__pb2
import SCENE_IMPL_DUNGEON_pb2 as SCENE__IMPL__DUNGEON__pb2
import SCENE_IMPL_EMPTY_pb2 as SCENE__IMPL__EMPTY__pb2
import SCENE_OBJECT_DETAIL_CONTAINER_pb2 as SCENE__OBJECT__DETAIL__CONTAINER__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18SC_SELF_SCENE_INFO.proto\x1a\x17LEVEL_SCRIPT_INFO.proto\x1a\x19SCD_SCENE_TEAM_INFO.proto\x1a\x10SCENE_DROP.proto\x1a\x18SCENE_IMPL_DUNGEON.proto\x1a\x16SCENE_IMPL_EMPTY.proto\x1a#SCENE_OBJECT_DETAIL_CONTAINER.proto\"\xff\x02\n\x12SC_SELF_SCENE_INFO\x12\x14\n\x0cscene_num_id\x18\x01 \x01(\x05\x12\x10\n\x08scene_id\x18\x02 \x01(\x04\x12.\n\x06\x64\x65tail\x18\x03 \x01(\x0b\x32\x1e.SCENE_OBJECT_DETAIL_CONTAINER\x12\x14\n\x0crevive_chars\x18\x07 \x03(\x04\x12)\n\rlevel_scripts\x18\x08 \x03(\x0b\x32\x12.LEVEL_SCRIPT_INFO\x12\x18\n\x10self_info_reason\x18\t \x01(\x05\x12\x13\n\x0bunlock_area\x18\n \x03(\t\x12\x1e\n\tdrop_list\x18\x0e \x03(\x0b\x32\x0b.SCENE_DROP\x12\'\n\tteam_info\x18\x10 \x01(\x0b\x32\x14.SCD_SCENE_TEAM_INFO\x12&\n\x07\x64ungeon\x18\x0b \x01(\x0b\x32\x13.SCENE_IMPL_DUNGEONH\x00\x12\"\n\x05\x65mpty\x18\x0c \x01(\x0b\x32\x11.SCENE_IMPL_EMPTYH\x00\x42\x0c\n\nscene_implb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_SELF_SCENE_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_SELF_SCENE_INFO']._serialized_start=186
  _globals['_SC_SELF_SCENE_INFO']._serialized_end=569
# @@protoc_insertion_point(module_scope)

