# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SC_WEAPON_BREAKTHROUGH.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SC_WEAPON_BREAKTHROUGH.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cSC_WEAPON_BREAKTHROUGH.proto\"C\n\x16SC_WEAPON_BREAKTHROUGH\x12\x10\n\x08weaponid\x18\x01 \x01(\x04\x12\x17\n\x0f\x62reakthrough_lv\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SC_WEAPON_BREAKTHROUGH_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SC_WEAPON_BREAKTHROUGH']._serialized_start=32
  _globals['_SC_WEAPON_BREAKTHROUGH']._serialized_end=99
# @@protoc_insertion_point(module_scope)
