# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCD_SCENE_TEAM_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCD_SCENE_TEAM_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CHAR_BAG_TEAM_TYPE_pb2 as CHAR__BAG__TEAM__TYPE__pb2
import VECTOR_pb2 as VECTOR__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19SCD_SCENE_TEAM_INFO.proto\x1a\x18\x43HAR_BAG_TEAM_TYPE.proto\x1a\x0cVECTOR.proto\"\xcf\x02\n\x13SCD_SCENE_TEAM_INFO\x12&\n\tteam_type\x18\x01 \x01(\x0e\x32\x13.CHAR_BAG_TEAM_TYPE\x12\x12\n\nteam_index\x18\x02 \x01(\x05\x12\x19\n\x11team_change_token\x18\x03 \x01(\x04\x12\x15\n\rcur_leader_id\x18\x04 \x01(\x04\x12\x1e\n\x16\x65nter_npc_teammate_ids\x18\x05 \x03(\x04\x12\x1e\n\x16leave_npc_teammate_ids\x18\x06 \x03(\x04\x12\"\n\x1anew_npc_teammate_action_id\x18\x07 \x01(\t\x12\x32\n!enter_npc_teammate_start_pos_list\x18\x08 \x03(\x0b\x32\x07.VECTOR\x12\x32\n!enter_npc_teammate_start_rot_list\x18\t \x03(\x0b\x32\x07.VECTORb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCD_SCENE_TEAM_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCD_SCENE_TEAM_INFO']._serialized_start=70
  _globals['_SCD_SCENE_TEAM_INFO']._serialized_end=405
# @@protoc_insertion_point(module_scope)

