# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCD_ACHIEVE_PERSONAL_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCD_ACHIEVE_PERSONAL_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCD_ACHIEVE_CONDITIONS_pb2 as SCD__ACHIEVE__CONDITIONS__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fSCD_ACHIEVE_PERSONAL_INFO.proto\x1a\x1cSCD_ACHIEVE_CONDITIONS.proto\"\xa2\x01\n\x19SCD_ACHIEVE_PERSONAL_INFO\x12\x16\n\x0e\x61\x63hieve_num_id\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\x05\x12\x11\n\tis_plated\x18\x03 \x01(\x08\x12\x16\n\x0eobtain_time_ts\x18\x04 \x01(\x03\x12\x33\n\x12\x61\x63hieve_conditions\x18\x05 \x01(\x0b\x32\x17.SCD_ACHIEVE_CONDITIONSb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCD_ACHIEVE_PERSONAL_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCD_ACHIEVE_PERSONAL_INFO']._serialized_start=66
  _globals['_SCD_ACHIEVE_PERSONAL_INFO']._serialized_end=228
# @@protoc_insertion_point(module_scope)
