# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCD_ITEM_DEPOT.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCD_ITEM_DEPOT.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCD_ITEM_GRID_pb2 as SCD__ITEM__GRID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14SCD_ITEM_DEPOT.proto\x1a\x13SCD_ITEM_GRID.proto\"\xa8\x01\n\x0eSCD_ITEM_DEPOT\x12<\n\x0fstackable_items\x18\x01 \x03(\x0b\x32#.SCD_ITEM_DEPOT.StackableItemsEntry\x12!\n\tinst_list\x18\x02 \x03(\x0b\x32\x0e.SCD_ITEM_GRID\x1a\x35\n\x13StackableItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCD_ITEM_DEPOT_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCD_ITEM_DEPOT_STACKABLEITEMSENTRY']._loaded_options = None
  _globals['_SCD_ITEM_DEPOT_STACKABLEITEMSENTRY']._serialized_options = b'8\001'
  _globals['_SCD_ITEM_DEPOT']._serialized_start=46
  _globals['_SCD_ITEM_DEPOT']._serialized_end=214
  _globals['_SCD_ITEM_DEPOT_STACKABLEITEMSENTRY']._serialized_start=161
  _globals['_SCD_ITEM_DEPOT_STACKABLEITEMSENTRY']._serialized_end=214
# @@protoc_insertion_point(module_scope)
