# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCD_ACHIEVE_CONDITIONS.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCD_ACHIEVE_CONDITIONS.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cSCD_ACHIEVE_CONDITIONS.proto\"\x98\x01\n\x16SCD_ACHIEVE_CONDITIONS\x12\x46\n\x10\x63ondition_values\x18\x01 \x03(\x0b\x32,.SCD_ACHIEVE_CONDITIONS.ConditionValuesEntry\x1a\x36\n\x14\x43onditionValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCD_ACHIEVE_CONDITIONS_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCD_ACHIEVE_CONDITIONS_CONDITIONVALUESENTRY']._loaded_options = None
  _globals['_SCD_ACHIEVE_CONDITIONS_CONDITIONVALUESENTRY']._serialized_options = b'8\001'
  _globals['_SCD_ACHIEVE_CONDITIONS']._serialized_start=33
  _globals['_SCD_ACHIEVE_CONDITIONS']._serialized_end=185
  _globals['_SCD_ACHIEVE_CONDITIONS_CONDITIONVALUESENTRY']._serialized_start=131
  _globals['_SCD_ACHIEVE_CONDITIONS_CONDITIONVALUESENTRY']._serialized_end=185
# @@protoc_insertion_point(module_scope)
