# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCD_ITEM_BAG_SYNC_QUICK_BAR.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCD_ITEM_BAG_SYNC_QUICK_BAR.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!SCD_ITEM_BAG_SYNC_QUICK_BAR.proto\";\n\x1bSCD_ITEM_BAG_SYNC_QUICK_BAR\x12\x0f\n\x07item_id\x18\x01 \x03(\t\x12\x0b\n\x03pos\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCD_ITEM_BAG_SYNC_QUICK_BAR_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCD_ITEM_BAG_SYNC_QUICK_BAR']._serialized_start=37
  _globals['_SCD_ITEM_BAG_SYNC_QUICK_BAR']._serialized_end=96
# @@protoc_insertion_point(module_scope)
