# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCD_ITEM_BAG_MODIFY.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCD_ITEM_BAG_MODIFY.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCD_ITEM_GRID_pb2 as SCD__ITEM__GRID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19SCD_ITEM_BAG_MODIFY.proto\x1a\x13SCD_ITEM_GRID.proto\"Z\n\x13SCD_ITEM_BAG_MODIFY\x12\x12\n\ngrid_limit\x18\x01 \x01(\x05\x12\x1d\n\x05grids\x18\x02 \x03(\x0b\x32\x0e.SCD_ITEM_GRID\x12\x10\n\x08\x64\x65l_list\x18\x03 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCD_ITEM_BAG_MODIFY_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCD_ITEM_BAG_MODIFY']._serialized_start=50
  _globals['_SCD_ITEM_BAG_MODIFY']._serialized_end=140
# @@protoc_insertion_point(module_scope)
