# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCD_ACHIEVE_DISPLAY_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCD_ACHIEVE_DISPLAY_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eSCD_ACHIEVE_DISPLAY_INFO.proto\"\x9a\x01\n\x18SCD_ACHIEVE_DISPLAY_INFO\x12\x37\n\x07\x64isplay\x18\x01 \x03(\x0b\x32&.SCD_ACHIEVE_DISPLAY_INFO.DisplayEntry\x12\x15\n\rdisplay_depot\x18\x02 \x03(\x05\x1a.\n\x0c\x44isplayEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCD_ACHIEVE_DISPLAY_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCD_ACHIEVE_DISPLAY_INFO_DISPLAYENTRY']._loaded_options = None
  _globals['_SCD_ACHIEVE_DISPLAY_INFO_DISPLAYENTRY']._serialized_options = b'8\001'
  _globals['_SCD_ACHIEVE_DISPLAY_INFO']._serialized_start=35
  _globals['_SCD_ACHIEVE_DISPLAY_INFO']._serialized_end=189
  _globals['_SCD_ACHIEVE_DISPLAY_INFO_DISPLAYENTRY']._serialized_start=143
  _globals['_SCD_ACHIEVE_DISPLAY_INFO_DISPLAYENTRY']._serialized_end=189
# @@protoc_insertion_point(module_scope)
