# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCD_ITEM_DEPOT_MODIFY.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCD_ITEM_DEPOT_MODIFY.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCD_ITEM_GRID_pb2 as SCD__ITEM__GRID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bSCD_ITEM_DEPOT_MODIFY.proto\x1a\x13SCD_ITEM_GRID.proto\"\xaa\x02\n\x15SCD_ITEM_DEPOT_MODIFY\x12\x30\n\x05items\x18\x01 \x03(\x0b\x32!.SCD_ITEM_DEPOT_MODIFY.ItemsEntry\x12!\n\tinst_list\x18\x02 \x03(\x0b\x32\x0e.SCD_ITEM_GRID\x12\x15\n\rdel_inst_list\x18\x03 \x03(\x04\x12\x41\n\x0einfinite_items\x18\x04 \x03(\x0b\x32).SCD_ITEM_DEPOT_MODIFY.InfiniteItemsEntry\x1a,\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x34\n\x12InfiniteItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCD_ITEM_DEPOT_MODIFY_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCD_ITEM_DEPOT_MODIFY_ITEMSENTRY']._loaded_options = None
  _globals['_SCD_ITEM_DEPOT_MODIFY_ITEMSENTRY']._serialized_options = b'8\001'
  _globals['_SCD_ITEM_DEPOT_MODIFY_INFINITEITEMSENTRY']._loaded_options = None
  _globals['_SCD_ITEM_DEPOT_MODIFY_INFINITEITEMSENTRY']._serialized_options = b'8\001'
  _globals['_SCD_ITEM_DEPOT_MODIFY']._serialized_start=53
  _globals['_SCD_ITEM_DEPOT_MODIFY']._serialized_end=351
  _globals['_SCD_ITEM_DEPOT_MODIFY_ITEMSENTRY']._serialized_start=253
  _globals['_SCD_ITEM_DEPOT_MODIFY_ITEMSENTRY']._serialized_end=297
  _globals['_SCD_ITEM_DEPOT_MODIFY_INFINITEITEMSENTRY']._serialized_start=299
  _globals['_SCD_ITEM_DEPOT_MODIFY_INFINITEITEMSENTRY']._serialized_end=351
# @@protoc_insertion_point(module_scope)
