# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCD_GAME_MECHANICS_INST_TIME_FREEZE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCD_GAME_MECHANICS_INST_TIME_FREEZE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)SCD_GAME_MECHANICS_INST_TIME_FREEZE.proto\"X\n#SCD_GAME_MECHANICS_INST_TIME_FREEZE\x12\x10\n\x08time_key\x18\x01 \x01(\x05\x12\x1f\n\x17total_freeze_time_in_ms\x18\x02 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCD_GAME_MECHANICS_INST_TIME_FREEZE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCD_GAME_MECHANICS_INST_TIME_FREEZE']._serialized_start=45
  _globals['_SCD_GAME_MECHANICS_INST_TIME_FREEZE']._serialized_end=133
# @@protoc_insertion_point(module_scope)
