# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY.proto\"\xe3\x02\n#SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY\x12L\n\rlast_use_time\x18\x01 \x03(\x0b\x32\x35.SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY.LastUseTimeEntry\x12O\n\x0e\x63\x61nnot_destroy\x18\x02 \x03(\x0b\x32\x37.SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY.CannotDestroyEntry\x12\x1a\n\x12\x63\x61nnot_destroy_all\x18\x03 \x01(\x08\x12\x17\n\x0f\x62\x61tch_move_flag\x18\x04 \x01(\x03\x1a\x32\n\x10LastUseTimeEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x34\n\x12\x43\x61nnotDestroyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY_LASTUSETIMEENTRY']._loaded_options = None
  _globals['_SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY_LASTUSETIMEENTRY']._serialized_options = b'8\001'
  _globals['_SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY_CANNOTDESTROYENTRY']._loaded_options = None
  _globals['_SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY_CANNOTDESTROYENTRY']._serialized_options = b'8\001'
  _globals['_SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY']._serialized_start=46
  _globals['_SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY']._serialized_end=401
  _globals['_SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY_LASTUSETIMEENTRY']._serialized_start=297
  _globals['_SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY_LASTUSETIMEENTRY']._serialized_end=347
  _globals['_SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY_CANNOTDESTROYENTRY']._serialized_start=349
  _globals['_SCD_ITEM_BAG_SCOPE_ASSISTANT_MODIFY_CANNOTDESTROYENTRY']._serialized_end=401
# @@protoc_insertion_point(module_scope)
