# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCD_ACHIEVE_PUBLIC_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCD_ACHIEVE_PUBLIC_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dSCD_ACHIEVE_PUBLIC_INFO.proto\"X\n\x17SCD_ACHIEVE_PUBLIC_INFO\x12\x16\n\x0e\x61\x63hieve_num_id\x18\x01 \x01(\x05\x12\x11\n\topen_time\x18\x02 \x01(\x03\x12\x12\n\nclose_time\x18\x03 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCD_ACHIEVE_PUBLIC_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCD_ACHIEVE_PUBLIC_INFO']._serialized_start=33
  _globals['_SCD_ACHIEVE_PUBLIC_INFO']._serialized_end=121
# @@protoc_insertion_point(module_scope)
