# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCENE_IMPL_DUNGEON.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCENE_IMPL_DUNGEON.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18SCENE_IMPL_DUNGEON.proto\"\x94\x01\n\x12SCENE_IMPL_DUNGEON\x12\x12\n\ndungeon_id\x18\x01 \x01(\t\x12\x1b\n\x13\x63hallenge_expire_ts\x18\x02 \x01(\x03\x12\x18\n\x10leave_dungeon_ts\x18\x03 \x01(\x03\x12\x11\n\tis_reward\x18\x04 \x01(\x08\x12\x0f\n\x07is_calc\x18\x05 \x01(\x08\x12\x0f\n\x07is_pass\x18\x06 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCENE_IMPL_DUNGEON_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENE_IMPL_DUNGEON']._serialized_start=29
  _globals['_SCENE_IMPL_DUNGEON']._serialized_end=177
# @@protoc_insertion_point(module_scope)

