# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCENE_OBJECT_COMMON_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCENE_OBJECT_COMMON_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import VECTOR_pb2 as VECTOR__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eSCENE_OBJECT_COMMON_INFO.proto\x1a\x0cVECTOR.proto\"\xf9\x01\n\x18SCENE_OBJECT_COMMON_INFO\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x12\n\ntemplateid\x18\x03 \x01(\t\x12\x19\n\x08position\x18\x04 \x01(\x0b\x32\x07.VECTOR\x12\x19\n\x08rotation\x18\x05 \x01(\x0b\x32\x07.VECTOR\x12\x1e\n\x16\x62\x65long_level_script_id\x18\x06 \x01(\x04\x12\x14\n\x0cscene_num_id\x18\x07 \x01(\x05\x12\n\n\x02hp\x18\x08 \x01(\x01\x12\x1d\n\x15\x62\x65long_script_slot_id\x18\t \x01(\r\x12\x18\n\x10is_battle_create\x18\n \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCENE_OBJECT_COMMON_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENE_OBJECT_COMMON_INFO']._serialized_start=49
  _globals['_SCENE_OBJECT_COMMON_INFO']._serialized_end=298
# @@protoc_insertion_point(module_scope)

