# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCENE_INTERACTIVE.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCENE_INTERACTIVE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_MGR_INFO_pb2 as BATTLE__MGR__INFO__pb2
import DYNAMIC_PARAMETER_pb2 as DYNAMIC__PARAMETER__pb2
import SCENE_OBJECT_COMMON_INFO_pb2 as SCENE__OBJECT__COMMON__INFO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17SCENE_INTERACTIVE.proto\x1a\x15\x42\x41TTLE_MGR_INFO.proto\x1a\x17\x44YNAMIC_PARAMETER.proto\x1a\x1eSCENE_OBJECT_COMMON_INFO.proto\"\x9b\x02\n\x11SCENE_INTERACTIVE\x12.\n\x0b\x63ommon_info\x18\x01 \x01(\x0b\x32\x19.SCENE_OBJECT_COMMON_INFO\x12\x11\n\torigin_id\x18\x02 \x01(\x04\x12\x36\n\nproperties\x18\x03 \x03(\x0b\x32\".SCENE_INTERACTIVE.PropertiesEntry\x12\x0c\n\x04meta\x18\x05 \x01(\x05\x12%\n\x0b\x62\x61ttle_info\x18\x06 \x01(\x0b\x32\x10.BATTLE_MGR_INFO\x12\x0f\n\x07\x62ond_id\x18\x07 \x01(\x04\x1a\x45\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.DYNAMIC_PARAMETER:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCENE_INTERACTIVE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENE_INTERACTIVE_PROPERTIESENTRY']._loaded_options = None
  _globals['_SCENE_INTERACTIVE_PROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_SCENE_INTERACTIVE']._serialized_start=108
  _globals['_SCENE_INTERACTIVE']._serialized_end=391
  _globals['_SCENE_INTERACTIVE_PROPERTIESENTRY']._serialized_start=322
  _globals['_SCENE_INTERACTIVE_PROPERTIESENTRY']._serialized_end=391
# @@protoc_insertion_point(module_scope)

