# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCENE_SUMMON.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCENE_SUMMON.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ATTR_INFO_pb2 as ATTR__INFO__pb2
import BATTLE_BLACKBOARD_pb2 as BATTLE__BLACKBOARD__pb2
import BATTLE_MGR_INFO_pb2 as BATTLE__MGR__INFO__pb2
import SCENE_OBJECT_COMMON_INFO_pb2 as SCENE__OBJECT__COMMON__INFO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12SCENE_SUMMON.proto\x1a\x0f\x41TTR_INFO.proto\x1a\x17\x42\x41TTLE_BLACKBOARD.proto\x1a\x15\x42\x41TTLE_MGR_INFO.proto\x1a\x1eSCENE_OBJECT_COMMON_INFO.proto\"\xbf\x01\n\x0cSCENE_SUMMON\x12.\n\x0b\x63ommon_info\x18\x01 \x01(\x0b\x32\x19.SCENE_OBJECT_COMMON_INFO\x12\x19\n\x05\x61ttrs\x18\x03 \x03(\x0b\x32\n.ATTR_INFO\x12%\n\x0b\x62\x61ttle_info\x18\x04 \x01(\x0b\x32\x10.BATTLE_MGR_INFO\x12\x15\n\rcast_skill_id\x18\x05 \x01(\t\x12&\n\nblackboard\x18\x06 \x01(\x0b\x32\x12.BATTLE_BLACKBOARDb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCENE_SUMMON_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENE_SUMMON']._serialized_start=120
  _globals['_SCENE_SUMMON']._serialized_end=311
# @@protoc_insertion_point(module_scope)

