# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCENE_OBJECT_DETAIL_CONTAINER.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCENE_OBJECT_DETAIL_CONTAINER.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCENE_CHARACTER_pb2 as SCENE__CHARACTER__pb2
import SCENE_INTERACTIVE_pb2 as SCENE__INTERACTIVE__pb2
import SCENE_MONSTER_pb2 as SCENE__MONSTER__pb2
import SCENE_NPC_pb2 as SCENE__NPC__pb2
import SCENE_SUMMON_pb2 as SCENE__SUMMON__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#SCENE_OBJECT_DETAIL_CONTAINER.proto\x1a\x15SCENE_CHARACTER.proto\x1a\x17SCENE_INTERACTIVE.proto\x1a\x13SCENE_MONSTER.proto\x1a\x0fSCENE_NPC.proto\x1a\x12SCENE_SUMMON.proto\"\xda\x01\n\x1dSCENE_OBJECT_DETAIL_CONTAINER\x12#\n\tchar_list\x18\x01 \x03(\x0b\x32\x10.SCENE_CHARACTER\x12$\n\x0cmonster_list\x18\x02 \x03(\x0b\x32\x0e.SCENE_MONSTER\x12,\n\x10interactive_list\x18\x03 \x03(\x0b\x32\x12.SCENE_INTERACTIVE\x12\x1c\n\x08npc_list\x18\x04 \x03(\x0b\x32\n.SCENE_NPC\x12\"\n\x0bsummon_list\x18\x05 \x03(\x0b\x32\r.SCENE_SUMMONb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCENE_OBJECT_DETAIL_CONTAINER_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENE_OBJECT_DETAIL_CONTAINER']._serialized_start=146
  _globals['_SCENE_OBJECT_DETAIL_CONTAINER']._serialized_end=364
# @@protoc_insertion_point(module_scope)

