# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCENE_MONSTER.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SCENE_MONSTER.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ATTR_INFO_pb2 as ATTR__INFO__pb2
import BATTLE_MGR_INFO_pb2 as BATTLE__MGR__INFO__pb2
import SCENE_OBJECT_COMMON_INFO_pb2 as SCENE__OBJECT__COMMON__INFO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SCENE_MONSTER.proto\x1a\x0f\x41TTR_INFO.proto\x1a\x15\x42\x41TTLE_MGR_INFO.proto\x1a\x1eSCENE_OBJECT_COMMON_INFO.proto\"\xa3\x01\n\rSCENE_MONSTER\x12.\n\x0b\x63ommon_info\x18\x01 \x01(\x0b\x32\x19.SCENE_OBJECT_COMMON_INFO\x12\x11\n\torigin_id\x18\x02 \x01(\x04\x12\r\n\x05level\x18\x03 \x01(\x05\x12\x19\n\x05\x61ttrs\x18\x04 \x03(\x0b\x32\n.ATTR_INFO\x12%\n\x0b\x62\x61ttle_info\x18\x05 \x01(\x0b\x32\x10.BATTLE_MGR_INFOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCENE_MONSTER_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENE_MONSTER']._serialized_start=96
  _globals['_SCENE_MONSTER']._serialized_end=259
# @@protoc_insertion_point(module_scope)

