# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SERVER_SKILL.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SERVER_SKILL.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_BLACKBOARD_pb2 as BATTLE__BLACKBOARD__pb2
import BATTLE_SKILL_SOURCE_pb2 as BATTLE__SKILL__SOURCE__pb2
import TEMPLATE_ID_pb2 as TEMPLATE__ID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12SERVER_SKILL.proto\x1a\x17\x42\x41TTLE_BLACKBOARD.proto\x1a\x19\x42\x41TTLE_SKILL_SOURCE.proto\x1a\x11TEMPLATE_ID.proto\"\x8a\x02\n\x0cSERVER_SKILL\x12\x1e\n\x08skill_id\x18\x01 \x01(\x0b\x32\x0c.TEMPLATE_ID\x12\x0f\n\x07inst_id\x18\x02 \x01(\x04\x12\x14\n\x0cpotential_lv\x18\x03 \x01(\x05\x12\r\n\x05level\x18\x04 \x01(\x05\x12&\n\nblackboard\x18\x05 \x01(\x0b\x32\x12.BATTLE_BLACKBOARD\x12$\n\x06source\x18\x06 \x01(\x0e\x32\x14.BATTLE_SKILL_SOURCE\x12\x17\n\x0ftalent_node_ids\x18\x07 \x03(\t\x12\x16\n\x0eis_server_init\x18\x08 \x01(\x08\x12\x11\n\tis_enable\x18\t \x01(\x08\x12\x12\n\nis_passive\x18\n \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SERVER_SKILL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVER_SKILL']._serialized_start=94
  _globals['_SERVER_SKILL']._serialized_end=360
# @@protoc_insertion_point(module_scope)

