# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SERVER_BUFF_STACKING_GROUP.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SERVER_BUFF_STACKING_GROUP.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n SERVER_BUFF_STACKING_GROUP.proto\"\x8f\x01\n\x1aSERVER_BUFF_STACKING_GROUP\x12\x14\n\x0cstacking_key\x18\x01 \x01(\t\x12\x15\n\rstacking_type\x18\x02 \x01(\x05\x12\x15\n\rmax_stack_cnt\x18\x03 \x01(\x05\x12\x16\n\x0eis_server_init\x18\x04 \x01(\x08\x12\x15\n\rbuff_inst_ids\x18\x05 \x03(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SERVER_BUFF_STACKING_GROUP_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVER_BUFF_STACKING_GROUP']._serialized_start=37
  _globals['_SERVER_BUFF_STACKING_GROUP']._serialized_end=180
# @@protoc_insertion_point(module_scope)

