# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SKILL_LEVEL_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SKILL_LEVEL_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16SKILL_LEVEL_INFO.proto\"p\n\x10SKILL_LEVEL_INFO\x12\x10\n\x08skill_id\x18\x01 \x01(\t\x12\x13\n\x0bskill_level\x18\x02 \x01(\x05\x12\x17\n\x0fskill_max_level\x18\x03 \x01(\x05\x12\x1c\n\x14skill_enhanced_level\x18\x04 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SKILL_LEVEL_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SKILL_LEVEL_INFO']._serialized_start=26
  _globals['_SKILL_LEVEL_INFO']._serialized_end=138
# @@protoc_insertion_point(module_scope)

