# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SROLE_DATA_ACHIEVEMENT.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SROLE_DATA_ACHIEVEMENT.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SROLE_DATA_ACHIEVEMENT_INFO_pb2 as SROLE__DATA__ACHIEVEMENT__INFO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cSROLE_DATA_ACHIEVEMENT.proto\x1a!SROLE_DATA_ACHIEVEMENT_INFO.proto\"\xb0\x01\n\x16SROLE_DATA_ACHIEVEMENT\x12\x35\n\x07\x64isplay\x18\x01 \x03(\x0b\x32$.SROLE_DATA_ACHIEVEMENT.DisplayEntry\x12/\n\tinfo_list\x18\x02 \x03(\x0b\x32\x1c.SROLE_DATA_ACHIEVEMENT_INFO\x1a.\n\x0c\x44isplayEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SROLE_DATA_ACHIEVEMENT_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SROLE_DATA_ACHIEVEMENT_DISPLAYENTRY']._loaded_options = None
  _globals['_SROLE_DATA_ACHIEVEMENT_DISPLAYENTRY']._serialized_options = b'8\001'
  _globals['_SROLE_DATA_ACHIEVEMENT']._serialized_start=68
  _globals['_SROLE_DATA_ACHIEVEMENT']._serialized_end=244
  _globals['_SROLE_DATA_ACHIEVEMENT_DISPLAYENTRY']._serialized_start=198
  _globals['_SROLE_DATA_ACHIEVEMENT_DISPLAYENTRY']._serialized_end=244
# @@protoc_insertion_point(module_scope)
