# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SROLE_DATA_DOMAIN_DEV_SYSTEM.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SROLE_DATA_DOMAIN_DEV_SYSTEM.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SROLE_DATA_DOMAIN_DEV_pb2 as SROLE__DATA__DOMAIN__DEV__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"SROLE_DATA_DOMAIN_DEV_SYSTEM.proto\x1a\x1bSROLE_DATA_DOMAIN_DEV.proto\"G\n\x1cSROLE_DATA_DOMAIN_DEV_SYSTEM\x12\'\n\x07\x64omains\x18\x01 \x03(\x0b\x32\x16.SROLE_DATA_DOMAIN_DEVb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SROLE_DATA_DOMAIN_DEV_SYSTEM_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SROLE_DATA_DOMAIN_DEV_SYSTEM']._serialized_start=67
  _globals['_SROLE_DATA_DOMAIN_DEV_SYSTEM']._serialized_end=138
# @@protoc_insertion_point(module_scope)
