# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SROLE_INFO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SROLE_INFO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FRIEND_CHAR_INFO_pb2 as FRIEND__CHAR__INFO__pb2
import HG_THIRD_ACCOUNT_TYPE_pb2 as HG__THIRD__ACCOUNT__TYPE__pb2
import SROLE_DATA_ACHIEVEMENT_pb2 as SROLE__DATA__ACHIEVEMENT__pb2
import SROLE_DATA_DOMAIN_DEV_SYSTEM_pb2 as SROLE__DATA__DOMAIN__DEV__SYSTEM__pb2
import SROLE_DATA_STATISTIC_pb2 as SROLE__DATA__STATISTIC__pb2
import THIRD_ACCOUNT_DATA_pb2 as THIRD__ACCOUNT__DATA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10SROLE_INFO.proto\x1a\x16\x46RIEND_CHAR_INFO.proto\x1a\x1bHG_THIRD_ACCOUNT_TYPE.proto\x1a\x1cSROLE_DATA_ACHIEVEMENT.proto\x1a\"SROLE_DATA_DOMAIN_DEV_SYSTEM.proto\x1a\x1aSROLE_DATA_STATISTIC.proto\x1a\x18THIRD_ACCOUNT_DATA.proto\"\xd1\x04\n\nSROLE_INFO\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08short_id\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\r\x12\x1e\n\x16\x62usiness_card_topic_id\x18\x04 \x01(\x05\x12\x11\n\tsignature\x18\x05 \x01(\t\x12\x16\n\x0euser_avatar_id\x18\x06 \x01(\x05\x12\x1c\n\x14user_avatar_frame_id\x18\x07 \x01(\x05\x12\x17\n\x0f\x61\x64venture_level\x18\x08 \x01(\r\x12\x13\n\x0bworld_level\x18\t \x01(\r\x12\x17\n\x0fmain_mission_id\x18\n \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x0b \x01(\x03\x12\x18\n\x10platform_role_id\x18\x0c \x01(\t\x12\x31\n\ndomain_dev\x18\r \x01(\x0b\x32\x1d.SROLE_DATA_DOMAIN_DEV_SYSTEM\x12,\n\x0b\x61\x63hievement\x18\x0e \x01(\x0b\x32\x17.SROLE_DATA_ACHIEVEMENT\x12(\n\tstatistic\x18\x0f \x01(\x0b\x32\x15.SROLE_DATA_STATISTIC\x12$\n\tchar_list\x18\x10 \x03(\x0b\x32\x11.FRIEND_CHAR_INFO\x12!\n\x19\x62usiness_card_expand_flag\x18\x11 \x01(\x08\x12/\n\x0flast_login_type\x18\x12 \x01(\x0e\x32\x16.HG_THIRD_ACCOUNT_TYPE\x12/\n\x12third_account_data\x18\x13 \x01(\x0b\x32\x13.THIRD_ACCOUNT_DATAb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SROLE_INFO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SROLE_INFO']._serialized_start=194
  _globals['_SROLE_INFO']._serialized_end=787
# @@protoc_insertion_point(module_scope)
