# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SROLE_DATA_DOMAIN_DEV.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SROLE_DATA_DOMAIN_DEV.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bSROLE_DATA_DOMAIN_DEV.proto\"9\n\x15SROLE_DATA_DOMAIN_DEV\x12\x11\n\tdomain_id\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SROLE_DATA_DOMAIN_DEV_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SROLE_DATA_DOMAIN_DEV']._serialized_start=31
  _globals['_SROLE_DATA_DOMAIN_DEV']._serialized_end=88
# @@protoc_insertion_point(module_scope)
