# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TEAM_CHAR_ID.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TEAM_CHAR_ID.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TEAM_CHAR_ID_TYPE_pb2 as TEAM__CHAR__ID__TYPE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12TEAM_CHAR_ID.proto\x1a\x17TEAM_CHAR_ID_TYPE.proto\"j\n\x0cTEAM_CHAR_ID\x12#\n\x07id_type\x18\x01 \x01(\x0e\x32\x12.TEAM_CHAR_ID_TYPE\x12\x10\n\x06obj_id\x18\x02 \x01(\x04H\x00\x12\x18\n\x0epreset_char_id\x18\x03 \x01(\tH\x00\x42\t\n\x07\x63har_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TEAM_CHAR_ID_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEAM_CHAR_ID']._serialized_start=47
  _globals['_TEAM_CHAR_ID']._serialized_end=153
# @@protoc_insertion_point(module_scope)

