# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TEMPLATE_ID.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TEMPLATE_ID.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BATTLE_ACTION_OWNER_TYPE_pb2 as BATTLE__ACTION__OWNER__TYPE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11TEMPLATE_ID.proto\x1a\x1e\x42\x41TTLE_ACTION_OWNER_TYPE.proto\"e\n\x0bTEMPLATE_ID\x12\'\n\x04type\x18\x03 \x01(\x0e\x32\x19.BATTLE_ACTION_OWNER_TYPE\x12\x10\n\x06str_id\x18\x01 \x01(\tH\x00\x12\x10\n\x06int_id\x18\x02 \x01(\x05H\x00\x42\t\n\x07id_implb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TEMPLATE_ID_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPLATE_ID']._serialized_start=53
  _globals['_TEMPLATE_ID']._serialized_end=154
# @@protoc_insertion_point(module_scope)

