# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: THIRD_ACCOUNT_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'THIRD_ACCOUNT_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HG_THIRD_ACCOUNT_TYPE_pb2 as HG__THIRD__ACCOUNT__TYPE__pb2
import THIRD_ACCOUNT_DATA_PSN_pb2 as THIRD__ACCOUNT__DATA__PSN__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18THIRD_ACCOUNT_DATA.proto\x1a\x1bHG_THIRD_ACCOUNT_TYPE.proto\x1a\x1cTHIRD_ACCOUNT_DATA_PSN.proto\"\x8b\x01\n\x12THIRD_ACCOUNT_DATA\x12\x37\n\x17third_account_data_type\x18\x01 \x01(\x0e\x32\x16.HG_THIRD_ACCOUNT_TYPE\x12\x34\n\x11third_account_psn\x18\x02 \x01(\x0b\x32\x17.THIRD_ACCOUNT_DATA_PSNH\x00\x42\x06\n\x04\x64\x61tab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'THIRD_ACCOUNT_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THIRD_ACCOUNT_DATA']._serialized_start=88
  _globals['_THIRD_ACCOUNT_DATA']._serialized_end=227
# @@protoc_insertion_point(module_scope)
