# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WEAPON_DATA.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'WEAPON_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11WEAPON_DATA.proto\"\xad\x01\n\x0bWEAPON_DATA\x12\x0f\n\x07inst_id\x18\x01 \x01(\x04\x12\x13\n\x0btemplate_id\x18\x02 \x01(\x05\x12\x0b\n\x03\x65xp\x18\x03 \x01(\x04\x12\x11\n\tweapon_lv\x18\x04 \x01(\r\x12\x11\n\trefine_lv\x18\x05 \x01(\r\x12\x17\n\x0f\x62reakthrough_lv\x18\x06 \x01(\r\x12\x15\n\requip_char_id\x18\x07 \x01(\x04\x12\x15\n\rattach_gem_id\x18\x08 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WEAPON_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEAPON_DATA']._serialized_start=22
  _globals['_WEAPON_DATA']._serialized_end=195
# @@protoc_insertion_point(module_scope)

